const params = {
    style: 'mtr',
    svg_height: 350,
    padding: 5.09,
    y_pc: 40,
    branch_spacing: 45,
    theme: ['toronto', 'l2', '#00923F', '#fff'],
    direction: 'l',
    current_stn_idx: 'l1mz',
    platform_num: '2',
    stn_list: {
        linestart: {
            parents: [],
            children: ['feg4'],
            name: ['路綫右端', 'RIGHT END'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [[]],
            },
            services: ['local'],
            facility: '',
            num: '32',
            secondaryName: false,
        },
        lineend: {
            parents: ['l1mz'],
            children: [],
            name: ['路綫左端', 'LEFT END'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [[]],
            },
            services: ['local'],
            facility: '',
            num: '00',
            secondaryName: false,
        },
        l1mz: {
            parents: ['iwf6'],
            children: ['lineend'],
            name: ['基柏龄', 'Kipling'],
            branch: {
                left: [],
                right: [],
            },
            num: '01',
            transfer: {
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [[]],
            },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        iwf6: {
            children: ['l1mz'],
            parents: ['fasm'],
            name: ['依士灵顿', 'Islington'],
            branch: {
                left: [],
                right: [],
            },
            num: '02',
            transfer: {
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [[]],
            },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        fasm: {
            name: ['皇家约克', 'Royal York'],
            secondaryName: false,
            num: '03',
            services: ['local'],
            parents: ['1yv2'],
            children: ['iwf6'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        '1yv2': {
            name: ['老磨坊', 'Old Mill'],
            secondaryName: false,
            num: '04',
            services: ['local'],
            parents: ['3xfr'],
            children: ['fasm'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        '3xfr': {
            name: ['珍街', 'Jane'],
            secondaryName: false,
            num: '05',
            services: ['local'],
            parents: ['xw9o'],
            children: ['1yv2'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        xw9o: {
            name: ['兰尼米德', 'Runnymede'],
            secondaryName: false,
            num: '06',
            services: ['local'],
            parents: ['ctjh'],
            children: ['3xfr'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        ctjh: {
            name: ['海柏公园', 'High Park'],
            secondaryName: false,
            num: '07',
            services: ['local'],
            parents: ['y82b'],
            children: ['xw9o'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        y82b: {
            name: ['基尔', 'Keele'],
            secondaryName: false,
            num: '08',
            services: ['local'],
            parents: ['d6ni'],
            children: ['ctjh'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        d6ni: {
            name: ['登打士西', 'Dundas West'],
            secondaryName: false,
            num: '09',
            services: ['local'],
            parents: ['hqep'],
            children: ['y82b'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        hqep: {
            name: ['兰士登', 'Lansdowne'],
            secondaryName: false,
            num: '10',
            services: ['local'],
            parents: ['1rvf'],
            children: ['d6ni'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        '1rvf': {
            name: ['德化林', 'Dufferin'],
            secondaryName: false,
            num: '11',
            services: ['local'],
            parents: ['tw7k'],
            children: ['hqep'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        tw7k: {
            name: ['奥盛顿', 'Ossington'],
            secondaryName: false,
            num: '12',
            services: ['local'],
            parents: ['te48'],
            children: ['1rvf'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        te48: {
            name: ['基斯蒂', 'Christie'],
            secondaryName: false,
            num: '13',
            services: ['local'],
            parents: ['yogu'],
            children: ['tw7k'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        yogu: {
            name: ['巴佛士', 'Bathurst'],
            secondaryName: false,
            num: '14',
            services: ['local'],
            parents: ['do5f'],
            children: ['te48'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        do5f: {
            name: ['士巴丹拿', 'Unnamed do5f'],
            secondaryName: false,
            num: '15',
            services: ['local'],
            parents: ['zwnj'],
            children: ['yogu'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[['toronto', 'l1', '#F8C300', '#000', '1 央街－大学线', 'Line 2\\Yonge-University']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        zwnj: {
            name: ['圣乔治', 'St. George'],
            secondaryName: false,
            num: '16',
            services: ['local'],
            parents: ['0i8m'],
            children: ['do5f'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[['toronto', 'l1', '#F8C300', '#000', '1 央街－大学线', 'Line 2\\Yonge-University']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        '0i8m': {
            name: ['卑街', 'Bay'],
            secondaryName: false,
            num: '17',
            services: ['local'],
            parents: ['rhgq'],
            children: ['zwnj'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        rhgq: {
            name: ['布鲁亚－央街', 'Bloor-Yonge'],
            secondaryName: false,
            num: '18',
            services: ['local'],
            parents: ['6es5'],
            children: ['0i8m'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[['toronto', 'l1', '#F8C300', '#000', '1 央街－大学线', 'Line 2\\Yonge-University']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        '6es5': {
            name: ['雪邦', 'Sherbourne'],
            secondaryName: false,
            num: '19',
            services: ['local'],
            parents: ['fjt5'],
            children: ['rhgq'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        fjt5: {
            name: ['法兰卫城', 'Castle Frank'],
            secondaryName: false,
            num: '20',
            services: ['local'],
            parents: ['odgv'],
            children: ['6es5'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        odgv: {
            name: ['百乐汇', 'Broadview'],
            secondaryName: false,
            num: '21',
            services: ['local'],
            parents: ['pjty'],
            children: ['fjt5'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        pjty: {
            name: ['志士达', 'Chester'],
            secondaryName: false,
            num: '22',
            services: ['local'],
            parents: ['82le'],
            children: ['odgv'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        '82le': {
            name: ['坡路', 'Pape'],
            secondaryName: false,
            num: '23',
            services: ['local'],
            parents: ['c6ko'],
            children: ['pjty'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        c6ko: {
            name: ['当兰士', 'Donlands'],
            secondaryName: false,
            num: '24',
            services: ['local'],
            parents: ['0bkx'],
            children: ['82le'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        '0bkx': {
            name: ['坚活', 'Greenwood'],
            secondaryName: false,
            num: '25',
            services: ['local'],
            parents: ['x26q'],
            children: ['c6ko'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        x26q: {
            name: ['觉士维', 'Coxwell'],
            secondaryName: false,
            num: '26',
            services: ['local'],
            parents: ['7hs7'],
            children: ['0bkx'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        '7hs7': {
            name: ['活拜', 'Woodbine'],
            secondaryName: false,
            num: '27',
            services: ['local'],
            parents: ['76gw'],
            children: ['x26q'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        '76gw': {
            name: ['缅因街', 'Main Street'],
            secondaryName: false,
            num: '28',
            services: ['local'],
            parents: ['ci46'],
            children: ['7hs7'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        ci46: {
            name: ['维多利亚公园', 'Victoria Park'],
            secondaryName: false,
            num: '29',
            services: ['local'],
            parents: ['pqbs'],
            children: ['76gw'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        pqbs: {
            name: ['华登', 'Warden'],
            secondaryName: false,
            num: '30',
            services: ['local'],
            parents: ['feg4'],
            children: ['ci46'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        feg4: {
            name: ['坚尼地', 'Kennedy'],
            secondaryName: false,
            num: '31',
            services: ['local'],
            parents: ['linestart'],
            children: ['pqbs'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[['toronto', 'l3', '#0082C9', '#fff', '3 士嘉堡轻铁', 'Line 3\\Scarborough']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
    },
    line_name: ['2 布鲁亚－丹佛线', 'Line 2\\Bloor-Danforth'],
    psd_num: '1',
    line_num: '2',
    info_panel_type: 'gz28',
    direction_gz_x: 50,
    direction_gz_y: 70,
    customiseMTRDest: {
        isLegacy: false,
        terminal: false,
    },
    svgWidth: {
        destination: 1500,
        runin: 1500,
        railmap: 2500,
        indoor: 4000,
    },
    notesGZMTR: [],
    namePosMTR: {
        isStagger: true,
        isFlip: false,
    },
};

export default params;
