const params = {
    style: 'mtr',
    svg_height: 350,
    padding: 5.09,
    y_pc: 40,
    branch_spacing: 45,
    theme: ['toronto', 'l3', '#0082C9', '#fff'],
    direction: 'r',
    current_stn_idx: 'l1mz',
    platform_num: '2',
    stn_list: {
        linestart: {
            parents: [],
            children: ['l1mz'],
            name: ['路綫左端', 'LEFT END'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [[]],
            },
            services: ['local'],
            facility: '',
            num: '00',
            secondaryName: false,
        },
        lineend: {
            parents: ['ssez'],
            children: [],
            name: ['路綫右端', 'RIGHT END'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [[]],
            },
            services: ['local'],
            facility: '',
            num: '07',
            secondaryName: false,
        },
        l1mz: {
            parents: ['linestart'],
            children: ['iwf6'],
            name: ['麦高云', 'McCowan'],
            branch: {
                left: [],
                right: [],
            },
            num: '01',
            transfer: {
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [[]],
            },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        iwf6: {
            children: ['9rwu'],
            parents: ['l1mz'],
            name: ['士嘉堡中心', 'Scarborough Centre'],
            branch: {
                left: [],
                right: [],
            },
            num: '02',
            transfer: {
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [[]],
            },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        '9rwu': {
            name: ['美兰', 'Midland'],
            secondaryName: false,
            num: '03',
            services: ['local'],
            parents: ['iwf6'],
            children: ['jsko'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        jsko: {
            name: ['艾斯美', 'Ellesmere'],
            secondaryName: false,
            num: '04',
            services: ['local'],
            parents: ['9rwu'],
            children: ['modb'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        modb: {
            name: ['罗伦斯东', 'Lawrence East'],
            secondaryName: false,
            num: '05',
            services: ['local'],
            parents: ['jsko'],
            children: ['ssez'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        ssez: {
            name: ['坚尼地', 'Kennedy'],
            secondaryName: false,
            num: '06',
            services: ['local'],
            parents: ['modb'],
            children: ['lineend'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[['toronto', 'l2', '#00923F', '#fff', '3 布鲁亚－丹佛线', 'Line 3\\ Bloor-Danforth']], []],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
    },
    line_name: ['3 士嘉堡轻铁', 'Line 3\\ Scarborough'],
    psd_num: '1',
    line_num: '3',
    info_panel_type: 'gz28',
    direction_gz_x: 50,
    direction_gz_y: 70,
    customiseMTRDest: {
        isLegacy: false,
        terminal: false,
    },
    svgWidth: {
        destination: 1500,
        runin: 1500,
        railmap: 2000,
        indoor: 4000,
    },
    notesGZMTR: [],
    namePosMTR: {
        isStagger: true,
        isFlip: false,
    },
};

export default params;
