const params = {
    style: 'gzmtr',
    svg_height: 300,
    padding: 3.67,
    y_pc: 43.06,
    branch_spacing: 43.65,
    theme: ['klangvalley', 'kl3', '#ED8B2D', '#fff'],
    direction: 'l',
    current_stn_idx: '7e3x',
    platform_num: '3',
    stn_list: {
        linestart: {
            parents: [],
            children: ['ny2q'],
            name: ['路綫左端', 'LEFT END'],
            branch: { left: [], right: [] },
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            num: '00',
            secondaryName: false,
        },
        lineend: {
            parents: ['7e3x'],
            children: [],
            name: ['路綫右端', 'RIGHT END'],
            branch: { left: [], right: [] },
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            num: '18',
            secondaryName: false,
        },
        l1mz: {
            parents: ['iwf6'],
            children: ['lyqw'],
            name: ['半山芭 ', 'Pudu'],
            branch: { left: [], right: [] },
            num: '10',
            transfer: {
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [[['klangvalley', 'kl4', '#802A1B', '#fff', '大城堡线', 'Sri Pataling Line']]],
            },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        iwf6: {
            children: ['l1mz'],
            parents: ['0gcd'],
            name: ['汉都亚 ', 'Hang Tuah'],
            branch: { left: [], right: [] },
            num: '09',
            transfer: {
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [
                    [
                        ['klangvalley', 'kl4', '#802A1B', '#fff', '大城堡线', 'Sri Pataling Line'],
                        ['klangvalley', 'kl8', '#8DBB3B', '#fff', '吉隆坡单轨', 'KL Monorail Line'],
                    ],
                ],
            },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        ei9t: {
            parents: ['qbbb'],
            children: ['7e3x'],
            branch: { left: [], right: [] },
            name: ['丽阳花园 ', 'Cahaya'],
            num: '17',
            services: ['local'],
            facility: '',
            transfer: { info: [[]], osi_names: [], paid_area: true, tick_direc: 'r' },
            secondaryName: false,
        },
        qbbb: {
            parents: ['tgp4'],
            children: ['ei9t'],
            branch: { left: [], right: [] },
            name: ['千百家', 'Cempaka'],
            num: '16',
            services: ['local'],
            facility: '',
            transfer: { info: [[]], osi_names: [], paid_area: true, tick_direc: 'r' },
            secondaryName: false,
        },
        tgp4: {
            parents: ['su3g'],
            children: ['qbbb'],
            branch: { left: [], right: [] },
            name: [' 班登英达 ', 'Pandan Indah'],
            num: '15',
            services: ['local'],
            facility: '',
            transfer: {
                info: [[['klangvalley', 'kl13', '#818181', '#fff', '环状线', 'Circle Line']]],
                osi_names: [],
                paid_area: true,
                tick_direc: 'r',
            },
            secondaryName: false,
        },
        su3g: {
            parents: ['dre1'],
            children: ['tgp4'],
            branch: { left: [], right: [] },
            name: ['班登再也 ', 'Pandan Jaya'],
            num: '14',
            services: ['local'],
            facility: '',
            transfer: { info: [[]], osi_names: [], paid_area: true, tick_direc: 'r' },
            secondaryName: false,
        },
        dre1: {
            parents: ['9v64'],
            children: ['su3g'],
            branch: { left: [], right: [] },
            name: ['马鲁里 ', 'Maluri'],
            num: '13',
            services: ['local'],
            facility: '',
            transfer: {
                info: [[['klangvalley', 'kl9', '#007737', '#fff', '加影线', 'Kajang Line']]],
                osi_names: [],
                paid_area: true,
                tick_direc: 'r',
            },
            secondaryName: false,
        },
        '9v64': {
            parents: ['lyqw'],
            children: ['dre1'],
            branch: { left: [], right: [] },
            name: ['美和家 ', 'Miharja'],
            num: '12',
            services: ['local'],
            facility: '',
            transfer: { info: [[]], osi_names: [], paid_area: true, tick_direc: 'r' },
            secondaryName: false,
        },
        lyqw: {
            parents: ['l1mz'],
            children: ['9v64'],
            branch: { left: [], right: [] },
            name: ['陈秀连 ', 'Chan Sow Lin'],
            num: '11',
            services: ['local'],
            facility: '',
            transfer: {
                info: [
                    [
                        ['klangvalley', 'kl4', '#802A1B', '#fff', '大城堡线', 'Sri Pataling Line'],
                        ['klangvalley', 'kl12', '#F9C823', '#fff', '布城线', 'Putrajaya Line'],
                    ],
                ],
                osi_names: [],
                paid_area: true,
                tick_direc: 'r',
            },
            secondaryName: false,
        },
        '0gcd': {
            name: ['人民广场 ', 'Plaza Rakyat'],
            secondaryName: false,
            num: '08',
            services: ['local'],
            parents: ['svlx'],
            children: ['iwf6'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['klangvalley', 'kl4', '#802A1B', '#fff', '大城堡线', 'Sri Pataling Line']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        svlx: {
            name: ['占美清真寺 ', 'Masjid Jamek'],
            secondaryName: false,
            num: '07',
            services: ['local'],
            parents: ['s08h'],
            children: ['0gcd'],
            branch: { left: [], right: [] },
            transfer: {
                info: [
                    [
                        ['klangvalley', 'kl4', '#802A1B', '#fff', '大城堡线', 'Sri Pataling Line'],
                        ['klangvalley', 'kl5', '#E32D4A', '#fff', '格拉那再也线', 'Kelana Jaya Line'],
                    ],
                ],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        s08h: {
            name: ['市政局 ', 'Bandaraya'],
            secondaryName: false,
            num: '06',
            services: ['local'],
            parents: ['ojvh'],
            children: ['svlx'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['klangvalley', 'kl4', '#802A1B', '#fff', '大城堡线', 'Sri Pataling Line']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        ojvh: {
            name: ['苏丹伊斯迈 ', 'Sultan Ismail'],
            secondaryName: false,
            num: '05',
            services: ['local'],
            parents: ['naqs'],
            children: ['s08h'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['klangvalley', 'kl4', '#802A1B', '#fff', '大城堡线', 'Sri Pataling Line']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        naqs: {
            name: ['布特拉世贸中心', ' PWTC'],
            secondaryName: false,
            num: '04',
            services: ['local'],
            parents: ['epll'],
            children: ['ojvh'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['klangvalley', 'kl4', '#802A1B', '#fff', '大城堡线', 'Sri Pataling Line']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        epll: {
            name: ['蒂蒂旺沙 ', 'Titiwangsa'],
            secondaryName: false,
            num: '03',
            services: ['local'],
            parents: ['9uzg'],
            children: ['naqs'],
            branch: { left: [], right: [] },
            transfer: {
                info: [
                    [
                        ['klangvalley', 'kl4', '#802A1B', '#fff', '大城堡线', 'Sri Pataling Line'],
                        ['klangvalley', 'kl8', '#8DBB3B', '#fff', '吉隆坡单轨', 'KL Monorail Line'],
                        ['klangvalley', 'kl12', '#F9C823', '#fff', '布城线', 'Putrajaya Line'],
                        ['klangvalley', 'kl13', '#818181', '#fff', '环状线', 'Circle Line'],
                    ],
                ],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        '9uzg': {
            name: ['冼都 ', 'Sentul'],
            secondaryName: false,
            num: '02',
            services: ['local'],
            parents: ['ny2q'],
            children: ['epll'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['klangvalley', 'kl4', '#802A1B', '#fff', '大城堡线', 'Sri Pataling Line']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        ny2q: {
            name: ['冼都东 ', 'Sentul Timur'],
            secondaryName: false,
            num: '01',
            services: ['local'],
            parents: ['linestart'],
            children: ['9uzg'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['klangvalley', 'kl4', '#802A1B', '#fff', '大城堡线', 'Sri Pataling Line']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        '7e3x': {
            name: ['安邦 ', 'Ampang'],
            secondaryName: false,
            num: '18',
            services: ['local'],
            parents: ['ei9t'],
            children: ['lineend'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
    },
    line_name: ['安邦线', 'Ampang Line'],
    psd_num: '18',
    line_num: 'AG',
    info_panel_type: 'gz1421',
    direction_gz_x: 21.28,
    direction_gz_y: 79.02,
    customiseMTRDest: { isLegacy: false, terminal: false },
    svgWidth: { destination: 1000, runin: 1000, railmap: 1500, indoor: 1000 },
    notesGZMTR: [['布城线和环状线未开通。', 'Putrajaya Line and Circle Line are under construction.', 79.5, 75, true]],
    namePosMTR: { isStagger: true, isFlip: false },
};

export default params;
