const params = {
    style: 'mtr',
    svg_height: 300,
    padding: 13.261261261261263,
    y_pc: 40,
    branch_spacing: 45,
    theme: ['hongkong', 'ael', '#007078', '#fff'],
    direction: 'l',
    current_stn_idx: '7uan',
    platform_num: '1',
    stn_list: {
        linestart: {
            parents: [],
            children: ['0r9d'],
            name: ['路綫左端', 'LEFT END'],
            branch: { left: [], right: [] },
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            num: '00',
            facility: '',
            secondaryName: false,
        },
        lineend: {
            parents: ['iwf6'],
            children: [],
            name: ['路綫右端', 'RIGHT END'],
            branch: { left: [], right: [] },
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            num: '00',
            facility: '',
            secondaryName: false,
        },
        l1mz: {
            parents: ['m6b7'],
            children: ['iwf6'],
            name: ['九龍', 'Kowloon'],
            branch: { left: [], right: [] },
            num: '02',
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        iwf6: {
            children: ['lineend'],
            parents: ['l1mz'],
            name: ['香港', 'Hong Kong'],
            branch: { left: [], right: [] },
            num: '01',
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        m6b7: {
            parents: ['7uan'],
            children: ['l1mz'],
            branch: { left: [], right: [] },
            name: ['青衣', 'Tsing Yi'],
            num: '00',
            services: ['local'],
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            facility: '',
            secondaryName: false,
        },
        '7uan': {
            parents: ['0r9d'],
            children: ['m6b7'],
            branch: { left: [], right: [] },
            name: ['機場', 'Airport'],
            num: '00',
            services: ['local'],
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            facility: 'airport',
            secondaryName: false,
        },
        '0r9d': {
            parents: ['linestart'],
            children: ['7uan'],
            branch: { left: [], right: [] },
            name: ['博覽館', 'AsiaWorld-Expo'],
            num: '00',
            services: ['local'],
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            facility: '',
            secondaryName: false,
        },
    },
    line_name: ['機場快綫', 'Airport Express'],
    psd_num: '1',
    line_num: 'TW',
    info_panel_type: 'gz28',
    direction_gz_x: 50,
    direction_gz_y: 70,
    customiseMTRDest: { isLegacy: false, terminal: ['機場及博覽館', 'Airport and AsiaWorld-Expo'] },
    svgWidth: { destination: 1100, runin: 1100, railmap: 1100, indoor: 1100 },
    notesGZMTR: [],
    namePosMTR: { isStagger: true, isFlip: false },
};

export default params;
