const params = {
    style: 'mtr',
    svg_height: 300,
    padding: 23.02,
    y_pc: 40,
    branch_spacing: 45,
    theme: ['hongkong', 'drl', '#E777CB', '#fff'],
    direction: 'l',
    current_stn_idx: 'iwf6',
    platform_num: '1',
    stn_list: {
        linestart: {
            parents: [],
            children: ['l1mz'],
            name: ['路綫左端', 'LEFT END'],
            change_type: 'none',
            branch: { left: [], right: [] },
            interchange: [[]],
            transfer: { type: 'none', tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            usage: '',
            facility: '',
            num: '00',
        },
        lineend: {
            parents: ['iwf6'],
            children: [],
            name: ['路綫右端', 'RIGHT END'],
            change_type: 'none',
            branch: { left: [], right: [] },
            interchange: [[]],
            transfer: { type: 'none', tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            usage: '',
            facility: '',
            num: '00',
        },
        l1mz: {
            parents: ['linestart'],
            children: ['iwf6'],
            name: ['欣澳', 'Sunny Bay'],
            change_type: 'none',
            branch: { left: [], right: [] },
            num: '02',
            interchange: [[]],
            transfer: {
                type: 'int2',
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [[['hongkong', 'tcl', '#F38B00', '#fff', '東涌綫', 'Tung Chung Line']]],
            },
            services: ['local'],
            usage: '',
            facility: '',
        },
        iwf6: {
            children: ['lineend'],
            parents: ['l1mz'],
            name: ['迪士尼', 'Disneyland Resort'],
            change_type: 'none',
            branch: { left: [], right: [] },
            num: '01',
            interchange: [[]],
            transfer: { type: 'none', tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            usage: '',
            facility: 'disney',
        },
    },
    line_name: ['迪士尼綫', 'Disneyland Resort Line'],
    psd_num: '1',
    line_num: 'DR',
    info_panel_type: 'gz5',
    direction_gz_x: 37.7,
    direction_gz_y: 79.97,
    customiseMTRDest: { isLegacy: false, terminal: false },
    svgWidth: { destination: 800, runin: 1000, railmap: 800 },
    notesGZMTR: [],
    namePosMTR: { isStagger: false, isFlip: false },
};

export default params;
