const params = {
    style: 'mtr',
    svg_height: 300,
    svg_width: 1000,
    svg_dest_width: 1050,
    show_outer: true,
    padding: 5.353925353925354,
    y_pc: 42.5019305019305,
    strip_pc: 90,
    branch_spacing: 43.160875160875165,
    theme: ['hongkong', 'eal', '#61b4e4', '#fff'],
    direction: 'l',
    current_stn_idx: 'iwf6',
    platform_num: '4',
    txt_bg_gap: 15,
    txt_flip: true,
    stn_list: {
        linestart: {
            parents: [],
            children: ['m2ot', 'fhq4'],
            name: ['路綫左端', 'LEFT END'],
            change_type: 'none',
            branch: { left: [], right: ['through', 'fhq4'] },
            interchange: [[]],
            transfer: { type: 'none', tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
        },
        lineend: {
            parents: ['iwf6'],
            children: [],
            name: ['路綫右端', 'RIGHT END'],
            change_type: 'none',
            branch: { left: [], right: [] },
            interchange: [[]],
            transfer: { type: 'none', tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
        },
        l1mz: {
            parents: ['q027'],
            children: ['iwf6'],
            name: ['旺角東', 'Mong Kok East'],
            change_type: 'none',
            branch: { left: [], right: [] },
            num: '02',
            interchange: [[]],
            transfer: { type: 'none', tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
        },
        iwf6: {
            children: ['lineend'],
            parents: ['l1mz'],
            name: ['紅磡', 'Hung Hom'],
            change_type: 'int2',
            branch: { left: [], right: [] },
            num: '01',
            interchange: [[['hongkong', 'wrl', '#b6008d', '#fff', '西鐵綫', 'West Rail Line']]],
            transfer: {
                type: 'int2',
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [[['hongkong', 'wrl', '#b6008d', '#fff', '西鐵綫', 'West Rail Line']]],
            },
            services: ['local'],
        },
        q027: {
            parents: ['6r9r'],
            children: ['l1mz'],
            branch: { left: [], right: [] },
            name: ['九龍塘', 'Kowloon Tong'],
            change_type: 'int2',
            num: '03',
            interchange: [[['hongkong', 'ktl', '#00af41', '#fff', '觀塘綫', 'Kwun Tong Line']]],
            transfer: {
                type: 'int2',
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [[['hongkong', 'ktl', '#00af41', '#fff', '觀塘綫', 'Kwun Tong Line']]],
            },
            services: ['local'],
        },
        '6r9r': {
            parents: ['u8xj'],
            children: ['q027'],
            branch: { left: [], right: [] },
            name: ['大圍', 'Tai Wai'],
            change_type: 'int2',
            num: '04',
            interchange: [[['hongkong', 'mol', '#9a3820', '#fff', '屯馬綫一期', 'Tuen Ma Line Phase 1']]],
            transfer: {
                type: 'int2',
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [[['hongkong', 'mol', '#9a3820', '#fff', '屯馬綫一期', 'Tuen Ma Line Phase 1']]],
            },
            services: ['local'],
        },
        u8xj: {
            parents: ['hybz', '7gy7'],
            children: ['6r9r'],
            branch: { left: ['through', 'hybz'], right: [] },
            name: ['沙田', 'Sha Tin'],
            change_type: 'none',
            num: '05',
            interchange: [[]],
            transfer: { type: 'none', tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
        },
        '7gy7': {
            parents: ['rr8a'],
            children: ['u8xj'],
            branch: { left: [], right: [] },
            name: ['火炭', 'Fo Tan'],
            change_type: 'none',
            num: '06',
            interchange: [[]],
            transfer: { type: 'none', tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
        },
        rr8a: {
            parents: ['fwhz'],
            children: ['hybz', '7gy7'],
            branch: { left: [], right: ['through', 'hybz'] },
            name: ['大學', 'University'],
            change_type: 'none',
            num: '08',
            interchange: [[]],
            transfer: { type: 'none', tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
        },
        fwhz: {
            parents: ['7dwu'],
            children: ['rr8a'],
            branch: { left: [], right: [] },
            name: ['大埔墟', 'Tai Po Market'],
            change_type: 'none',
            num: '09',
            interchange: [[]],
            transfer: { type: 'none', tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
        },
        '7dwu': {
            parents: ['jce3'],
            children: ['fwhz'],
            branch: { left: [], right: [] },
            name: ['太和', 'Tai Wo'],
            change_type: 'none',
            num: '10',
            interchange: [[]],
            transfer: { type: 'none', tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
        },
        jce3: {
            parents: ['l116'],
            children: ['7dwu'],
            branch: { left: [], right: [] },
            name: ['粉嶺', 'Fanling'],
            change_type: 'none',
            num: '11',
            interchange: [[]],
            transfer: { type: 'none', tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
        },
        l116: {
            parents: ['m2ot', 'fhq4'],
            children: ['jce3'],
            branch: { left: ['through', 'fhq4'], right: [] },
            name: ['上水', 'Sheung Shui'],
            change_type: 'none',
            num: '12',
            interchange: [[]],
            transfer: { type: 'none', tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
        },
        m2ot: {
            parents: ['linestart'],
            children: ['l116'],
            branch: { left: [], right: [] },
            name: ['羅湖', 'Lo Wu'],
            change_type: 'osi11_ur',
            num: '13',
            interchange: [
                [],
                [
                    ['罗湖', 'Luohu'],
                    ['shenzhen', 'sz1', '#00b140', '#fff', '深圳罗宝线', 'Shenzhen Luobao Line'],
                ],
            ],
            transfer: {
                type: 'osi11',
                tick_direc: 'r',
                paid_area: false,
                osi_names: [['罗湖', 'Luohu']],
                info: [[], [['shenzhen', 'sz1', '#00b140', '#fff', '深圳罗宝线', 'Shenzhen Luobao Line']]],
            },
            services: ['local'],
        },
        fhq4: {
            branch: { left: [], right: [] },
            parents: ['linestart'],
            children: ['l116'],
            name: ['落馬洲', 'Lok Ma Chau'],
            change_type: 'osi11_ur',
            num: '14',
            interchange: [
                [],
                [
                    ['福田口岸', 'Futian Checkpoint'],
                    ['shenzhen', 'sz4', '#da291c', '#fff', '深圳龙华线', 'Shenzhen Longhua Line'],
                ],
            ],
            transfer: {
                type: 'osi11',
                tick_direc: 'r',
                paid_area: false,
                osi_names: [['福田口岸', 'Futian Checkpoint']],
                info: [[], [['shenzhen', 'sz4', '#da291c', '#fff', '深圳龙华线', 'Shenzhen Longhua Line']]],
            },
            services: ['local'],
        },
        hybz: {
            branch: { left: [], right: [] },
            parents: ['rr8a'],
            children: ['u8xj'],
            name: ['馬場', 'Racecourse'],
            change_type: 'none',
            num: '07',
            interchange: [[]],
            transfer: { type: 'none', tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
        },
    },
    line_name: ['東鐵綫', 'East Rail Line'],
    dest_legacy: false,
    char_form: 'trad',
    psd_num: 1,
    line_num: 'ER',
    info_panel_type: 'gz28',
    direction_gz_x: 50,
    direction_gz_y: 70,
};

export default params;
