const params = {
    style: 'mtr',
    svg_height: 300,
    svg_width: 1000,
    svg_dest_width: 1000,
    show_outer: true,
    padding: 17.24,
    y_pc: 40,
    strip_pc: 90,
    branch_spacing: 45,
    theme: ['hongkong', 'sile', '#B6BD00', '#fff'],
    direction: 'l',
    current_stn_idx: 'iwf6',
    platform_num: '6',
    txt_bg_gap: 15,
    txt_flip: false,
    stn_list: {
        linestart: {
            parents: [],
            children: ['aicy'],
            name: ['路綫左端', 'LEFT END'],
            change_type: 'none',
            branch: { left: [], right: [] },
            interchange: [[]],
            transfer: { type: 'none', tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            usage: '',
            facility: '',
        },
        lineend: {
            parents: ['iwf6'],
            children: [],
            name: ['路綫右端', 'RIGHT END'],
            change_type: 'none',
            branch: { left: [], right: [] },
            interchange: [[]],
            transfer: { type: 'none', tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            usage: '',
            facility: '',
        },
        l1mz: {
            parents: ['jgfo'],
            children: ['iwf6'],
            name: ['海洋公園', 'Ocean Park'],
            change_type: 'none',
            branch: { left: [], right: [] },
            num: '02',
            interchange: [[]],
            transfer: { type: 'none', tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            usage: '',
            facility: '',
        },
        iwf6: {
            children: ['lineend'],
            parents: ['l1mz'],
            name: ['金鐘', 'Admiralty'],
            change_type: 'none',
            branch: { left: [], right: [] },
            num: '01',
            interchange: [[]],
            transfer: {
                type: 'int3',
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [
                    [
                        ['hongkong', 'twl', '#E2231A', '#fff', '荃灣綫', 'Tsuen Wan Line'],
                        ['hongkong', 'isl', '#0071CE', '#fff', '港島綫', 'Island Line'],
                    ],
                ],
            },
            services: ['local'],
            usage: '',
            facility: '',
        },
        jgfo: {
            parents: ['l38z'],
            children: ['l1mz'],
            branch: { left: [], right: [] },
            name: ['黃竹坑', 'Wong Chuk Hang'],
            change_type: 'none',
            num: '00',
            interchange: [[]],
            services: ['local'],
            facility: '',
            transfer: { info: [[]], type: 'none', osi_names: [], paid_area: true, tick_direc: 'r' },
        },
        l38z: {
            parents: ['aicy'],
            children: ['jgfo'],
            branch: { left: [], right: [] },
            name: ['利東', 'Lei Tung'],
            change_type: 'none',
            num: '00',
            interchange: [[]],
            services: ['local'],
            facility: '',
            transfer: { info: [[]], type: 'none', osi_names: [], paid_area: true, tick_direc: 'r' },
        },
        aicy: {
            parents: ['linestart'],
            children: ['l38z'],
            branch: { left: [], right: [] },
            name: ['海怡半島', 'South Horizon'],
            change_type: 'none',
            num: '00',
            interchange: [[]],
            services: ['local'],
            facility: '',
            transfer: { info: [[]], type: 'none', osi_names: [], paid_area: true, tick_direc: 'r' },
        },
    },
    line_name: ['南港島綫', 'South Island Line'],
    dest_legacy: false,
    char_form: 'trad',
    psd_num: 1,
    line_num: 'TW',
    info_panel_type: 'gz28',
    direction_gz_x: 50,
    direction_gz_y: 70,
};

export default params;
