export default {
    svg_height: 300,
    svg_width: 1200,
    svg_dest_width: 1000,
    show_outer: true,
    padding: 8.750201061605276,
    y_pc: 40,
    strip_pc: 90,
    branch_spacing: 45,
    theme: ['hongkong', 'wrl', '#B6008D', '#fff'],
    direction: 'l',
    current_stn_idx: 'iwf6',
    platform_num: '3',
    txt_bg_gap: 15,
    txt_flip: true,
    stn_list: {
        linestart: {
            parents: [],
            children: ['1qc9'],
            name: ['路綫左端', 'LEFT END'],
            change_type: 'none',
            branch: { left: [], right: [] },
            interchange: [[]],
            transfer: { type: 'none', tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            usage: '',
            facility: '',
        },
        lineend: {
            parents: ['iwf6'],
            children: [],
            name: ['路綫右端', 'RIGHT END'],
            change_type: 'none',
            branch: { left: [], right: [] },
            interchange: [[]],
            transfer: { type: 'none', tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            usage: '',
            facility: '',
        },
        l1mz: {
            parents: ['72qp'],
            children: ['iwf6'],
            name: ['尖東', 'East Tsim Sha Tsui'],
            change_type: 'none',
            branch: { left: [], right: [] },
            num: '02',
            interchange: [[]],
            transfer: {
                type: 'osi11',
                tick_direc: 'l',
                paid_area: false,
                osi_names: [['尖沙咀', 'Tsim Sha Tsui']],
                info: [[], [['hongkong', 'twl', '#E2231A', '#fff', '荃灣綫', 'Tsuen Wan Line']]],
            },
            services: ['local'],
            usage: '',
            facility: '',
        },
        iwf6: {
            children: ['lineend'],
            parents: ['l1mz'],
            name: ['紅磡', 'Hung Hom'],
            change_type: 'none',
            branch: { left: [], right: [] },
            num: '01',
            interchange: [[]],
            transfer: {
                type: 'int2',
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [[['hongkong', 'eal', '#61B4E4', '#fff', '轉綫', 'Line']]],
            },
            services: ['local'],
            usage: '',
            facility: '',
        },
        '1qc9': {
            name: ['屯門', 'Tuen Mun'],
            num: '00',
            services: ['local'],
            parents: ['linestart'],
            children: ['5qln'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['hongkong', 'lrl', '#CD9700', '#fff', '輕鐵', 'Light Rail']]],
                type: 'int2',
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
            interchange: [[]],
            usage: '',
        },
        '5qln': {
            name: ['兆康', 'Siu Hong'],
            num: '00',
            services: ['local'],
            parents: ['1qc9'],
            children: ['jptn'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['hongkong', 'lrl', '#CD9700', '#fff', '輕鐵', 'Light Rail']]],
                type: 'int2',
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
            interchange: [[]],
            usage: '',
        },
        jptn: {
            name: ['天水圍', 'Tin Shui Wai'],
            num: '00',
            services: ['local'],
            parents: ['5qln'],
            children: ['3d00'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['hongkong', 'lrl', '#CD9700', '#fff', '輕鐵', 'Light Rail']]],
                type: 'int2',
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
            interchange: [[]],
            usage: '',
        },
        '3d00': {
            name: ['朗屏', 'Long Ping'],
            num: '00',
            services: ['local'],
            parents: ['jptn'],
            children: ['oc4n'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], type: 'none', tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
            interchange: [[]],
            usage: '',
        },
        oc4n: {
            name: ['元朗', 'Yuen Long'],
            num: '00',
            services: ['local'],
            parents: ['3d00'],
            children: ['xdys'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['hongkong', 'lrl', '#CD9700', '#fff', '輕鐵', 'Light Rail']]],
                type: 'int2',
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
            interchange: [[]],
            usage: '',
        },
        xdys: {
            name: ['錦上路', 'Kam Sheung Road'],
            num: '00',
            services: ['local'],
            parents: ['oc4n'],
            children: ['n8ec'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], type: 'none', tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
            interchange: [[]],
            usage: '',
        },
        n8ec: {
            name: ['荃灣西', 'Tsuen Wan West'],
            num: '00',
            services: ['local'],
            parents: ['xdys'],
            children: ['h2w0'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], type: 'none', tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
            interchange: [[]],
            usage: '',
        },
        h2w0: {
            name: ['美孚', 'Mei Foo'],
            num: '00',
            services: ['local'],
            parents: ['n8ec'],
            children: ['fsyx'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['hongkong', 'twl', '#E2231A', '#fff', '荃灣綫', 'Tsuen Wan Line']]],
                type: 'int2',
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
            interchange: [[]],
            usage: '',
        },
        fsyx: {
            name: ['南昌', 'Nam Cheong'],
            num: '00',
            services: ['local'],
            parents: ['h2w0'],
            children: ['72qp'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['hongkong', 'tcl', '#F38B00', '#fff', '東涌綫', 'Tung Chung Line']]],
                type: 'int2',
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
            interchange: [[]],
            usage: '',
        },
        '72qp': {
            name: ['柯士甸', 'Austin'],
            num: '00',
            services: ['local'],
            parents: ['fsyx'],
            children: ['l1mz'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[], [['hongkong', 'hsr', '#9D968D', '#fff', '高速鐵路', 'High Speed Rail']]],
                type: 'osi11',
                tick_direc: 'r',
                paid_area: false,
                osi_names: [['香港西九龍', 'Hong Kong\\West Kowloon']],
            },
            facility: '',
            interchange: [[]],
            usage: '',
        },
    },
    line_name: ['西鐵綫', 'West Rail Line'],
    dest_legacy: false,
    char_form: 'trad',
    psd_num: 1,
    line_num: 'TW',
    info_panel_type: 'gz28',
    direction_gz_x: 50,
    direction_gz_y: 70,
};
