const params = {
    style: 'shmetro',
    svg_height: 400,
    padding: 8.75,
    y_pc: 40,
    branch_spacing: 45,
    theme: ['beijing', 'bj11', '#ED796B', '#fff'],
    direction: 'l',
    current_stn_idx: '9o1k',
    platform_num: '2',
    stn_list: {
        linestart: {
            parents: [],
            children: ['6nzc'],
            name: ['路綫右端', 'RIGHT END'],
            branch: { left: [], right: [] },
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            num: '05',
            secondaryName: false,
        },
        lineend: {
            parents: ['97ll'],
            children: [],
            name: ['路綫左端', 'LEFT END'],
            branch: { left: [], right: [] },
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            num: '00',
            secondaryName: false,
        },
        '6tjz': {
            name: ['北辛安', "Beixin'an"],
            secondaryName: false,
            num: '03',
            services: ['local'],
            parents: ['6nzc'],
            children: ['9o1k'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        '6nzc': {
            name: ['新首钢', 'Xinshougang(Shougang Park)'],
            secondaryName: false,
            num: '04',
            services: ['local'],
            parents: ['linestart'],
            children: ['6tjz'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        '97ll': {
            name: ['模式口', 'Moshikou'],
            secondaryName: ['暂缓开通', 'Stay open'],
            num: '01',
            services: [],
            parents: ['9o1k'],
            children: ['lineend'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        '9o1k': {
            name: ['金安桥', "Jin'anqiao"],
            secondaryName: false,
            num: '02',
            services: ['local'],
            parents: ['6tjz'],
            children: ['97ll'],
            branch: { left: [], right: [] },
            transfer: {
                info: [
                    [
                        ['beijing', 'bj6', '#B58500', '#fff', '6号线', 'Line 6'],
                        ['beijing', 's1l', '#A45A2A', '#fff', 'S1线', 'Line S1'],
                    ],
                ],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
    },
    line_name: ['11号线', 'Line 11'],
    psd_num: '1',
    line_num: '11',
    info_panel_type: 'gz28',
    direction_gz_x: 50,
    direction_gz_y: 70,
    customiseMTRDest: { isLegacy: false, terminal: false },
    svgWidth: { destination: 1350, runin: 1300, railmap: 1200, indoor: 1200 },
    notesGZMTR: [],
    namePosMTR: { isStagger: true, isFlip: false },
};

export default params;
