const params = {
    style: 'mtr',
    svg_height: 450,
    padding: 8.750201061605276,
    y_pc: 40,
    branch_spacing: 45,
    theme: ['beijing', 'bj13', '#F4DA40', '#fff'],
    direction: 'r',
    current_stn_idx: 'l1mz',
    platform_num: '2',
    stn_list: {
        linestart: {
            parents: [],
            children: ['l1mz'],
            name: ['路綫左端', 'LEFT END'],
            branch: { left: [], right: [] },
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            num: '00',
            secondaryName: false,
        },
        lineend: {
            parents: ['mq3y'],
            children: [],
            name: ['路綫右端', 'RIGHT END'],
            branch: { left: [], right: [] },
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            num: '18',
            secondaryName: false,
        },
        l1mz: {
            parents: ['linestart'],
            children: ['iwf6'],
            name: ['西直门', 'Xizhi Men'],
            branch: { left: [], right: [] },
            num: '01',
            transfer: {
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [
                    [
                        ['beijing', 'bj2', '#004B87', '#fff', '2号线', 'Line 2'],
                        ['beijing', 'bj4', '#008C95', '#fff', '4号线/大兴线', 'Line 4/DAXING Line'],
                    ],
                ],
            },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        iwf6: {
            children: ['loyz'],
            parents: ['l1mz'],
            name: ['大钟寺', 'Dazhongsi'],
            branch: { left: [], right: [] },
            num: '02',
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        loyz: {
            name: ['知春路', 'Zhichun Lu'],
            secondaryName: false,
            num: '03',
            services: ['local'],
            parents: ['iwf6'],
            children: ['744e'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['beijing', 'bj10', '#0092BC', '#fff', '10号线', 'Line 10']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        '744e': {
            name: ['五道口', 'Wudao Kou'],
            secondaryName: false,
            num: '04',
            services: ['local'],
            parents: ['loyz'],
            children: ['8kka'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        '8kka': {
            name: ['上地', 'Shangdi'],
            secondaryName: false,
            num: '05',
            services: ['local'],
            parents: ['744e'],
            children: ['zs4l'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        zs4l: {
            name: ['清河站', 'Qinghe Railway Station'],
            secondaryName: false,
            num: '06',
            services: ['local'],
            parents: ['8kka'],
            children: ['4iax'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        '4iax': {
            name: ['西二旗', "Xi'erqi"],
            secondaryName: false,
            num: '07',
            services: ['local'],
            parents: ['zs4l'],
            children: ['x6vj'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['beijing', 'cpl', '#D986BA', '#fff', '昌平线', 'Changping Line']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        x6vj: {
            name: ['龙泽', 'Longze'],
            secondaryName: false,
            num: '08',
            services: ['local'],
            parents: ['4iax'],
            children: ['wm6u'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        wm6u: {
            name: ['回龙观', 'Huilong Guan'],
            secondaryName: false,
            num: '09',
            services: ['local'],
            parents: ['x6vj'],
            children: ['06vp'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        '06vp': {
            name: ['霍营', 'Huoying'],
            secondaryName: false,
            num: '10',
            services: ['local'],
            parents: ['wm6u'],
            children: ['0x5x'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['beijing', 'bj8', '#009B77', '#fff', '8号线', 'Line 8']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        '0x5x': {
            name: ['立水桥', 'Lishui Qiao'],
            secondaryName: false,
            num: '11',
            services: ['local'],
            parents: ['06vp'],
            children: ['gaoj'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['beijing', 'bj5', '#AA0061', '#fff', '5号线', 'Line 5']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        gaoj: {
            name: ['北苑', 'Beiyuan'],
            secondaryName: false,
            num: '12',
            services: ['local'],
            parents: ['0x5x'],
            children: ['2xie'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        '2xie': {
            name: ['望京西', 'Wangjing Xi(W)'],
            secondaryName: false,
            num: '13',
            services: ['local'],
            parents: ['gaoj'],
            children: ['9cea'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['beijing', 'bj15', '#653279', '#fff', '15号线', 'Line 15']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        '9cea': {
            name: ['芍药居', 'Shaoyaoju'],
            secondaryName: false,
            num: '14',
            services: ['local'],
            parents: ['2xie'],
            children: ['80n6'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['beijing', 'bj10', '#0092BC', '#fff', '10号线', 'Line 10']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        '80n6': {
            name: ['光熙门', 'Guangxi Men'],
            secondaryName: false,
            num: '15',
            services: ['local'],
            parents: ['9cea'],
            children: ['iqiw'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        iqiw: {
            name: ['柳芳', 'Liufang'],
            secondaryName: false,
            num: '16',
            services: ['local'],
            parents: ['80n6'],
            children: ['mq3y'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        mq3y: {
            name: ['东直门', 'Dongzhi Men'],
            secondaryName: false,
            num: '17',
            services: ['local'],
            parents: ['iqiw'],
            children: ['lineend'],
            branch: { left: [], right: [] },
            transfer: {
                info: [
                    [
                        ['beijing', 'bj2', '#004B87', '#fff', '2号线', 'Line 2'],
                        ['beijing', 'cae', '#A192B2', '#fff', '首都机场线', 'Capital Airport Express'],
                    ],
                ],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
    },
    line_name: ['13号线', 'Line 13'],
    psd_num: '1',
    line_num: '13',
    info_panel_type: 'gz28',
    direction_gz_x: 50,
    direction_gz_y: 70,
    customiseMTRDest: { isLegacy: false, terminal: false },
    svgWidth: { destination: 2000, runin: 2000, railmap: 2000, indoor: 2000 },
    notesGZMTR: [],
    namePosMTR: { isStagger: true, isFlip: false },
};

export default params;
