const params = {
    style: 'shmetro',
    svg_height: 400,
    padding: 8.750201061605276,
    y_pc: 40,
    branch_spacing: 45,
    theme: ['beijing', 'bj14', '#CA9A8E', '#fff'],
    direction: 'r',
    current_stn_idx: 'p5gt',
    platform_num: '2',
    stn_list: {
        linestart: {
            parents: [],
            children: ['p5gt'],
            name: ['路綫左端', 'LEFT END'],
            branch: { left: [], right: [] },
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            num: '00',
            secondaryName: false,
        },
        lineend: {
            parents: ['bvw3'],
            children: [],
            name: ['路綫右端', 'RIGHT END'],
            branch: { left: [], right: [] },
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            num: '35',
            secondaryName: false,
        },
        ygys: {
            name: ['园博园', 'Yuanboyuan(Garden Expo Park)'],
            secondaryName: false,
            num: '02',
            services: ['local'],
            parents: ['p5gt'],
            children: ['44ox'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        p5gt: {
            name: ['张郭庄', 'Zhangguozhuang'],
            secondaryName: false,
            num: '01',
            services: ['local'],
            parents: ['linestart'],
            children: ['ygys'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        po4v: {
            name: ['大井', 'Dajing'],
            secondaryName: false,
            num: '05',
            services: ['local'],
            parents: ['uo2r'],
            children: ['c9bt'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        uo2r: {
            name: ['郭庄子', 'Guozhuangzi'],
            secondaryName: false,
            num: '04',
            services: ['local'],
            parents: ['44ox'],
            children: ['po4v'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        '44ox': {
            name: ['大瓦窑', 'Dawayao'],
            secondaryName: false,
            num: '03',
            services: ['local'],
            parents: ['ygys'],
            children: ['uo2r'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        '63ae': {
            name: ['西局', 'Xiju'],
            secondaryName: false,
            num: '07',
            services: ['local'],
            parents: ['c9bt'],
            children: ['jvc3'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['beijing', 'bj10', '#0092BC', '#fff', '10号线', 'Line 10']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        c9bt: {
            name: ['七里庄', 'Qilizhuang'],
            secondaryName: false,
            num: '06',
            services: ['local'],
            parents: ['po4v'],
            children: ['63ae'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['beijing', 'bj9', '#97D700', '#fff', '9号线', 'Line 9']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        '7dl9': {
            name: ['景风门', 'Jingfengmen'],
            secondaryName: false,
            num: '10',
            services: ['local'],
            parents: ['scy7'],
            children: ['owjf'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        scy7: {
            name: ['丽泽商务区', 'Lize Shangwuqu'],
            secondaryName: false,
            num: '09',
            services: ['local'],
            parents: ['jvc3'],
            children: ['7dl9'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        jvc3: {
            name: ['东管头', 'Dongguantou'],
            secondaryName: false,
            num: '08',
            services: ['local'],
            parents: ['63ae'],
            children: ['scy7'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        ufqf: {
            name: ['永定门外', 'Yongdingmen Wai'],
            secondaryName: false,
            num: '13',
            services: ['local'],
            parents: ['dwlg'],
            children: ['gcwg'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['beijing', 'bj8', '#009B77', '#fff', '8号线', 'Line 8']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        dwlg: {
            name: ['陶然桥', 'Taoranqiao'],
            secondaryName: ['暂缓开通', 'Stay open'],
            num: '12',
            services: [],
            parents: ['owjf'],
            children: ['ufqf'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        owjf: {
            name: ['北京南站', 'Beijingnan Zhan(Beijing South Railway Station)'],
            secondaryName: false,
            num: '11',
            services: ['local'],
            parents: ['7dl9'],
            children: ['dwlg'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['beijing', 'bj4', '#008C95', '#fff', '4号线\\大兴线', 'Line 4\\Daxing Line']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        '2tff': {
            name: ['方庄', 'Fangzhuang'],
            secondaryName: false,
            num: '16',
            services: ['local'],
            parents: ['p6cc'],
            children: ['v0pf'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        p6cc: {
            name: ['蒲黄榆', 'Puhuangyu'],
            secondaryName: false,
            num: '15',
            services: ['local'],
            parents: ['gcwg'],
            children: ['2tff'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['beijing', 'bj5', '#AA0061', '#fff', '5号线', 'Line 5']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        gcwg: {
            name: ['景泰', 'Jingtai'],
            secondaryName: false,
            num: '14',
            services: ['local'],
            parents: ['ufqf'],
            children: ['p6cc'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        '9gn8': {
            name: ['平乐园', 'Pingleyuan'],
            secondaryName: false,
            num: '19',
            services: ['local'],
            parents: ['eep5'],
            children: ['yymr'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        eep5: {
            name: ['北工大西门', 'Beigongda Ximen(Beijing Univ. of Tech. West Gate)'],
            secondaryName: false,
            num: '18',
            services: ['local'],
            parents: ['v0pf'],
            children: ['9gn8'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        v0pf: {
            name: ['十里河', 'Shilihe'],
            secondaryName: false,
            num: '17',
            services: ['local'],
            parents: ['2tff'],
            children: ['eep5'],
            branch: { left: [], right: [] },
            transfer: {
                info: [
                    [
                        ['beijing', 'bj10', '#0092BC', '#fff', '10号线', 'Line 10'],
                        ['beijing', 'bj17', '#00A9A9', '#fff', '17号线', 'Line 17'],
                    ],
                    [],
                    [],
                ],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        s2ol: {
            name: ['朝阳公园', 'Chaoyang Gongyuan(Chaoyang Park)'],
            secondaryName: false,
            num: '24',
            services: ['local'],
            parents: ['efec'],
            children: ['iqvc'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        efec: {
            name: ['金台路', 'Jintai Lu'],
            secondaryName: false,
            num: '23',
            services: ['local'],
            parents: ['1odo'],
            children: ['s2ol'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['beijing', 'bj6', '#B58500', '#fff', '6号线', 'Line 6']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        '1odo': {
            name: ['红庙', 'Hongmiao'],
            secondaryName: ['暂缓开通', 'Stay open'],
            num: '22',
            services: [],
            parents: ['h937'],
            children: ['efec'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        h937: {
            name: ['大望路', 'Dawang Lu'],
            secondaryName: false,
            num: '21',
            services: ['local'],
            parents: ['yymr'],
            children: ['1odo'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['beijing', 'bj1', '#A4343A', '#fff', '1号线\\八通线', 'Line 1\\Batong Line']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        yymr: {
            name: ['九龙山', 'Jiulongshan'],
            secondaryName: false,
            num: '20',
            services: ['local'],
            parents: ['9gn8'],
            children: ['h937'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['beijing', 'bj7', '#FFC56E', '#fff', '7号线', 'Line 7']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        midd: {
            name: ['阜通', 'Futong'],
            secondaryName: false,
            num: '30',
            services: ['local'],
            parents: ['pi8g'],
            children: ['x8eo'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        pi8g: {
            name: ['望京南', 'Wangjingnan'],
            secondaryName: false,
            num: '29',
            services: ['local'],
            parents: ['7ub9'],
            children: ['midd'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        '7ub9': {
            name: ['高家园', 'Gaojia Yuan'],
            secondaryName: ['暂缓开通', 'Stay open'],
            num: '28',
            services: [],
            parents: ['9im3'],
            children: ['pi8g'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        '9im3': {
            name: ['将台', 'Jiangtai'],
            secondaryName: false,
            num: '27',
            services: ['local'],
            parents: ['2pod'],
            children: ['7ub9'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        '2pod': {
            name: ['东风北桥', 'Dongfeng Beiqiao'],
            secondaryName: false,
            num: '26',
            services: ['local'],
            parents: ['iqvc'],
            children: ['9im3'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        iqvc: {
            name: ['枣营', 'Zaoying'],
            secondaryName: false,
            num: '25',
            services: ['local'],
            parents: ['s2ol'],
            children: ['2pod'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        bvw3: {
            name: ['善各庄', "Shan'gezhuang"],
            secondaryName: false,
            num: '34',
            services: ['local'],
            parents: ['3xgl'],
            children: ['lineend'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        '3xgl': {
            name: ['来广营', 'Laiguangying'],
            secondaryName: false,
            num: '33',
            services: ['local'],
            parents: ['8kbz'],
            children: ['bvw3'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        '8kbz': {
            name: ['东湖渠', 'Donghuqu'],
            secondaryName: false,
            num: '32',
            services: ['local'],
            parents: ['x8eo'],
            children: ['3xgl'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        x8eo: {
            name: ['望京', 'Wangjing'],
            secondaryName: false,
            num: '31',
            services: ['local'],
            parents: ['midd'],
            children: ['8kbz'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['beijing', 'bj15', '#653279', '#fff', '15号线', 'Line 15']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
    },
    line_name: ['14号线', 'Line 14'],
    psd_num: '1',
    line_num: '14',
    info_panel_type: 'gz28',
    direction_gz_x: 50,
    direction_gz_y: 70,
    customiseMTRDest: { isLegacy: false, terminal: false },
    svgWidth: { destination: 1350, runin: 1300, railmap: 2200, indoor: 2400 },
    notesGZMTR: [],
    namePosMTR: { isStagger: true, isFlip: false },
};

export default params;
