const param = {
    style: 'shmetro',
    svg_height: 400,
    padding: 8.75,
    y_pc: 40,
    branch_spacing: 45,
    theme: ['beijing', 'bj16', '#6BA539', '#fff'],
    direction: 'l',
    current_stn_idx: 'l1mz',
    platform_num: '2',
    stn_list: {
        linestart: {
            parents: [],
            children: ['iwf6'],
            name: ['路綫右端', 'RIGHT END'],
            branch: { left: [], right: [] },
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            num: '19',
            secondaryName: false,
        },
        lineend: {
            parents: ['l1mz'],
            children: [],
            name: ['路綫左端', 'LEFT END'],
            branch: { left: [], right: [] },
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            num: '00',
            secondaryName: false,
        },
        l1mz: {
            parents: ['xp0m'],
            children: ['lineend'],
            name: ['北安河', "Bei'anhe"],
            branch: { left: [], right: [] },
            num: '01',
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        iwf6: {
            children: ['e6fb'],
            parents: ['linestart'],
            name: ['玉渊潭东门', 'Yuyuantan Dongmen\\(Yuyuantan Park East Gate)'],
            branch: { left: [], right: [] },
            num: '18',
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        e6fb: {
            name: ['甘家口', 'Ganjiakou'],
            secondaryName: false,
            num: '17',
            services: ['local'],
            parents: ['iwf6'],
            children: ['1xnt'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        '1xnt': {
            name: ['二里沟', 'Erligou'],
            secondaryName: ['暂缓开通', 'Stay Open'],
            num: '16',
            services: [],
            parents: ['e6fb'],
            children: ['mny3'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['beijing', 'bj6', '#B58500', '#fff', '6号线', 'Line 6']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        mny3: {
            name: ['国家图书馆', 'Guojia Tushuguan\\(National Library)'],
            secondaryName: false,
            num: '15',
            services: ['local'],
            parents: ['1xnt'],
            children: ['kbfm'],
            branch: { left: [], right: [] },
            transfer: {
                info: [
                    [
                        ['beijing', 'bj4', '#008C95', '#fff', '4号线\\大兴线', 'Line 4\\Daxing Line'],
                        ['beijing', 'bj9', '#97D700', '#fff', '9号线', 'Line 9'],
                    ],
                ],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        eokp: {
            name: ['万泉河桥', 'Wanquanheqiao'],
            secondaryName: false,
            num: '11',
            services: ['local'],
            parents: ['ipio'],
            children: ['b6bz'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        ipio: {
            name: ['苏州街', 'Suzhou Jie'],
            secondaryName: ['暂缓开通', 'Stay open'],
            num: '12',
            services: [],
            parents: ['w81n'],
            children: ['eokp'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['beijing', 'bj10', '#0092BC', '#fff', '10号线', 'Line 10']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        w81n: {
            name: ['苏州桥', 'Suzhouqiao'],
            secondaryName: false,
            num: '13',
            services: ['local'],
            parents: ['kbfm'],
            children: ['ipio'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        kbfm: {
            name: ['万寿寺', 'Wanshousi'],
            secondaryName: false,
            num: '14',
            services: ['local'],
            parents: ['mny3'],
            children: ['w81n'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        b6bz: {
            name: ['西苑', 'Xiyuan'],
            secondaryName: false,
            num: '10',
            services: ['local'],
            parents: ['eokp'],
            children: ['z972'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['beijing', 'bj4', '#008C95', '#fff', '4号线\\大兴线', 'Line 4\\Daxing Line']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        sd27: {
            name: ['永丰南', 'Yongfengnan'],
            secondaryName: false,
            num: '06',
            services: ['local'],
            parents: ['1jvu'],
            children: ['peit'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        '1jvu': {
            name: ['西北旺', 'Xibeiwang'],
            secondaryName: false,
            num: '07',
            services: ['local'],
            parents: ['s5i1'],
            children: ['sd27'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        s5i1: {
            name: ['马连洼', 'Malianwa'],
            secondaryName: false,
            num: '08',
            services: ['local'],
            parents: ['z972'],
            children: ['1jvu'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        z972: {
            name: ['农大南路', 'Nongda Nanlu'],
            secondaryName: false,
            num: '09',
            services: ['local'],
            parents: ['b6bz'],
            children: ['s5i1'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        xp0m: {
            name: ['温阳路', 'Wenyang Lu'],
            secondaryName: false,
            num: '02',
            services: ['local'],
            parents: ['i0db'],
            children: ['l1mz'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        i0db: {
            name: ['稻香湖路', 'Daoxianghu Lu'],
            secondaryName: false,
            num: '03',
            services: ['local'],
            parents: ['1k0c'],
            children: ['xp0m'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        '1k0c': {
            name: ['屯佃', 'Tundian'],
            secondaryName: false,
            num: '04',
            services: ['local'],
            parents: ['peit'],
            children: ['i0db'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        peit: {
            name: ['永丰', 'Yongfeng'],
            secondaryName: false,
            num: '05',
            services: ['local'],
            parents: ['sd27'],
            children: ['1k0c'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
    },
    line_name: ['16号线', 'Line 16'],
    psd_num: '1',
    line_num: '16',
    info_panel_type: 'gz28',
    direction_gz_x: 50,
    direction_gz_y: 70,
    customiseMTRDest: { isLegacy: false, terminal: false },
    svgWidth: { destination: 1500, runin: 1200, railmap: 1750, indoor: 1500 },
    notesGZMTR: [],
    namePosMTR: { isStagger: true, isFlip: false },
};

export default param;
