const param = {
    style: 'shmetro',
    svg_height: 400,
    padding: 8.4,
    y_pc: 40,
    branch_spacing: 45,
    theme: ['beijing', 'bj17', '#00A9A9', '#fff'],
    direction: 'l',
    current_stn_idx: 'iwf6',
    platform_num: '2',
    stn_list: {
        linestart: {
            parents: [],
            children: ['lp11'],
            name: ['路綫左端', 'LEFT END'],
            branch: { left: [], right: [] },
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            num: '00',
            secondaryName: false,
        },
        lineend: {
            parents: ['iwf6'],
            children: [],
            name: ['路綫右端', 'RIGHT END'],
            branch: { left: [], right: [] },
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            num: '08',
            secondaryName: false,
        },
        l1mz: {
            parents: ['bvcx'],
            children: ['iwf6'],
            name: ['次渠', 'Ciqu'],
            branch: { left: [], right: [] },
            num: '20',
            transfer: {
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [[['beijing', 'yzl', '#D0006F', '#fff', '亦庄线', 'Yizhuang Line']]],
            },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        iwf6: {
            children: ['lineend'],
            parents: ['l1mz'],
            name: ['嘉会湖', 'Jiahuihu'],
            branch: { left: [], right: [] },
            num: '21',
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        lp11: {
            name: ['十里河', 'Shilihe'],
            secondaryName: false,
            num: '15',
            services: ['local'],
            parents: ['linestart'],
            children: ['5czs'],
            branch: { left: [], right: [] },
            transfer: {
                info: [
                    [
                        ['beijing', 'bj10', '#0092BC', '#fff', '10号线', 'Line 10'],
                        ['beijing', 'bj14', '#CA9A8E', '#fff', '14号线', 'Line 14'],
                    ],
                ],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        '5czs': {
            name: ['周家庄', 'Zhoujiazhuang'],
            secondaryName: false,
            num: '16',
            services: ['local'],
            parents: ['lp11'],
            children: ['33aw'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        '33aw': {
            name: ['十八里店', 'Shibalidian'],
            secondaryName: false,
            num: '17',
            services: ['local'],
            parents: ['5czs'],
            children: ['3qxj'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        '3qxj': {
            name: ['北神树', 'Beishenshu'],
            secondaryName: false,
            num: '18',
            services: ['local'],
            parents: ['33aw'],
            children: ['bvcx'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        bvcx: {
            name: ['次渠北', 'Ciqubei'],
            secondaryName: false,
            num: '19',
            services: ['local'],
            parents: ['3qxj'],
            children: ['l1mz'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
    },
    line_name: ['17号线', 'Line 17'],
    psd_num: '1',
    line_num: '17',
    info_panel_type: 'gz28',
    direction_gz_x: 50,
    direction_gz_y: 70,
    customiseMTRDest: { isLegacy: false, terminal: false },
    svgWidth: { destination: 1350, runin: 1200, railmap: 1350, indoor: 1350 },
    notesGZMTR: [],
    namePosMTR: { isStagger: true, isFlip: false },
};

export default param;
