const params = {
    style: 'shmetro',
    svg_height: 500,
    padding: 8.75,
    y_pc: 40,
    branch_spacing: 45,
    theme: ['beijing', 'bj2', '#004B87', '#fff'],
    direction: 'r',
    current_stn_idx: 'iwf6',
    platform_num: false,
    stn_list: {
        linestart: {
            parents: [],
            children: ['l1mz'],
            name: ['路綫左端', 'LEFT END'],
            branch: { left: [], right: [] },
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            num: '00',
            secondaryName: false,
            loop_pivot: false,
        },
        lineend: {
            parents: ['wcjm'],
            children: [],
            name: ['路綫右端', 'RIGHT END'],
            branch: { left: [], right: [] },
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            num: '00',
            secondaryName: false,
            loop_pivot: false,
        },
        l1mz: {
            parents: ['linestart'],
            children: ['fdwp'],
            name: ['积水潭', 'Jishuitαn'],
            branch: { left: [], right: [] },
            num: '02',
            transfer: {
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [[['beijing', 'bj19', '#D6ABC1', '#fff', '19号线', 'Line 19']]],
            },
            services: ['local'],
            facility: '',
            secondaryName: false,
            loop_pivot: false,
        },
        iwf6: {
            children: ['8lip'],
            parents: ['lt41'],
            name: ['朝阳门', 'Chαoyαngmen'],
            branch: { left: [], right: [] },
            num: '01',
            transfer: {
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [[['beijing', 'bj6', '#B58500', '#fff', '6号线', 'Line 6']]],
            },
            services: ['local'],
            facility: '',
            secondaryName: false,
            loop_pivot: false,
        },
        fdwp: {
            name: ['鼓楼大街', 'Gulou Dαjie'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['l1mz'],
            children: ['etp0'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['beijing', 'bj8', '#009B77', '#fff', '8号线', 'Line 8']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
            loop_pivot: false,
        },
        etp0: {
            name: ['安定门', 'Andingmen'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['fdwp'],
            children: ['56xk'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
            loop_pivot: false,
        },
        '56xk': {
            name: ['雍和宫', 'Yonghegong\\(Lama Temple)'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['etp0'],
            children: ['768x'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['beijing', 'bj5', '#AA0061', '#fff', '5号线', 'Line 5']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
            loop_pivot: false,
        },
        '768x': {
            name: ['东直门', 'Dongzhimen'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['56xk'],
            children: ['lt41'],
            branch: { left: [], right: [] },
            transfer: {
                info: [
                    [
                        ['beijing', 'bj13', '#F4DA40', '#fff', '13号线', 'Line 13'],
                        ['beijing', 'cae', '#A192B2', '#fff', '首都机场线', 'Captial Airport Express'],
                    ],
                    [],
                ],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
            loop_pivot: false,
        },
        lt41: {
            name: ['东四十条', 'Dongsi Shitiαo'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['768x'],
            children: ['iwf6'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
            loop_pivot: false,
        },
        '8lip': {
            name: ['建国门', 'Jiαnguomen'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['iwf6'],
            children: ['9zfq'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['beijing', 'bj1', '#A4343A', '#fff', '1号线/八通线', 'Line 1/Batong Line']], []],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
            loop_pivot: false,
        },
        '9zfq': {
            name: ['北京站', 'Beijing Zhαn\\(Beijing Railway Station)'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['8lip'],
            children: ['norf'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
            loop_pivot: false,
        },
        norf: {
            name: ['崇文门', 'Chongwenmen'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['9zfq'],
            children: ['1od5'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['beijing', 'bj5', '#AA0061', '#fff', '5号线', 'Line 5']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
            loop_pivot: false,
        },
        '1od5': {
            name: ['前门', 'Qiαnmen'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['norf'],
            children: ['na0v'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['beijing', 'bj8', '#009B77', '#fff', '8号线', 'Line 8']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
            loop_pivot: false,
        },
        na0v: {
            name: ['和平门', 'Hepingmen'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['1od5'],
            children: ['ifws'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
            loop_pivot: false,
        },
        ifws: {
            name: ['宣武门', 'Xuαnwumen'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['na0v'],
            children: ['vcga'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['beijing', 'bj4', '#008C95', '#fff', '4号线/大兴线', 'Line 4/Daxing Line']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
            loop_pivot: false,
        },
        vcga: {
            name: ['长椿街', 'Chαngchun Jie'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['ifws'],
            children: ['y27r'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
            loop_pivot: false,
        },
        y27r: {
            name: ['复兴门', 'Fuxingmen'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['vcga'],
            children: ['d41s'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['beijing', 'bj1', '#A4343A', '#fff', '1号线/八通线', 'Line 1/Batong Line']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
            loop_pivot: false,
        },
        d41s: {
            name: ['阜成门', 'Fuchengmen'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['y27r'],
            children: ['8p8j'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
            loop_pivot: false,
        },
        '8p8j': {
            name: ['车公庄', 'Chegongzhuαng'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['d41s'],
            children: ['wcjm'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['beijing', 'bj6', '#B58500', '#fff', '6号线', 'Line 6']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
            loop_pivot: false,
        },
        wcjm: {
            name: ['西直门', 'Xizhimen'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['8p8j'],
            children: ['lineend'],
            branch: { left: [], right: [] },
            transfer: {
                info: [
                    [
                        ['beijing', 'bj4', '#008C95', '#fff', '4号线/大兴线', 'Line 4/Daxing Line'],
                        ['beijing', 'bj13', '#F4DA40', '#fff', '13号线', 'Line 13'],
                    ],
                ],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
            loop_pivot: false,
        },
    },
    line_name: ['2号线', 'Line 2'],
    psd_num: '1',
    line_num: 'TW',
    info_panel_type: 'sh',
    direction_gz_x: 50,
    direction_gz_y: 70,
    customiseMTRDest: { isLegacy: false, terminal: false },
    svgWidth: { destination: 2000, runin: 2000, railmap: 2000, indoor: 2000 },
    notesGZMTR: [],
    namePosMTR: { isStagger: true, isFlip: false },
    coline: [],
    loop: true,
    loop_info: { bank: true, left_and_right_factor: 1, bottom_factor: 8 },
};

export default params;
