const params = {
    svg_height: 450,
    padding: 8.750201061605276,
    y_pc: 40,
    branch_spacing: 45,
    theme: ['beijing', 'bj2', '#004B87', '#fff'],
    direction: 'r',
    current_stn_idx: 'l1mz',
    platform_num: '2',
    stn_list: {
        linestart: {
            parents: [],
            children: ['l1mz'],
            name: ['路綫左端', 'LEFT END'],
            branch: { left: [], right: [] },
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            num: '00',
            secondaryName: false,
        },
        lineend: {
            parents: ['gg5e'],
            children: [],
            name: ['路綫右端', 'RIGHT END'],
            branch: { left: [], right: [] },
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            num: '00',
            secondaryName: false,
        },
        l1mz: {
            parents: ['linestart'],
            children: ['iwf6'],
            name: ['复兴门', 'Fuxing Men'],
            branch: { left: [], right: [] },
            num: '02',
            transfer: {
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [[['beijing', 'bj1', '#A4343A', '#fff', '1号线', 'Line 1']]],
            },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        iwf6: {
            children: ['3wgv'],
            parents: ['l1mz'],
            name: ['长椿街', 'Changchun Jie'],
            branch: { left: [], right: [] },
            num: '01',
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        '3wgv': {
            name: ['宣武门', 'Xuanwu Men'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['iwf6'],
            children: ['3ivt'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['beijing', 'bj4', '#008C95', '#fff', '4号线/大兴线', 'Line 4/DAXING Line']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        '3ivt': {
            name: ['和平门', 'Heping Men'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['3wgv'],
            children: ['zcf8'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        zcf8: {
            name: ['前门', 'Qian Men'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['3ivt'],
            children: ['szln'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        szln: {
            name: ['崇文门', 'Chongwen Men'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['zcf8'],
            children: ['dtx1'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['beijing', 'bj5', '#AA0061', '#fff', '5号线', 'Line 5']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        dtx1: {
            name: ['北京站', 'Beijing Railway Station'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['szln'],
            children: ['b5s8'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        b5s8: {
            name: ['建国门', 'Jianguo Men'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['dtx1'],
            children: ['ezt5'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['beijing', 'bj1', '#A4343A', '#fff', '1号线', 'Line 1']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        ezt5: {
            name: ['朝阳门', 'Chaoyang Men'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['b5s8'],
            children: ['gghr'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['beijing', 'bj6', '#B58500', '#fff', '6号线', 'Line 6']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        gghr: {
            name: ['东四十条', 'Dongsi Shitiao'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['ezt5'],
            children: ['7x2u'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        '7x2u': {
            name: ['东直门', 'Dongzhi Men'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['gghr'],
            children: ['0ez5'],
            branch: { left: [], right: [] },
            transfer: {
                info: [
                    [
                        ['beijing', 'bj13', '#F4DA40', '#fff', '13号线', 'Line 13'],
                        ['beijing', 'cae', '#A192B2', '#fff', '首都机场线', 'Capital Airport Express'],
                    ],
                ],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        '0ez5': {
            name: ['雍和宫', 'Yonghegong\\Lama Temple'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['7x2u'],
            children: ['ucuf'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['beijing', 'bj5', '#AA0061', '#fff', '5号线', 'Line 5']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        ucuf: {
            name: ['安定门', 'Anding Men'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['0ez5'],
            children: ['2dbh'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        '2dbh': {
            name: ['鼓楼大街', 'Gulou Dajie'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['ucuf'],
            children: ['m0pa'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['beijing', 'bj8', '#009B77', '#fff', '8号线', 'Line 8']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        m0pa: {
            name: ['积水潭', 'Jishuitan'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['2dbh'],
            children: ['9pwk'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        '9pwk': {
            name: ['西直门', 'Xizhi Men'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['m0pa'],
            children: ['mgqd'],
            branch: { left: [], right: [] },
            transfer: {
                info: [
                    [
                        ['beijing', 'bj4', '#008C95', '#fff', '4号线', 'Line 4'],
                        ['beijing', 'bj13', '#F4DA40', '#fff', '13号线', 'Line 13'],
                    ],
                ],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        mgqd: {
            name: ['车公庄', 'Chegongzhuang'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['9pwk'],
            children: ['uz34'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['beijing', 'bj6', '#B58500', '#fff', '6号线', 'Line 6']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        uz34: {
            name: ['阜成门', 'Fucheng Men'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['mgqd'],
            children: ['gg5e'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        gg5e: {
            name: ['复兴门', 'Fuxing Men'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['uz34'],
            children: ['lineend'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['beijing', 'bj1', '#A4343A', '#fff', '1号线', 'Line 1']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
    },
    line_name: ['2号线', 'Line 2'],
    psd_num: '1',
    line_num: 'TW',
    info_panel_type: 'gz28',
    direction_gz_x: 50,
    direction_gz_y: 70,
    customiseMTRDest: { isLegacy: false, terminal: false },
    svgWidth: { destination: 2000, runin: 2000, railmap: 2000, indoor: 2750 },
    notesGZMTR: [],
    namePosMTR: { isStagger: true, isFlip: false },
};

export default params;
