const params = {
    style: 'mtr',
    svg_height: 450,
    padding: 8.750201061605276,
    y_pc: 40,
    branch_spacing: 45,
    theme: ['beijing', 'bj4', '#008C95', '#fff'],
    direction: 'r',
    current_stn_idx: 'l1mz',
    platform_num: '2',
    stn_list: {
        linestart: {
            parents: [],
            children: ['l1mz'],
            name: ['路綫左端', 'LEFT END'],
            branch: { left: [], right: [] },
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            num: '00',
            secondaryName: false,
        },
        lineend: {
            parents: ['vopg'],
            children: [],
            name: ['路綫右端', 'RIGHT END'],
            branch: { left: [], right: [] },
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            num: '36',
            secondaryName: false,
        },
        l1mz: {
            parents: ['linestart'],
            children: ['iwf6'],
            name: ['安河桥北', 'Anheqiao Bei(N)'],
            branch: { left: [], right: [] },
            num: '01',
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        iwf6: {
            children: ['3uhl'],
            parents: ['l1mz'],
            name: ['北宫门', 'Beigongmen'],
            branch: { left: [], right: [] },
            num: '02',
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        '3uhl': {
            name: ['西苑', 'Xi Yuan'],
            secondaryName: false,
            num: '03',
            services: ['local'],
            parents: ['iwf6'],
            children: ['w5cl'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['beijing', 'bj16', '#6BA539', '#fff', '16号线', 'Line 16']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        w5cl: {
            name: ['圆明园', 'Yuanmingyuan Park'],
            secondaryName: false,
            num: '04',
            services: ['local'],
            parents: ['3uhl'],
            children: ['gzcj'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        gzcj: {
            name: ['北京大学东门', 'Peking University East Gate'],
            secondaryName: false,
            num: '05',
            services: ['local'],
            parents: ['w5cl'],
            children: ['xqeo'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        xqeo: {
            name: ['中关村', 'Zhongguancun'],
            secondaryName: false,
            num: '06',
            services: ['local'],
            parents: ['gzcj'],
            children: ['2dys'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        '2dys': {
            name: ['海淀黄庄', 'Haidian Huangzhuang'],
            secondaryName: false,
            num: '07',
            services: ['local'],
            parents: ['xqeo'],
            children: ['i2dc'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['beijing', 'bj10', '#0092BC', '#fff', '10号线', 'Line 10']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        i2dc: {
            name: ['人民大学', 'Renmin University'],
            secondaryName: false,
            num: '08',
            services: ['local'],
            parents: ['2dys'],
            children: ['9kus'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        '9kus': {
            name: ['魏公村', 'Weigongcun'],
            secondaryName: false,
            num: '09',
            services: ['local'],
            parents: ['i2dc'],
            children: ['y7zy'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        y7zy: {
            name: ['国家图书馆', 'National Library'],
            secondaryName: false,
            num: '10',
            services: ['local'],
            parents: ['9kus'],
            children: ['svr4'],
            branch: { left: [], right: [] },
            transfer: {
                info: [
                    [
                        ['beijing', 'bj9', '#97D700', '#fff', '9号线', 'Line 9'],
                        ['beijing', 'bj16', '#6BA539', '#fff', '16号线', 'Line 16'],
                    ],
                ],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        svr4: {
            name: ['动物园', 'Beijing Zoo'],
            secondaryName: false,
            num: '11',
            services: ['local'],
            parents: ['y7zy'],
            children: ['1zgd'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        '1zgd': {
            name: ['西直门', 'Xizhi Men'],
            secondaryName: false,
            num: '12',
            services: ['local'],
            parents: ['svr4'],
            children: ['egmd'],
            branch: { left: [], right: [] },
            transfer: {
                info: [
                    [
                        ['beijing', 'bj2', '#004B87', '#fff', '2号线', 'Line 2'],
                        ['beijing', 'bj13', '#F4DA40', '#fff', '13号线', 'Line 13'],
                    ],
                ],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        egmd: {
            name: ['新街口', 'Xinjiekou'],
            secondaryName: false,
            num: '13',
            services: ['local'],
            parents: ['1zgd'],
            children: ['s3bu'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        s3bu: {
            name: ['平安里', "Ping'an Li"],
            secondaryName: false,
            num: '14',
            services: ['local'],
            parents: ['egmd'],
            children: ['1ack'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['beijing', 'bj6', '#B58500', '#fff', '6号线', 'Line 6']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        '5ncb': {
            name: ['灵境胡同', 'Lingjing Hutong'],
            secondaryName: false,
            num: '16',
            services: ['local'],
            parents: ['1ack'],
            children: ['xjjl'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        xjjl: {
            name: ['西单', 'Xidan'],
            secondaryName: false,
            num: '17',
            services: ['local'],
            parents: ['5ncb'],
            children: ['pxth'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['beijing', 'bj1', '#A4343A', '#fff', '1号线', 'Line 1']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        pxth: {
            name: ['宣武门', 'Xuanwu Men'],
            secondaryName: false,
            num: '18',
            services: ['local'],
            parents: ['xjjl'],
            children: ['at7o'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['beijing', 'bj2', '#004B87', '#fff', '2号线', 'Line 2']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        at7o: {
            name: ['菜市口', 'Caishi Kou'],
            secondaryName: false,
            num: '19',
            services: ['local'],
            parents: ['pxth'],
            children: ['p9ba'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['beijing', 'bj7', '#FFC56E', '#fff', '7号线', 'Line 7']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        p9ba: {
            name: ['陶然亭', 'Taoranting'],
            secondaryName: false,
            num: '20',
            services: ['local'],
            parents: ['at7o'],
            children: ['utpj'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        utpj: {
            name: ['北京南站', 'Beijing South Railway Station'],
            secondaryName: false,
            num: '21',
            services: ['local'],
            parents: ['p9ba'],
            children: ['hvue'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['beijing', 'bj14', '#CA9A8E', '#fff', '14号线', ' Line 14']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        hvue: {
            name: ['马家堡', 'Majiapu'],
            secondaryName: false,
            num: '22',
            services: ['local'],
            parents: ['utpj'],
            children: ['dq01'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        dq01: {
            name: ['角门西', 'Jiaomen Xi(W)'],
            secondaryName: false,
            num: '23',
            services: ['local'],
            parents: ['hvue'],
            children: ['dafe'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['beijing', 'bj10', '#0092BC', '#fff', '10号线', 'Line 10']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        dafe: {
            name: ['公益西桥', 'Gongyi Xiqiao'],
            secondaryName: false,
            num: '24',
            services: ['local'],
            parents: ['dq01'],
            children: ['7qwm'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        '7qwm': {
            name: ['新宫', 'Xin Gong'],
            secondaryName: false,
            num: '25',
            services: ['local'],
            parents: ['dafe'],
            children: ['8ize'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        '8ize': {
            name: ['西红门', 'Xihong Men'],
            secondaryName: false,
            num: '26',
            services: ['local'],
            parents: ['7qwm'],
            children: ['94pa'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        '94pa': {
            name: ['高米店北', 'Gaomidian Bei(N)'],
            secondaryName: false,
            num: '27',
            services: ['local'],
            parents: ['8ize'],
            children: ['r4gt'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        hzmd: {
            name: ['枣园', 'Zaoyuan'],
            secondaryName: false,
            num: '29',
            services: ['local'],
            parents: ['r4gt'],
            children: ['5sf1'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        '5sf1': {
            name: ['清源路', 'Qingyuan Lu'],
            secondaryName: false,
            num: '30',
            services: ['local'],
            parents: ['hzmd'],
            children: ['4fup'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        '4fup': {
            name: ['黄村西大街', 'Huangcun Xidajie'],
            secondaryName: false,
            num: '31',
            services: ['local'],
            parents: ['5sf1'],
            children: ['pcok'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        pcok: {
            name: ['黄村火车站', 'Huangcun Railway Station'],
            secondaryName: false,
            num: '32',
            services: ['local'],
            parents: ['4fup'],
            children: ['uc7e'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        uc7e: {
            name: ['义和庄', 'Yihezhuang'],
            secondaryName: false,
            num: '33',
            services: ['local'],
            parents: ['pcok'],
            children: ['neqs'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        neqs: {
            name: ['生物医药基地', 'Biomedical Base'],
            secondaryName: false,
            num: '34',
            services: ['local'],
            parents: ['uc7e'],
            children: ['vopg'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        vopg: {
            name: ['天宫院', 'Tiangong Yuan'],
            secondaryName: false,
            num: '35',
            services: ['local'],
            parents: ['neqs'],
            children: ['lineend'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        '1ack': {
            name: ['西四', 'Xisi'],
            secondaryName: false,
            num: '15',
            services: ['local'],
            parents: ['s3bu'],
            children: ['5ncb'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        r4gt: {
            name: ['高米店南', 'Gaomidian Nan(S)'],
            secondaryName: false,
            num: '28',
            services: ['local'],
            parents: ['94pa'],
            children: ['hzmd'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
    },
    line_name: ['4号线/大兴线', 'Line 4/DAXING Line'],
    psd_num: '1',
    line_num: '4',
    info_panel_type: 'gz28',
    direction_gz_x: 50,
    direction_gz_y: 70,
    customiseMTRDest: { isLegacy: false, terminal: false },
    svgWidth: { destination: 2000, runin: 2000, railmap: 2500, indoor: 2500 },
    notesGZMTR: [],
    namePosMTR: { isStagger: true, isFlip: false },
};

export default params;
