const params = {
    style: 'mtr',
    svg_height: 450,
    padding: 8.750201061605276,
    y_pc: 40,
    branch_spacing: 45,
    theme: ['beijing', 'bj6', '#B58500', '#fff'],
    direction: 'r',
    current_stn_idx: 'l1mz',
    platform_num: '2',
    stn_list: {
        linestart: {
            parents: [],
            children: ['l1mz'],
            name: ['路綫左端', 'LEFT END'],
            branch: { left: [], right: [] },
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            num: '00',
            secondaryName: false,
        },
        lineend: {
            parents: ['gua0'],
            children: [],
            name: ['路綫右端', 'RIGHT END'],
            branch: { left: [], right: [] },
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            num: '00',
            secondaryName: false,
        },
        l1mz: {
            parents: ['linestart'],
            children: ['iwf6'],
            name: ['金安桥', "Jin'an Qiao"],
            branch: { left: [], right: [] },
            num: '02',
            transfer: {
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [[['beijing', 's1l', '#A45A2A', '#fff', 'S1线', 'Line S1']]],
            },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        iwf6: {
            children: ['dx9v'],
            parents: ['l1mz'],
            name: ['苹果园', 'Pingguo Yuan'],
            branch: { left: [], right: [] },
            num: '01',
            transfer: {
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [
                    [
                        ['beijing', 'bj1', '#A4343A', '#fff', '1号线', 'Line 1'],
                        ['beijing', 's1l', '#A45A2A', '#fff', 'S1线', 'Line S1'],
                    ],
                ],
            },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        dx9v: {
            name: ['杨庄', 'Yangzhuang'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['iwf6'],
            children: ['507q'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        '507q': {
            name: ['西黄村', 'Xihuangcun'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['dx9v'],
            children: ['wj16'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        wj16: {
            name: ['廖公庄', 'Liaogongzhuang'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['507q'],
            children: ['639e'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        '639e': {
            name: ['田村', 'Tiancun'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['wj16'],
            children: ['lej6'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        lej6: {
            name: ['海淀五路居', 'Haidian Wuluju'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['639e'],
            children: ['4c8t'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['beijing', 'bj10', '#0092BC', '#fff', '10号线', 'Line 10']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        '4c8t': {
            name: ['花园桥', 'Huayuan Qiao'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['lej6'],
            children: ['9pyo'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        '9pyo': {
            name: ['白石桥南', 'Baishiqiao Nan(S)'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['4c8t'],
            children: ['r5kv'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['beijing', 'bj9', '#97D700', '#fff', '9号线', 'Line 9']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        r5kv: {
            name: ['车公庄西', 'Chegongzhuang Xi(W)'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['9pyo'],
            children: ['uxm9'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        uxm9: {
            name: ['车公庄', 'Chegongzhuang'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['r5kv'],
            children: ['e9rp'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['beijing', 'bj2', '#004B87', '#fff', '2号线', 'Line 2']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        e9rp: {
            name: ['平安里', "Ping'an Li"],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['uxm9'],
            children: ['rtfa'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['beijing', 'bj4', '#008C95', '#fff', '4号线/大兴线', 'Line 4/DAXING Line']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        rtfa: {
            name: ['北海北', 'Beihai Bei(N)'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['e9rp'],
            children: ['nu0i'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        nu0i: {
            name: ['南锣鼓巷', 'Nanluogu Xiang'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['rtfa'],
            children: ['amk0'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['beijing', 'bj8', '#009B77', '#fff', '8号线', 'Line 8']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        amk0: {
            name: ['东四', 'Dongsi'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['nu0i'],
            children: ['xzla'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['beijing', 'bj5', '#AA0061', '#fff', '5号线', 'Line 5']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        xzla: {
            name: ['朝阳门', 'Chaoyang Men'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['amk0'],
            children: ['p0k4'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['beijing', 'bj2', '#004B87', '#fff', '2号线', 'Line 2']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        p0k4: {
            name: ['东大桥', 'Dongdaqiao'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['xzla'],
            children: ['0st5'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        '0st5': {
            name: ['呼家楼', 'Hujialou'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['p0k4'],
            children: ['mx71'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['beijing', 'bj10', '#0092BC', '#fff', '10号线', 'Line 10']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        mx71: {
            name: ['金台路', 'Jintai Lu'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['0st5'],
            children: ['0uia'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['beijing', 'bj14', '#CA9A8E', '#fff', '14号线', 'Line 14']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        '0uia': {
            name: ['十里堡', 'Shilipu'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['mx71'],
            children: ['d30g'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        xhx5: {
            name: ['褡裢坡', 'Dalianpo'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['d30g'],
            children: ['kzwq'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        kzwq: {
            name: ['黄渠', 'Huangqu'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['xhx5'],
            children: ['4qke'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        d30g: {
            name: ['青年路', 'Qingnian Lu'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['0uia'],
            children: ['xhx5'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        '4qke': {
            name: ['常营', 'Changying'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['kzwq'],
            children: ['ui4w'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        ui4w: {
            name: ['草房', 'Caofang'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['4qke'],
            children: ['exjz'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        exjz: {
            name: ['物资学院路', 'Wuzi Xueyuan Lu'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['ui4w'],
            children: ['g6am'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        g6am: {
            name: ['通州北关', 'Tongzhou Beiguan'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['exjz'],
            children: ['qpv2'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        qpv2: {
            name: ['通运门', 'Tongyun Men'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['g6am'],
            children: ['mtpj'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        mtpj: {
            name: ['北运河西', 'Beiyunhe Xi(W)'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['qpv2'],
            children: ['xh2v'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        xh2v: {
            name: ['北运河东', 'Beiyunhe Dong(E)'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['mtpj'],
            children: ['kwag'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        kwag: {
            name: ['郝家府', 'Haojia Fu'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['xh2v'],
            children: ['kgas'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        kgas: {
            name: ['东夏园', 'Dongxia Yuan'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['kwag'],
            children: ['gua0'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        gua0: {
            name: ['潞城', 'Lucheng'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['kgas'],
            children: ['lineend'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
    },
    line_name: ['6号线', 'Line 6'],
    psd_num: '1',
    line_num: 'TW',
    info_panel_type: 'gz28',
    direction_gz_x: 50,
    direction_gz_y: 70,
    customiseMTRDest: { isLegacy: false, terminal: false },
    svgWidth: { destination: 2000, runin: 2000, railmap: 3000, indoor: 3000 },
    notesGZMTR: [],
    namePosMTR: { isStagger: true, isFlip: false },
};

export default params;
