const params = {
    style: 'shmetro',
    svg_height: 400,
    padding: 5.43,
    y_pc: 40,
    branch_spacing: 45,
    theme: ['beijing', 'bj8', '#009B77', '#fff'],
    direction: 'r',
    current_stn_idx: 'kyj2',
    platform_num: '2',
    stn_list: {
        linestart: {
            parents: [],
            children: ['u5d5'],
            name: ['路綫左端', 'LEFT END'],
            branch: { left: [], right: [] },
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            num: '00',
            secondaryName: false,
        },
        lineend: {
            parents: ['8i85'],
            children: [],
            name: ['路綫右端', 'RIGHT END'],
            branch: { left: [], right: [] },
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            num: '36',
            secondaryName: false,
        },
        u5d5: {
            name: ['朱辛庄', 'Zhuxinzhuang'],
            secondaryName: false,
            num: '01',
            services: ['local'],
            parents: ['linestart'],
            children: ['sidd'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        sidd: {
            name: ['育知路', 'Yuzhi Lu'],
            secondaryName: false,
            num: '02',
            services: ['local'],
            parents: ['u5d5'],
            children: ['23pa'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        '23pa': {
            name: ['平西府', 'Pingxifu'],
            secondaryName: false,
            num: '03',
            services: ['local'],
            parents: ['sidd'],
            children: ['gibi'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        gibi: {
            name: ['回龙观东大街', 'Huilongguan Dongdajie'],
            secondaryName: false,
            num: '04',
            services: ['local'],
            parents: ['23pa'],
            children: ['9qpq'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        '4qvx': {
            name: ['永泰庄', 'Yongtaizhuang'],
            secondaryName: false,
            num: '08',
            services: ['local'],
            parents: ['kzl8'],
            children: ['ark0'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        kzl8: {
            name: ['西小口', 'Xixiaokou'],
            secondaryName: false,
            num: '07',
            services: ['local'],
            parents: ['bqnh'],
            children: ['4qvx'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        bqnh: {
            name: ['育新', 'Yuxin'],
            secondaryName: false,
            num: '06',
            services: ['local'],
            parents: ['9qpq'],
            children: ['kzl8'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        '9qpq': {
            name: ['霍营', 'Huoying'],
            secondaryName: false,
            num: '05',
            services: ['local'],
            parents: ['gibi'],
            children: ['bqnh'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['beijing', 'bj13', '#F4DA40', '#fff', '13号线', 'Line 13']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        '1lub': {
            name: ['森林公园南门', 'Senlin Gongyuan Nanmen\\(Forest Park South Gate)'],
            secondaryName: false,
            num: '10',
            services: ['local'],
            parents: ['ark0'],
            children: ['b8e9'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        ark0: {
            name: ['林萃桥', 'Lincuiqiao'],
            secondaryName: false,
            num: '09',
            services: ['local'],
            parents: ['4qvx'],
            children: ['1lub'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        b8e9: {
            name: ['奥林匹克公园', 'Aolinpike Gongyuan\\(Olympic Park)'],
            secondaryName: false,
            num: '11',
            services: ['local'],
            parents: ['1lub'],
            children: ['snts'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['beijing', 'bj15', '#653279', '#fff', '15号线', 'Line 15']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        wq2x: {
            name: ['安德里北街', 'Andeli Beijie'],
            secondaryName: false,
            num: '15',
            services: ['local'],
            parents: ['4x3q'],
            children: ['iwp6'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        '4x3q': {
            name: ['安华桥', 'Anhuaqiao'],
            secondaryName: false,
            num: '14',
            services: ['local'],
            parents: ['zccy'],
            children: ['wq2x'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        zccy: {
            name: ['北土城', 'Beitucheng'],
            secondaryName: false,
            num: '13',
            services: ['local'],
            parents: ['snts'],
            children: ['4x3q'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['beijing', 'bj10', '#0092BC', '#fff', '10号线', 'Line 10']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        snts: {
            name: ['奥体中心', 'Aoti Zhongxin\\(Olympic Sports Center)'],
            secondaryName: false,
            num: '12',
            services: ['local'],
            parents: ['b8e9'],
            children: ['zccy'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        pxpc: {
            name: ['中国美术馆', 'Zhongguo Meishuguan\\(National Art Museum)'],
            secondaryName: false,
            num: '19',
            services: ['local'],
            parents: ['kyj2'],
            children: ['2nwq'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        kyj2: {
            name: ['南锣鼓巷', 'Nanluogu Xiang'],
            secondaryName: false,
            num: '18',
            services: ['local'],
            parents: ['nebf'],
            children: ['pxpc'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['beijing', 'bj6', '#B58500', '#fff', '6号线', 'Line 6']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        nebf: {
            name: ['什刹海', 'Shichahai'],
            secondaryName: false,
            num: '17',
            services: ['local'],
            parents: ['iwp6'],
            children: ['kyj2'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        iwp6: {
            name: ['鼓楼大街', 'Gulou Dajie'],
            secondaryName: false,
            num: '16',
            services: ['local'],
            parents: ['wq2x'],
            children: ['nebf'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['beijing', 'bj2', '#004B87', '#fff', '2号线', 'Line 2']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        '49zc': {
            name: ['珠市口', 'Zhushikou'],
            secondaryName: false,
            num: '23',
            services: ['local'],
            parents: ['kfzs'],
            children: ['9ydi'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['beijing', 'bj7', '#FFC56E', '#fff', '7号线', 'Line 7']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        kfzs: {
            name: ['前门', 'Qianmen'],
            secondaryName: false,
            num: '22',
            services: ['local'],
            parents: ['als3'],
            children: ['49zc'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['beijing', 'bj2', '#004B87', '#fff', '2号线', 'Line 2']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        als3: {
            name: ['王府井', 'Wangfujing'],
            secondaryName: false,
            num: '21',
            services: ['local'],
            parents: ['2nwq'],
            children: ['kfzs'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['beijing', 'bj1', '#A4343A', '#fff', '1号线\\八通线', 'Line 1\\Batong Line']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        '2nwq': {
            name: ['金鱼胡同', 'Jinyu Hutong'],
            secondaryName: false,
            num: '20',
            services: ['local'],
            parents: ['pxpc'],
            children: ['als3'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        i95z: {
            name: ['海户屯', 'Haihutun'],
            secondaryName: false,
            num: '27',
            services: ['local'],
            parents: ['apmy'],
            children: ['kkpg'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        apmy: {
            name: ['木樨园', 'Muxiyuan'],
            secondaryName: false,
            num: '26',
            services: ['local'],
            parents: ['cpp6'],
            children: ['i95z'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        cpp6: {
            name: ['永定门外', 'Yongdingmen Wai'],
            secondaryName: false,
            num: '25',
            services: ['local'],
            parents: ['9ydi'],
            children: ['apmy'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['beijing', 'bj14', '#CA9A8E', '#fff', '14号线', 'Line 14']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        '9ydi': {
            name: ['天桥', 'Tianqiao'],
            secondaryName: false,
            num: '24',
            services: ['local'],
            parents: ['49zc'],
            children: ['cpp6'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        n9of: {
            name: ['火箭万源', 'Huojian Wanyuan'],
            secondaryName: false,
            num: '32',
            services: ['local'],
            parents: ['ws9t'],
            children: ['0bpu'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        ws9t: {
            name: ['东高地', 'Donggaodi'],
            secondaryName: false,
            num: '31',
            services: ['local'],
            parents: ['vcxs'],
            children: ['n9of'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        vcxs: {
            name: ['和义', 'Heyi'],
            secondaryName: false,
            num: '30',
            services: ['local'],
            parents: ['nxsb'],
            children: ['ws9t'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        nxsb: {
            name: ['大红门南', 'Dahongmennan'],
            secondaryName: false,
            num: '29',
            services: ['local'],
            parents: ['kkpg'],
            children: ['vcxs'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        kkpg: {
            name: ['大红门', 'Dahongmen'],
            secondaryName: ['暂缓开通', 'Stay Open'],
            num: '28',
            services: [],
            parents: ['i95z'],
            children: ['nxsb'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['beijing', 'bj10', '#0092BC', '#fff', '10号线', 'Line 10']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        '8i85': {
            name: ['瀛海', 'Yinghai'],
            secondaryName: false,
            num: '35',
            services: ['local'],
            parents: ['xejm'],
            children: ['lineend'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        xejm: {
            name: ['德茂', 'Demao'],
            secondaryName: false,
            num: '34',
            services: ['local'],
            parents: ['0bpu'],
            children: ['8i85'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        '0bpu': {
            name: ['五福堂', 'Wufutang'],
            secondaryName: false,
            num: '33',
            services: ['local'],
            parents: ['n9of'],
            children: ['xejm'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
    },
    line_name: ['8号线', 'Line 8'],
    psd_num: '1',
    line_num: '08',
    info_panel_type: 'gz28',
    direction_gz_x: 50,
    direction_gz_y: 70,
    customiseMTRDest: { isLegacy: false, terminal: false },
    svgWidth: { destination: 1400, runin: 1300, railmap: 3000, indoor: 3000 },
    notesGZMTR: [],
    namePosMTR: { isStagger: true, isFlip: false },
};

export default params;
