const params = {
    svg_height: 450,
    padding: 5,
    y_pc: 40,
    branch_spacing: 44.44444444444444,
    theme: ['beijing', 'cae', '#A192B2', '#fff'],
    direction: 'r',
    current_stn_idx: 'a4',
    platform_num: '2',
    stn_list: {
        linestart: {
            parents: [],
            children: ['a4'],
            name: ['路綫左端', 'LEFT END'],
            branch: { left: [], right: [] },
            num: '00',
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        a4: {
            parents: ['linestart'],
            children: ['a50'],
            name: ['东直门', 'Dongzhi Men'],
            branch: { left: [], right: [] },
            num: '00',
            transfer: {
                tick_direc: 'r',
                paid_area: true,
                osi_names: [['', '']],
                info: [
                    [
                        ['beijing', 'bj2', '#004B87', '#fff', '2号线', 'Line 2'],
                        ['beijing', 'bj13', '#F4DA40', '#fff', '13号线', 'Line 13'],
                    ],
                    [],
                ],
            },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        a50: {
            parents: ['a4'],
            children: ['7so0'],
            name: ['三元桥', 'Sanyuan Qiao'],
            branch: { left: [], right: [] },
            num: '00',
            transfer: {
                tick_direc: 'r',
                paid_area: false,
                osi_names: [['', '']],
                info: [[['beijing', 'bj10', '#0092BC', '#fff', '10号线', 'Line 10']], []],
            },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        lineend: {
            parents: ['d91k'],
            children: [],
            name: ['路綫右端', 'RIGHT END'],
            branch: { left: [], right: [] },
            num: '00',
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        '7so0': {
            name: ['3号航站楼', 'Terminal 3'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['a50'],
            children: ['eolf'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        eolf: {
            name: ['2号航站楼', 'Terminal 2'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['7so0'],
            children: ['0mdo'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        '0mdo': {
            name: ['三元桥', 'Sanyuan Qiao'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['eolf'],
            children: ['d91k'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['beijing', 'bj10', '#0092BC', '#fff', '10号线', 'Line 10']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        d91k: {
            name: ['东直门', 'Dongzhi Men'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['0mdo'],
            children: ['lineend'],
            branch: { left: [], right: [] },
            transfer: {
                info: [
                    [
                        ['beijing', 'bj2', '#004B87', '#fff', '2号线', 'Line 2'],
                        ['beijing', 'bj13', '#F4DA40', '#fff', '13号线', 'Line 13'],
                    ],
                ],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
    },
    line_name: ['首都机场线', 'Capital Airport Express'],
    psd_num: '1',
    line_num: '1',
    info_panel_type: 'gz28',
    direction_gz_x: 50,
    direction_gz_y: 70,
    customiseMTRDest: { isLegacy: false, terminal: false },
    svgWidth: { destination: 2000, runin: 2000, railmap: 2000, indoor: 2000 },
    notesGZMTR: [],
    namePosMTR: { isStagger: true, isFlip: false },
};

export default params;
