const params = {
    svg_height: 450,
    padding: 8.750201061605276,
    y_pc: 40,
    branch_spacing: 45,
    theme: ['beijing', 's1l', '#A45A2A', '#fff'],
    direction: 'r',
    current_stn_idx: 'iwf6',
    platform_num: '2',
    stn_list: {
        linestart: {
            parents: [],
            children: ['iwf6'],
            name: ['路綫右端', 'RIGHT END'],
            branch: { left: [], right: [] },
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            num: '00',
            secondaryName: false,
        },
        lineend: {
            parents: ['l1mz'],
            children: [],
            name: ['路綫左端', 'LEFT END'],
            branch: { left: [], right: [] },
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            num: '09',
            secondaryName: false,
        },
        l1mz: {
            parents: ['7gkm'],
            children: ['lineend'],
            name: ['苹果园', 'Pingguoyuɑn'],
            branch: { left: [], right: [] },
            num: '08',
            transfer: {
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [
                    [
                        ['beijing', 'bj1', '#A4343A', '#fff', '1号线/八通线', 'Line 1/Batong Line'],
                        ['beijing', 'bj6', '#B58500', '#fff', '6号线', 'Line 6'],
                    ],
                ],
            },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        iwf6: {
            children: ['34ht'],
            parents: ['linestart'],
            name: ['石厂', 'Shichɑng'],
            branch: { left: [], right: [] },
            num: '01',
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        '34ht': {
            name: ['小园', 'Xiɑoyuɑn'],
            secondaryName: false,
            num: '02',
            services: ['local'],
            parents: ['iwf6'],
            children: ['oijs'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        oijs: {
            name: ['栗园庄', 'Liyuɑnzhuɑng'],
            secondaryName: false,
            num: '03',
            services: ['local'],
            parents: ['34ht'],
            children: ['2wiv'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        '2wiv': {
            name: ['上岸', "Shɑng'ɑn"],
            secondaryName: false,
            num: '04',
            services: ['local'],
            parents: ['oijs'],
            children: ['b0ce'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        b0ce: {
            name: ['桥户营', 'Qiɑohuying'],
            secondaryName: false,
            num: '05',
            services: ['local'],
            parents: ['2wiv'],
            children: ['hkxg'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        hkxg: {
            name: ['四道桥', 'Sidɑoqiɑo'],
            secondaryName: false,
            num: '06',
            services: ['local'],
            parents: ['b0ce'],
            children: ['7gkm'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        '7gkm': {
            name: ['金安桥', "Jin'ɑnqiɑo"],
            secondaryName: false,
            num: '07',
            services: ['local'],
            parents: ['hkxg'],
            children: ['l1mz'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['beijing', 'bj6', '#B58500', '#fff', '6号线', 'Line 6']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
    },
    line_name: ['S1线', 'Line S1'],
    psd_num: '1',
    line_num: 'S1',
    info_panel_type: 'sh',
    direction_gz_x: 50,
    direction_gz_y: 70,
    customiseMTRDest: { isLegacy: false, terminal: false },
    svgWidth: { destination: 2000, runin: 2000, railmap: 2000, indoor: 2000 },
    notesGZMTR: [],
    namePosMTR: { isStagger: true, isFlip: false },
};

export default params;
