const params = {
    style: 'gzmtr',
    svg_height: 450,
    padding: 8.750201061605276,
    y_pc: 40,
    branch_spacing: 45,
    theme: ['beijing', 'xjl', '#D22630', '#fff'],
    direction: 'r',
    current_stn_idx: 'cmxq',
    platform_num: '2',
    stn_list: {
        linestart: {
            parents: [],
            children: ['cmxq'],
            name: ['路綫右端', 'RIGHT END'],
            branch: { left: [], right: [] },
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            num: '00',
            secondaryName: false,
        },
        lineend: {
            parents: ['l1mz'],
            children: [],
            name: ['路綫左端', 'LEFT END'],
            branch: { left: [], right: [] },
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            num: '16',
            secondaryName: false,
        },
        l1mz: {
            parents: ['iwf6'],
            children: ['lineend'],
            name: ['定海园', 'Dinghai Yuan'],
            branch: { left: [], right: [] },
            num: '15',
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        iwf6: {
            children: ['l1mz'],
            parents: ['3sqe'],
            name: ['定海园西', 'Dinghai Yuan Xi(W)'],
            branch: { left: [], right: [] },
            num: '14',
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        '3sqe': {
            name: ['经海一路', 'Jinghai Yilu'],
            secondaryName: false,
            num: '13',
            services: ['local'],
            parents: ['e87x'],
            children: ['iwf6'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        e87x: {
            name: ['亦创会展中心', 'Beijing Etrong International\\Exhibition & Convention Center'],
            secondaryName: false,
            num: '12',
            services: ['local'],
            parents: ['then'],
            children: ['3sqe'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        then: {
            name: ['荣昌东街', 'Rongchang Dongjie'],
            secondaryName: false,
            num: '11',
            services: ['local'],
            parents: ['k69t'],
            children: ['e87x'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['beijing', 'yzl', '#D0006F', '#fff', '亦庄线', 'Yizhuang Line']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        k69t: {
            name: ['亦庄同仁', 'Yizhuang Tongren'],
            secondaryName: false,
            num: '10',
            services: ['local'],
            parents: ['f1py'],
            children: ['then'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        f1py: {
            name: ['鹿圈东', 'Lujuan Dong(E)'],
            secondaryName: false,
            num: '09',
            services: ['local'],
            parents: ['qqsw'],
            children: ['k69t'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        qqsw: {
            name: ['泰河路', 'Taihe Lu'],
            secondaryName: false,
            num: '08',
            services: ['local'],
            parents: ['mjx0'],
            children: ['f1py'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        mjx0: {
            name: ['九号村', 'Jiuhao Cun'],
            secondaryName: false,
            num: '07',
            services: ['local'],
            parents: ['xvy4'],
            children: ['qqsw'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        xvy4: {
            name: ['四海庄', 'Sihai Zhuang'],
            secondaryName: false,
            num: '06',
            services: ['local'],
            parents: ['yagy'],
            children: ['mjx0'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        yagy: {
            name: ['太和桥北', 'Taihe Qiao Bei(N)'],
            secondaryName: false,
            num: '05',
            services: ['local'],
            parents: ['icia'],
            children: ['xvy4'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        icia: {
            name: ['瑞合庄', 'Ruihe Zhuang'],
            secondaryName: false,
            num: '04',
            services: ['local'],
            parents: ['clbr'],
            children: ['yagy'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        clbr: {
            name: ['融兴街', 'Rongxing Jie'],
            secondaryName: false,
            num: '03',
            services: ['local'],
            parents: ['0qby'],
            children: ['icia'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        '0qby': {
            name: ['屈庄', 'Qu Zhuang'],
            secondaryName: false,
            num: '02',
            services: ['local'],
            parents: ['cmxq'],
            children: ['clbr'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        cmxq: {
            name: ['老观里', 'Laoguan Li'],
            secondaryName: false,
            num: '01',
            services: ['local'],
            parents: ['linestart'],
            children: ['0qby'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
    },
    line_name: ['亦庄T1', 'Yizhuang T1 Line'],
    psd_num: '1',
    line_num: 'T1',
    info_panel_type: 'gz28',
    direction_gz_x: 50,
    direction_gz_y: 70,
    customiseMTRDest: { isLegacy: false, terminal: false },
    svgWidth: { destination: 2000, runin: 2000, railmap: 2000, indoor: 2000 },
    notesGZMTR: [],
    namePosMTR: { isStagger: true, isFlip: false },
};

export default params;
