const params = {
    svg_height: 450,
    padding: 8.750201061605276,
    y_pc: 40,
    branch_spacing: 45,
    faketheme: ['beijing', 'xiliuxian'],
    theme: ['beijing', 'xjl', '#D22630', '#fff'],
    direction: 'r',
    current_stn_idx: 'ez7s',
    platform_num: '2',
    stn_list: {
        linestart: {
            parents: [],
            children: ['ez7s'],
            name: ['路綫右端', 'RIGHT END'],
            branch: { left: [], right: [] },
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            num: '00',
            secondaryName: false,
        },
        lineend: {
            parents: ['l1mz'],
            children: [],
            name: ['路綫左端', 'LEFT END'],
            branch: { left: [], right: [] },
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            num: '07',
            secondaryName: false,
        },
        l1mz: {
            parents: ['iwf6'],
            children: ['lineend'],
            name: ['巴沟', 'Bɑgou'],
            branch: { left: [], right: [] },
            num: '06',
            transfer: {
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [[['beijing', 'bj10', '#0092BC', '#fff', '10号线', 'Line 10']]],
            },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        iwf6: {
            children: ['l1mz'],
            parents: ['zumd'],
            name: ['颐和园西门', 'Yiheyuɑn Ximen\\(Summer Palace West Gate)'],
            branch: { left: [], right: [] },
            num: '05',
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        zumd: {
            name: ['茶棚', 'Chɑpeng'],
            secondaryName: false,
            num: '04',
            services: ['local'],
            parents: ['lr75'],
            children: ['iwf6'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        lr75: {
            name: ['万安', "Wɑn'ɑn"],
            secondaryName: false,
            num: '03',
            services: ['local'],
            parents: ['hhgt'],
            children: ['zumd'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        hhgt: {
            name: ['植物园', 'Zhiwuyuɑn\\(Botanical Garden)'],
            secondaryName: false,
            num: '02',
            services: ['local'],
            parents: ['ez7s'],
            children: ['lr75'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        ez7s: {
            name: ['香山', 'Xiɑngshɑn\\(Fragrant Hills)'],
            secondaryName: false,
            num: '01',
            services: ['local'],
            parents: ['linestart'],
            children: ['hhgt'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
    },
    line_name: ['西郊线', 'Xijiao Line'],
    psd_num: '1',
    line_num: 'XJ',
    info_panel_type: 'gz28',
    direction_gz_x: 50,
    direction_gz_y: 70,
    customiseMTRDest: { isLegacy: false, terminal: false },
    svgWidth: { destination: 2000, runin: 2000, railmap: 2000, indoor: 2000 },
    notesGZMTR: [],
    namePosMTR: { isStagger: true, isFlip: false },
};

export default params;
