const param = {
    style: 'shmetro',
    svg_height: 400,
    padding: 8.750201061605276,
    y_pc: 40,
    branch_spacing: 45,
    theme: ['shanghai', 'sh3', '#FFD100', '#000'],
    direction: 'r',
    current_stn_idx: 's9tt',
    platform_num: '2',
    stn_list: {
        linestart: {
            parents: [],
            children: ['vzv2', 's9tt'],
            name: ['路綫左端', 'LEFT END'],
            branch: { left: [], right: ['through', 's9tt'] },
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            num: '00',
            secondaryName: false,
        },
        lineend: {
            parents: ['l9j9', 'fcqo'],
            children: [],
            name: ['路綫右端', 'RIGHT END'],
            branch: { left: ['through', 'fcqo'], right: [] },
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            num: '00',
            secondaryName: false,
        },
        l1mz: {
            parents: ['vzv2', 'syq7'],
            children: ['ll8u'],
            name: ['l1mz', '1'],
            branch: { left: ['through', 'syq7'], right: [] },
            num: '02',
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        iwf6: {
            children: ['l9j9', 'fmlo'],
            parents: ['ll8u'],
            name: ['iwf6', '1'],
            branch: { left: [], right: ['through', 'fmlo'] },
            num: '01',
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        vzv2: {
            name: ['vzv2', '1'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['linestart'],
            children: ['l1mz'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        l9j9: {
            name: ['l9j9', '1'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['iwf6'],
            children: ['lineend'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        ll8u: {
            name: ['ll8u', '1'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['l1mz'],
            children: ['iwf6'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        syq7: {
            name: ['syq7', '1'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['s9tt'],
            children: ['l1mz'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        fmlo: {
            name: ['fmlo', '1'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['iwf6'],
            children: ['fcqo'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        fcqo: {
            name: ['fcqo', '1'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['fmlo'],
            children: ['lineend'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        s9tt: {
            name: ['s9tt', '1'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['linestart'],
            children: ['syq7'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
    },
    line_name: ['荃灣綫', 'Tsuen Wan Line'],
    psd_num: '1',
    line_num: 'TW',
    info_panel_type: 'sh2020',
    direction_gz_x: 50,
    direction_gz_y: 70,
    customiseMTRDest: { isLegacy: false, terminal: false },
    svgWidth: { destination: 1000, runin: 1000, railmap: 800, indoor: 800 },
    notesGZMTR: [],
    namePosMTR: { isStagger: true, isFlip: false },
    coline: [
        {
            from: 'l1mz',
            to: 'iwf6',
            colors: [['shanghai', 'sh4', '#5F259F', '#fff', '4号线', 'Line 4']],
            display: true,
        },
        {
            from: 'iwf6',
            to: 'fcqo',
            colors: [['shanghai', 'sh4', '#5F259F', '#fff', '4号线', 'Line 4']],
            display: true,
        },
        {
            from: 's9tt',
            to: 'l1mz',
            colors: [['shanghai', 'sh4', '#5F259F', '#fff', '4号线', 'Line 4']],
            display: true,
        },
    ],
};

export default param;
