const param = {
    style: 'shmetro',
    svg_height: 300,
    padding: 8.750201061605276,
    y_pc: 40,
    branch_spacing: 45,
    theme: ['shanghai', 'sh3', '#FFD100', '#000'],
    direction: 'r',
    current_stn_idx: 'll8u',
    platform_num: '2',
    stn_list: {
        linestart: {
            parents: [],
            children: ['tl2a', 'vzv2'],
            name: ['路綫左端', 'LEFT END'],
            branch: { left: [], right: ['through', 'tl2a'] },
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            num: '00',
            secondaryName: false,
        },
        lineend: {
            parents: ['h2tm', 'l9j9'],
            children: [],
            name: ['路綫右端', 'RIGHT END'],
            branch: { left: ['through', 'h2tm'], right: [] },
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            num: '00',
            secondaryName: false,
        },
        l1mz: {
            parents: ['tl2a', 'vzv2'],
            children: ['ll8u'],
            name: ['l1mz', ''],
            branch: { left: ['through', 'tl2a'], right: [] },
            num: '02',
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        iwf6: {
            children: ['h2tm', 'l9j9'],
            parents: ['ll8u'],
            name: ['iwf6', ''],
            branch: { left: [], right: ['through', 'h2tm'] },
            num: '01',
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        vzv2: {
            name: ['vzv2', ''],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['linestart'],
            children: ['l1mz'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        tl2a: {
            name: ['tl2a', ''],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['linestart'],
            children: ['l1mz'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        l9j9: {
            name: ['l9j9', ''],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['iwf6'],
            children: ['lineend'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        h2tm: {
            name: ['h2tm', ''],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['iwf6'],
            children: ['lineend'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        ll8u: {
            name: ['ll8u', ''],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['l1mz'],
            children: ['iwf6'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
    },
    line_name: ['3号线', 'Line 3'],
    psd_num: '1',
    line_num: 'SH3',
    info_panel_type: 'sh',
    direction_gz_x: 50,
    direction_gz_y: 70,
    customiseMTRDest: { isLegacy: false, terminal: false },
    svgWidth: { destination: 1000, runin: 1000, railmap: 800, indoor: 800 },
    notesGZMTR: [],
    namePosMTR: { isStagger: true, isFlip: false },
};

export default param;
