const params = {
    style: 'mtr',
    svg_height: 450,
    padding: 7,
    y_pc: 46.48,
    branch_spacing: 59.58,
    theme: ['other', 'other', '#BF3334', '#fff'],
    direction: 'r',
    current_stn_idx: 'um47',
    platform_num: '2',
    stn_list: {
        linestart: {
            parents: [],
            children: ['iwf6'],
            name: ['路綫右端', 'RIGHT END'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [[]],
            },
            services: ['local'],
            facility: '',
            num: '00',
            secondaryName: false,
        },
        lineend: {
            parents: ['103x', 'l1mz'],
            children: [],
            name: ['路綫左端', 'LEFT END'],
            branch: {
                left: ['through', '103x'],
                right: [],
            },
            transfer: {
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [[]],
            },
            services: ['local'],
            facility: '',
            num: '18',
            secondaryName: false,
        },
        l1mz: {
            parents: ['z6ud'],
            children: ['lineend'],
            name: ['昆明南火车站', 'Kunming South Railway Station'],
            branch: {
                left: [],
                right: [],
            },
            num: '22',
            transfer: {
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [[['other', 'other', '#EE7C30', '#fff', '4号线', 'Line 4']]],
            },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        iwf6: {
            children: ['v9cl'],
            parents: ['linestart'],
            name: ['环城南路', 'South Ring Rd'],
            branch: {
                left: [],
                right: [],
            },
            num: '01',
            transfer: {
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [[['other', 'other', '#235A99', '#fff', '2号线', 'Line 2']]],
            },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        vj9w: {
            name: ['春融街', 'Chunrong St'],
            secondaryName: false,
            num: '13',
            services: ['local'],
            parents: ['gg5z'],
            children: ['ytpc', 'scuc'],
            branch: {
                left: [],
                right: ['through', 'ytpc'],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        '103x': {
            name: ['大学城南', 'University Town South'],
            secondaryName: false,
            num: '18',
            services: ['local'],
            parents: ['ydin'],
            children: ['lineend'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        v9cl: {
            name: ['昆明火车站', 'Kunming Railway Station'],
            secondaryName: false,
            num: '02',
            services: ['local'],
            parents: ['iwf6'],
            children: ['dpwk'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        dpwk: {
            name: ['福德', 'Fude'],
            secondaryName: false,
            num: '03',
            services: ['local'],
            parents: ['v9cl'],
            children: ['25h9'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        '25h9': {
            name: ['日新路', 'Rixin Rd'],
            secondaryName: false,
            num: '04',
            services: ['local'],
            parents: ['dpwk'],
            children: ['x58g'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        x58g: {
            name: ['巫家坝', 'Wujiaba'],
            secondaryName: false,
            num: '05',
            services: ['local'],
            parents: ['25h9'],
            children: ['d1vc'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        d1vc: {
            name: ['昌宏西路', 'Changhong West Rd'],
            secondaryName: false,
            num: '06',
            services: ['local'],
            parents: ['x58g'],
            children: ['a413'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        a413: {
            name: ['晓东村', 'Xiaodongcun'],
            secondaryName: false,
            num: '07',
            services: ['local'],
            parents: ['d1vc'],
            children: ['t3xu'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        t3xu: {
            name: ['珥季路', 'Erji Rd'],
            secondaryName: false,
            num: '08',
            services: ['local'],
            parents: ['a413'],
            children: ['xnt5'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        xnt5: {
            name: ['星耀路', 'Xingyao Rd'],
            secondaryName: false,
            num: '09',
            services: ['local'],
            parents: ['t3xu'],
            children: ['qiqi'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        qiqi: {
            name: ['新亚洲体育城', 'New Asia Athletics Park'],
            secondaryName: false,
            num: '10',
            services: ['local'],
            parents: ['xnt5'],
            children: ['um47'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        um47: {
            name: ['南部汽车站', 'South Coach'],
            secondaryName: false,
            num: '11',
            services: ['local'],
            parents: ['qiqi'],
            children: ['gg5z'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        gg5z: {
            name: ['斗南', 'Dounan'],
            secondaryName: false,
            num: '12',
            services: ['local'],
            parents: ['um47'],
            children: ['vj9w'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[['other', 'other', '#EE7C30', '#fff', '4号线', 'Line 4']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        ytpc: {
            name: ['驼峰街', 'Tuofeng St'],
            secondaryName: false,
            num: '14',
            services: ['local'],
            parents: ['vj9w'],
            children: ['pyto'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        pyto: {
            name: ['联大街', 'Lianda St'],
            secondaryName: false,
            num: '15',
            services: ['local'],
            parents: ['ytpc'],
            children: ['c3uq'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[['other', 'other', '#EE7C30', '#fff', '4号线', 'Line 4']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        c3uq: {
            name: ['谊康南路', 'Yikang South Rd'],
            secondaryName: false,
            num: '16',
            services: ['local'],
            parents: ['pyto'],
            children: ['ydin'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        ydin: {
            name: ['大学城', 'University Town'],
            secondaryName: false,
            num: '17',
            services: ['local'],
            parents: ['c3uq'],
            children: ['103x'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        scuc: {
            name: ['市级行政中心·清风', 'Municipal Administration Center'],
            secondaryName: false,
            num: '19',
            services: ['local'],
            parents: ['vj9w'],
            children: ['1rs7'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        '1rs7': {
            name: ['宜和路', 'Yihe Rd'],
            secondaryName: false,
            num: '20',
            services: ['local'],
            parents: ['scuc'],
            children: ['z6ud'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        z6ud: {
            name: ['白龙潭', 'Zulu Six Uniform Delta'],
            secondaryName: false,
            num: '21',
            services: ['local'],
            parents: ['1rs7'],
            children: ['l1mz'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
    },
    line_name: ['1号线', 'Line 1'],
    psd_num: '12',
    line_num: '1',
    info_panel_type: 'gzgf',
    direction_gz_x: 42.91,
    direction_gz_y: 78.63,
    customiseMTRDest: {
        isLegacy: false,
        terminal: false,
    },
    svgWidth: {
        destination: 2000,
        runin: 2000,
        railmap: 2500,
        indoor: 2500,
    },
    notesGZMTR: [
        [
            '1号线现与2号线在环城南路站贯通运行。',
            'Line 1 now can run through with Line 2 at South Ring Rd Station.',
            9,
            77,
            true,
        ],
    ],
    namePosMTR: {
        isStagger: true,
        isFlip: false,
    },
};

export default params;
