const params = {
    style: 'gzmtr',
    svg_height: 400,
    padding: 7,
    y_pc: 70,
    branch_spacing: 70,
    theme: ['kunming', 'km1', '#BF3334', '#fff'],
    direction: 'l',
    current_stn_idx: 'iwf6',
    platform_num: '4',
    stn_list: {
        linestart: {
            parents: [],
            children: ['gn94', 'l1mz'],
            name: ['路綫左端', 'LEFT END'],
            branch: { left: [], right: ['through', 'gn94'] },
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            num: '18',
            secondaryName: false,
        },
        lineend: {
            parents: ['iwf6'],
            children: [],
            name: ['路綫右端', 'RIGHT END'],
            branch: { left: [], right: [] },
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            num: '00',
            secondaryName: false,
        },
        l1mz: {
            parents: ['linestart'],
            children: ['z6ud'],
            name: ['大学城南', 'University Town South'],
            branch: { left: [], right: [] },
            num: '18',
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        iwf6: {
            children: ['lineend'],
            parents: ['v9cl'],
            name: ['环城南路', 'South Ring Rd.'],
            branch: { left: [], right: [] },
            num: '01',
            transfer: {
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [[['kunming', 'km2', '#235A99', '#fff', '2号线', 'Line 2']]],
            },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        vj9w: {
            name: ['春融街', 'Chunrong St.'],
            secondaryName: false,
            num: '13',
            services: ['local'],
            parents: ['mgnz', 'scuc'],
            children: ['gg5z'],
            branch: { left: ['through', 'mgnz'], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        v9cl: {
            name: ['昆明火车站', 'Kunming Railway Station'],
            secondaryName: false,
            num: '02',
            services: ['local'],
            parents: ['dpwk'],
            children: ['iwf6'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        dpwk: {
            name: ['福德', 'Fude'],
            secondaryName: false,
            num: '03',
            services: ['local'],
            parents: ['25h9'],
            children: ['v9cl'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        '25h9': {
            name: ['日新路', 'Rixin Rd.'],
            secondaryName: false,
            num: '04',
            services: ['local'],
            parents: ['x58g'],
            children: ['dpwk'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        x58g: {
            name: ['巫家坝', 'Wujiaba'],
            secondaryName: false,
            num: '05',
            services: ['local'],
            parents: ['d1vc'],
            children: ['25h9'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        d1vc: {
            name: ['昌宏西路', 'Changhong West Rd.'],
            secondaryName: false,
            num: '06',
            services: ['local'],
            parents: ['a413'],
            children: ['x58g'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        a413: {
            name: ['晓东村', 'Xiaodongcun'],
            secondaryName: false,
            num: '07',
            services: ['local'],
            parents: ['t3xu'],
            children: ['d1vc'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        t3xu: {
            name: ['珥季路', 'Erji Rd.'],
            secondaryName: false,
            num: '08',
            services: ['local'],
            parents: ['xnt5'],
            children: ['a413'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        xnt5: {
            name: ['星耀路', 'Xingyao Rd.'],
            secondaryName: false,
            num: '09',
            services: ['local'],
            parents: ['qiqi'],
            children: ['t3xu'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        qiqi: {
            name: ['新亚洲体育城', 'New Asia Athletics Park'],
            secondaryName: false,
            num: '10',
            services: ['local'],
            parents: ['um47'],
            children: ['xnt5'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        um47: {
            name: ['南部汽车站', 'South Coach Station'],
            secondaryName: false,
            num: '11',
            services: ['local'],
            parents: ['gg5z'],
            children: ['qiqi'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        gg5z: {
            name: ['斗南', 'Dounan'],
            secondaryName: false,
            num: '12',
            services: ['local'],
            parents: ['vj9w'],
            children: ['um47'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['kunming', 'km4', '#EE7C30', '#fff', '4号线', 'Line 4']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        scuc: {
            name: ['驼峰街', 'Tuofeng St.'],
            secondaryName: false,
            num: '14',
            services: ['local'],
            parents: ['1s8f'],
            children: ['vj9w'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        '1rs7': {
            name: ['谊康南路', 'Yikang South Rd.'],
            secondaryName: false,
            num: '16',
            services: ['local'],
            parents: ['z6ud'],
            children: ['1s8f'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        z6ud: {
            name: [' 大学城', 'University Town'],
            secondaryName: false,
            num: '17',
            services: ['local'],
            parents: ['l1mz'],
            children: ['1rs7'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        '1s8f': {
            name: ['联大街', 'Lianda St.'],
            secondaryName: false,
            num: '15',
            services: ['local'],
            parents: ['1rs7'],
            children: ['scuc'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['kunming', 'km4', '#EE7C30', '#fff', '4号线', 'Line 4']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        mgnz: {
            name: ['市级行政中心·清风', 'Municipal Administration Center'],
            secondaryName: false,
            num: '19',
            services: ['local'],
            parents: ['74hc'],
            children: ['vj9w'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        '74hc': {
            name: ['宜和路', 'Yihe Rd.'],
            secondaryName: false,
            num: '20',
            services: ['local'],
            parents: ['bhii'],
            children: ['mgnz'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        bhii: {
            name: ['白龙潭', 'Bailongtan'],
            secondaryName: false,
            num: '21',
            services: ['local'],
            parents: ['gn94'],
            children: ['74hc'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        gn94: {
            name: ['昆明南火车站', 'Kunming South Railway Station'],
            secondaryName: false,
            num: '22',
            services: ['local'],
            parents: ['linestart'],
            children: ['bhii'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['kunming', 'km4', '#EE7C30', '#fff', '4号线', 'Line 4']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
    },
    line_name: ['1号线', 'Line 1'],
    psd_num: '12',
    line_num: '1',
    info_panel_type: 'gzgf',
    direction_gz_x: 75,
    direction_gz_y: 20,
    customiseMTRDest: { isLegacy: false, terminal: false },
    svgWidth: { destination: 1893, runin: 1507, railmap: 1893, indoor: 1893 },
    notesGZMTR: [
        [
            '1号线现与2号线在环城南路站贯通运行。',
            'Line 1 now run through with Line 2 at South Ring Rd Station.',
            70,
            77.5,
            true,
        ],
    ],
    namePosMTR: { isStagger: true, isFlip: false },
};

export default params;
