const params = {
    style: 'gzmtr',
    svg_height: 300,
    padding: 7,
    y_pc: 40,
    branch_spacing: 60,
    theme: ['kunming', 'km2', '#235A99', '#fff'],
    direction: 'l',
    current_stn_idx: 'l1mz',
    platform_num: '2',
    stn_list: {
        linestart: {
            parents: [],
            children: ['iwf6'],
            name: ['路綫右端', 'RIGHT END'],
            branch: { left: [], right: [] },
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            num: '15',
            secondaryName: false,
        },
        lineend: {
            parents: ['l1mz'],
            children: [],
            name: ['路綫左端', 'LEFT END'],
            branch: { left: [], right: [] },
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            num: '00',
            secondaryName: false,
        },
        l1mz: {
            parents: ['vj9w'],
            children: ['lineend'],
            name: ['北部汽车站', 'North Coach Station'],
            branch: { left: [], right: [] },
            num: '01',
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        iwf6: {
            children: ['8idn'],
            parents: ['linestart'],
            name: ['环城南路', 'South Ring Rd.'],
            branch: { left: [], right: [] },
            num: '14',
            transfer: {
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [[['kunming', 'km1', '#BF3334', '#fff', '1号线', 'Line 1']]],
            },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        vj9w: {
            name: ['龙头街', 'Longtou St.'],
            secondaryName: false,
            num: '02',
            services: ['local'],
            parents: ['zbkt'],
            children: ['l1mz'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        zbkt: {
            name: ['司家营', 'Sijiaying'],
            secondaryName: false,
            num: '03',
            services: ['local'],
            parents: ['wnkz'],
            children: ['vj9w'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        wnkz: {
            name: ['羊肠村', 'Yangchangcun'],
            secondaryName: false,
            num: '04',
            services: ['local'],
            parents: ['mick'],
            children: ['zbkt'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        mick: {
            name: ['霖雨桥', 'Linyuqiao'],
            secondaryName: false,
            num: '05',
            services: ['local'],
            parents: ['edjq'],
            children: ['wnkz'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        edjq: {
            name: ['北辰', 'Beichen'],
            secondaryName: false,
            num: '06',
            services: ['local'],
            parents: ['q29r'],
            children: ['mick'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        q29r: {
            name: ['金星', 'Jinxing'],
            secondaryName: false,
            num: '07',
            services: ['local'],
            parents: ['gdsw'],
            children: ['edjq'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        gdsw: {
            name: ['白云路', 'Baiyun Rd.'],
            secondaryName: false,
            num: '08',
            services: ['local'],
            parents: ['3l2q'],
            children: ['q29r'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        '3l2q': {
            name: ['火车北站', 'North Railway Station'],
            secondaryName: false,
            num: '09',
            services: ['local'],
            parents: ['j2a9'],
            children: ['gdsw'],
            branch: { left: [], right: [] },
            transfer: {
                info: [
                    [
                        ['kunming', 'km4', '#EE7C30', '#fff', '4号线', 'Line 4'],
                        ['kunming', 'km5', '#2AA844', '#fff', '5号线', 'Line 5'],
                    ],
                ],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        j2a9: {
            name: ['穿心鼓楼', 'Chuanxin Gulou'],
            secondaryName: false,
            num: '10',
            services: ['local'],
            parents: ['n3xx'],
            children: ['3l2q'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        n3xx: {
            name: ['交三桥', 'Jiaosanqiao'],
            secondaryName: false,
            num: '11',
            services: ['local'],
            parents: ['svuy'],
            children: ['j2a9'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        svuy: {
            name: ['东风广场', 'Dongfeng Square'],
            secondaryName: false,
            num: '12',
            services: ['local'],
            parents: ['8idn'],
            children: ['n3xx'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['kunming', 'km3', '#D02E81', '#fff', '3号线', 'Line 3']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        '8idn': {
            name: ['塘子巷', 'Tangzixiang'],
            secondaryName: false,
            num: '13',
            services: ['local'],
            parents: ['iwf6'],
            children: ['svuy'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['kunming', 'km6', '#3D89A8', '#fff', '6号线', 'Line 6']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
    },
    line_name: ['2号线', 'Line 2'],
    psd_num: '12',
    line_num: '2',
    info_panel_type: 'gzgf',
    direction_gz_x: 50,
    direction_gz_y: 70,
    customiseMTRDest: {
        isLegacy: false,
        terminal: ['昆明南火车站/大学城南', 'Kunming South Railway Station/University Town South'],
    },
    svgWidth: { destination: 1420, runin: 1130, railmap: 1420, indoor: 1420 },
    notesGZMTR: [
        [
            '2号线现与1号线在环城南路站贯通运行。',
            'Line 2 now run through with Line 1 at South Ring Rd Station.',
            5.5,
            65,
            true,
        ],
    ],
    namePosMTR: { isStagger: true, isFlip: false },
};

export default params;
