const params = {
    style: 'gzmtr',
    svg_height: 300,
    padding: 4,
    y_pc: 50,
    branch_spacing: 60,
    theme: ['kunming', 'km5', '#2AA844', '#fff'],
    direction: 'l',
    current_stn_idx: 'l1mz',
    platform_num: '2',
    stn_list: {
        linestart: {
            parents: [],
            children: ['iwf6'],
            name: ['路綫右端', 'RIGHT END'],
            branch: { left: [], right: [] },
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            num: '23',
            secondaryName: false,
        },
        lineend: {
            parents: ['l1mz'],
            children: [],
            name: ['路綫左端', 'LEFT END'],
            branch: { left: [], right: [] },
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            num: '00',
            secondaryName: false,
        },
        l1mz: {
            parents: ['eox3'],
            children: ['lineend'],
            name: ['世博园', 'EXPO Park'],
            branch: { left: [], right: [] },
            num: '01',
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        iwf6: {
            children: ['2m3f'],
            parents: ['linestart'],
            name: ['宝丰', 'Baofeng'],
            branch: { left: [], right: [] },
            num: '22',
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        eox3: {
            name: ['白龙寺', 'Bailongshi'],
            secondaryName: false,
            num: '02',
            services: ['local'],
            parents: ['z0o5'],
            children: ['l1mz'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        z0o5: {
            name: ['石闸', 'Shizha'],
            secondaryName: false,
            num: '03',
            services: ['local'],
            parents: ['qmiy'],
            children: ['eox3'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        qmiy: {
            name: ['穿金路', 'Chuanjin Rd'],
            secondaryName: false,
            num: '04',
            services: ['local'],
            parents: ['fwip'],
            children: ['z0o5'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        fwip: {
            name: ['火车北站', 'North Railway Station'],
            secondaryName: false,
            num: '05',
            services: ['local'],
            parents: ['7ojl'],
            children: ['qmiy'],
            branch: { left: [], right: [] },
            transfer: {
                info: [
                    [
                        ['kunming', 'km2', '#235A99', '#fff', '2号线', 'Line 2'],
                        ['kunming', 'km4', '#EE7C30', '#fff', '4号线', 'Line 4'],
                    ],
                ],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        '7ojl': {
            name: ['圆通山', 'Yuantongshan'],
            secondaryName: false,
            num: '06',
            services: ['local'],
            parents: ['xnl8'],
            children: ['fwip'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        xnl8: {
            name: ['华山西路', 'Huashan West Rd.'],
            secondaryName: false,
            num: '07',
            services: ['local'],
            parents: ['7lpq'],
            children: ['7ojl'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        '7lpq': {
            name: ['五一路', 'Wuyi Rd.'],
            secondaryName: false,
            num: '08',
            services: ['local'],
            parents: ['5n5g'],
            children: ['xnl8'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['kunming', 'km3', '#D02E81', '#fff', '3号线', 'Line 3']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        '5n5g': {
            name: ['弥勒寺', 'Mileshi'],
            secondaryName: false,
            num: '09',
            services: ['local'],
            parents: ['ddds'],
            children: ['7lpq'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        ddds: {
            name: ['严家地', 'Yanjiadi'],
            secondaryName: false,
            num: '10',
            services: ['local'],
            parents: ['q5k4'],
            children: ['5n5g'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        q5k4: {
            name: ['金兰路', 'Jinlan Rd.'],
            secondaryName: false,
            num: '11',
            services: ['local'],
            parents: ['fduy'],
            children: ['ddds'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        fduy: {
            name: ['福海', 'Fuhai'],
            secondaryName: false,
            num: '12',
            services: ['local'],
            parents: ['0j99'],
            children: ['q5k4'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        '0j99': {
            name: ['广福路西口', 'Guangfu Rd. West Intersection'],
            secondaryName: false,
            num: '13',
            services: ['local'],
            parents: ['di04'],
            children: ['fduy'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        di04: {
            name: ['大坝', 'Daba'],
            secondaryName: false,
            num: '14',
            services: ['local'],
            parents: ['gkym'],
            children: ['0j99'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        gkym: {
            name: ['迎海路', 'Yinhai Rd.'],
            secondaryName: false,
            num: '15',
            services: ['local'],
            parents: ['5vfh'],
            children: ['di04'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        '5vfh': {
            name: ['渔户村', 'Yuhucun'],
            secondaryName: false,
            num: '16',
            services: ['local'],
            parents: ['brbk'],
            children: ['gkym'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        brbk: {
            name: ['兴体路', 'Xinti Rd.'],
            secondaryName: false,
            num: '17',
            services: ['local'],
            parents: ['1h10'],
            children: ['5vfh'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        '1h10': {
            name: ['庄家塘立交桥', 'Zhuangjiatang Overpass'],
            secondaryName: false,
            num: '18',
            services: ['local'],
            parents: ['flio'],
            children: ['brbk'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        flio: {
            name: ['金家河', 'Jinjiahe'],
            secondaryName: false,
            num: '19',
            services: ['local'],
            parents: ['ojps'],
            children: ['1h10'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        ojps: {
            name: ['福保', 'Fubao'],
            secondaryName: false,
            num: '20',
            services: ['local'],
            parents: ['2m3f'],
            children: ['flio'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        '2m3f': {
            name: ['滇池国际会展中心', 'Dianchi Convention & Exhibition Center'],
            secondaryName: false,
            num: '21',
            services: ['local'],
            parents: ['iwf6'],
            children: ['ojps'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
    },
    line_name: ['5号线', 'Line 5'],
    psd_num: '12',
    line_num: '5',
    info_panel_type: 'gzgf',
    direction_gz_x: 45,
    direction_gz_y: 70,
    customiseMTRDest: { isLegacy: false, terminal: false },
    svgWidth: { destination: 1420, runin: 1130, railmap: 1420, indoor: 1420 },
    notesGZMTR: [],
    namePosMTR: { isStagger: true, isFlip: false },
};

export default params;
