const params = {
    style: 'gzmtr',
    svg_height: 300,
    padding: 10,
    y_pc: 40,
    branch_spacing: 60,
    theme: ['kunming', 'km6', '#3D89A8', '#fff'],
    direction: 'l',
    current_stn_idx: 'iwf6',
    platform_num: '4',
    stn_list: {
        linestart: {
            parents: [],
            children: ['l1mz'],
            name: ['路綫左端', 'LEFT END'],
            branch: { left: [], right: [] },
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            num: '09',
            secondaryName: false,
        },
        lineend: {
            parents: ['iwf6'],
            children: [],
            name: ['路綫右端', 'RIGHT END'],
            branch: { left: [], right: [] },
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            num: '00',
            secondaryName: false,
        },
        l1mz: {
            parents: ['linestart'],
            children: ['svfu'],
            name: ['机场中心', 'Kunming Airport'],
            branch: { left: [], right: [] },
            num: '08',
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: 'airport',
            secondaryName: false,
        },
        iwf6: {
            children: ['lineend'],
            parents: ['lp3f'],
            name: ['塘子巷', 'Tangzixiang'],
            branch: { left: [], right: [] },
            num: '01',
            transfer: {
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [[['kunming', 'km2', '#235A99', '#fff', '2号线', 'Line 2']]],
            },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        lp3f: {
            name: ['岔街', 'Chajie'],
            secondaryName: false,
            num: '02',
            services: ['local'],
            parents: ['b4un'],
            children: ['iwf6'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        b4un: {
            name: ['东郊路', 'Dongjiao Rd.'],
            secondaryName: false,
            num: '03',
            services: ['local'],
            parents: ['opbi'],
            children: ['lp3f'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        opbi: {
            name: ['菊华', 'Juhua'],
            secondaryName: false,
            num: '04',
            services: ['local'],
            parents: ['2w14'],
            children: ['b4un'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['kunming', 'km4', '#EE7C30', '#fff', '4号线', 'Line 4']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        '2w14': {
            name: ['东部汽车站', 'East Coach Station'],
            secondaryName: false,
            num: '05',
            services: ['local'],
            parents: ['aa5c'],
            children: ['opbi'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['kunming', 'km3', '#D02E81', '#fff', '3号线', 'Line 3']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        aa5c: {
            name: ['大板桥', 'Dabanqiao'],
            secondaryName: false,
            num: '06',
            services: ['local'],
            parents: ['svfu'],
            children: ['2w14'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        svfu: {
            name: ['机场前', 'Airport Front'],
            secondaryName: false,
            num: '07',
            services: ['local'],
            parents: ['l1mz'],
            children: ['aa5c'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
    },
    line_name: ['6号线', 'Line 6'],
    psd_num: '12',
    line_num: '6',
    info_panel_type: 'gzgf',
    direction_gz_x: 50,
    direction_gz_y: 70,
    customiseMTRDest: { isLegacy: false, terminal: false },
    svgWidth: { destination: 1420, runin: 1130, railmap: 1420, indoor: 1420 },
    notesGZMTR: [],
    namePosMTR: { isStagger: true, isFlip: false },
};

export default params;
