const params = {
    style: 'gzmtr',
    svg_height: 330,
    padding: 5.353925353925354,
    y_pc: 43.06,
    branch_spacing: 47.82,
    theme: ['saopaulo', 'sp10', '#007C8F', '#fff'],
    direction: 'l',
    current_stn_idx: 'k7wr',
    platform_num: '10',
    stn_list: {
        linestart: {
            parents: [],
            children: ['m2ot'],
            name: ['路綫左端', 'LEFT END'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [[]],
            },
            services: ['local'],
            num: '00',
            facility: '',
            secondaryName: false,
        },
        lineend: {
            parents: ['k7wr'],
            children: [],
            name: ['路綫右端', 'RIGHT END'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [[]],
            },
            services: ['local'],
            num: '14',
            facility: '',
            secondaryName: false,
        },
        l1mz: {
            parents: ['q027'],
            children: ['iwf6'],
            name: ['卡普阿瓦', 'Capuava '],
            branch: {
                left: [],
                right: [],
            },
            num: '10',
            transfer: {
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [[]],
            },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        iwf6: {
            children: ['cs6b'],
            parents: ['l1mz'],
            name: ['毛阿', 'Mauá '],
            branch: {
                left: [],
                right: [],
            },
            num: '11',
            transfer: {
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [[]],
            },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        q027: {
            parents: ['6r9r'],
            children: ['l1mz'],
            branch: {
                left: [],
                right: [],
            },
            name: ['倍耐力', 'Pirellí '],
            num: '09',
            transfer: {
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [[]],
            },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        '6r9r': {
            parents: ['u8xj'],
            children: ['q027'],
            branch: {
                left: [],
                right: [],
            },
            name: ['圣安德鲁', 'Santo André '],
            num: '08',
            transfer: {
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [[]],
            },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        u8xj: {
            parents: ['7gy7'],
            children: ['6r9r'],
            branch: {
                left: [],
                right: [],
            },
            name: ['萨拉丁市长', 'Prefeito Saladino '],
            num: '07',
            transfer: {
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [[]],
            },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        '7gy7': {
            parents: ['nnvd'],
            children: ['u8xj'],
            branch: {
                left: [],
                right: [],
            },
            name: ['乌廷加', 'Utinga '],
            num: '06',
            transfer: {
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [[]],
            },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        rr8a: {
            parents: ['fwhz'],
            children: ['nnvd'],
            branch: {
                left: [],
                right: [],
            },
            name: ['塔曼杜蒂', 'Tamanduateí '],
            num: '04',
            transfer: {
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [[['saopaulo', 'sp2', '#008061', '#fff', '2号线', 'Line 2']]],
            },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        fwhz: {
            parents: ['l116'],
            children: ['rr8a'],
            branch: {
                left: [],
                right: [],
            },
            name: ['伊皮兰加', 'Ipiranga '],
            num: '03',
            transfer: {
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [[['saopaulo', 'sp15', '#858D90', '#fff', '15号线', 'Line 15']]],
            },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        l116: {
            parents: ['m2ot'],
            children: ['fwhz'],
            branch: {
                left: [],
                right: [],
            },
            name: ['尤文图斯·穆卡', 'Juventus·Mooca '],
            num: '02',
            transfer: {
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [[]],
            },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        m2ot: {
            parents: ['linestart'],
            children: ['l116'],
            branch: {
                left: [],
                right: [],
            },
            name: ['圣布拉什', 'Brás '],
            num: '01',
            transfer: {
                tick_direc: 'r',
                paid_area: false,
                osi_names: [['罗湖', 'Luohu']],
                info: [
                    [
                        ['saopaulo', 'sp3', '#EE3E34', '#fff', '3号线', 'Line 3'],
                        ['saopaulo', 'sp7', '#9E1766', '#fff', '7号线', 'Line 7'],
                        ['saopaulo', 'sp11', '#F04D22', '#fff', '11号线', 'Line 11'],
                        ['saopaulo', 'sp12', '#083E89', '#fff', '12号线', 'Line 12'],
                        ['saopaulo', 'sp13', '#00AB5B', '#fff', '13号线', 'Line 13'],
                    ],
                    [],
                ],
            },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        nnvd: {
            name: ['南圣卡埃塔诺', 'São Caetano do Sul '],
            secondaryName: false,
            num: '05',
            services: ['local'],
            parents: ['rr8a'],
            children: ['7gy7'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        okim: {
            name: ['里贝朗皮雷斯', 'Ribeirão Pires '],
            secondaryName: false,
            num: '13',
            services: ['local'],
            parents: ['cs6b'],
            children: ['k7wr'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        cs6b: {
            name: ['瓜皮图巴', 'Guapituba '],
            secondaryName: false,
            num: '12',
            services: ['local'],
            parents: ['iwf6'],
            children: ['okim'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        k7wr: {
            name: ['瑞奥格兰德达塞拉', 'Rio Grande da Serra '],
            secondaryName: false,
            num: '14',
            services: ['local'],
            parents: ['okim'],
            children: ['lineend'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
    },
    line_name: ['10号线', 'Line 10'],
    psd_num: '23',
    line_num: '10',
    info_panel_type: 'gz1421',
    direction_gz_x: 41.16,
    direction_gz_y: 70,
    customiseMTRDest: {
        isLegacy: false,
        terminal: false,
    },
    svgWidth: {
        destination: 1050,
        runin: 1050,
        railmap: 1300,
        indoor: 1000,
    },
    notesGZMTR: [
        ['十五号线伊皮兰加站暂未开通', 'Ipiranga Station of Line 15 is under construction.', 81.5, 67.5, true],
        [
            '在圣布拉什站换乘十三号线，仅能乘坐十三号线的机场直达车',
            'For transferring to Line 13 at Brás Station is currently only Linha 13 Aeroporto Expresso available.',
            63.5,
            81,
            true,
        ],
    ],
    namePosMTR: {
        isStagger: true,
        isFlip: true,
    },
};

export default params;
