const params = {
    style: 'gzmtr',
    svg_height: 364,
    padding: 8.750201061605276,
    y_pc: 47.82,
    branch_spacing: 45,
    theme: ['saopaulo', 'sp11', '#F04D22', '#fff'],
    direction: 'l',
    current_stn_idx: '14xl',
    platform_num: '11',
    stn_list: {
        '2990': {
            name: ['塔图阿普', 'Tatuapé '],
            num: '03',
            services: ['local'],
            parents: ['l1mz'],
            children: ['o2kp'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [
                    [
                        ['saopaulo', 'sp3', '#EE3E34', '#fff', '3号线', 'Line 3'],
                        ['saopaulo', 'sp12', '#083E89', '#fff', '12号线', 'Line 12'],
                    ],
                ],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
            secondaryName: false,
        },
        '6575': {
            name: ['安东尼奥·贾内蒂·内托', 'Antonio Gianetti Neto '],
            num: '09',
            services: ['local'],
            parents: ['g0m1'],
            children: ['iblk'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
            secondaryName: false,
        },
        linestart: {
            parents: [],
            children: ['iwf6'],
            name: ['路綫右端', 'RIGHT END'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [[]],
            },
            services: ['local'],
            facility: '',
            num: '00',
            secondaryName: false,
        },
        lineend: {
            parents: ['14xl'],
            children: [],
            name: ['路綫左端', 'LEFT END'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [[]],
            },
            services: ['local'],
            facility: '',
            num: '18',
            secondaryName: false,
        },
        l1mz: {
            parents: ['iwf6'],
            children: ['2990'],
            name: ['圣布拉什', 'Brás '],
            branch: {
                left: [],
                right: [],
            },
            num: '02',
            transfer: {
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [
                    [
                        ['saopaulo', 'sp3', '#EE3E34', '#fff', '3号线', 'Line 3'],
                        ['saopaulo', 'sp7', '#9E1766', '#fff', '7号线', 'Line 7'],
                        ['saopaulo', 'sp10', '#007C8F', '#fff', '10号线', 'Line 10'],
                        ['saopaulo', 'sp12', '#083E89', '#fff', '12号线', 'Line 12'],
                        ['saopaulo', 'sp13', '#00AB5B', '#fff', '13号线', 'Line 13'],
                    ],
                ],
            },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        iwf6: {
            children: ['l1mz'],
            parents: ['linestart'],
            name: ['卢兹', 'Luz '],
            branch: {
                left: [],
                right: [],
            },
            num: '01',
            transfer: {
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [
                    [
                        ['saopaulo', 'sp1', '#0153A0', '#fff', '1号线', 'Line 1'],
                        ['saopaulo', 'sp4', '#FED304', '#000', '4号线', 'Line 4'],
                        ['saopaulo', 'sp7', '#9E1766', '#fff', '7号线', 'Line 7'],
                        ['saopaulo', 'sp13', '#00AB5B', '#fff', '13号线', 'Line 13'],
                    ],
                ],
            },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        '6dw0': {
            name: [' 波阿', 'Poá'],
            num: '11',
            services: ['local'],
            parents: ['iblk'],
            children: ['jkou'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
            secondaryName: false,
        },
        iblk: {
            name: ['费拉兹·德·瓦斯康塞洛斯', 'Ferraz de Vasconcelos '],
            num: '10',
            services: ['local'],
            parents: ['6575'],
            children: ['6dw0'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
            secondaryName: false,
        },
        g0m1: {
            name: [' 瓜亚那斯', 'Guaianases'],
            num: '08',
            services: ['local'],
            parents: ['9tlx'],
            children: ['6575'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
            secondaryName: false,
        },
        '9tlx': {
            name: [' 何塞·博尼法西奥', 'José Bonifácio'],
            num: '07',
            services: ['local'],
            parents: ['1en6'],
            children: ['g0m1'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
            secondaryName: false,
        },
        '1en6': {
            name: ['唐博斯科', 'Dom Bosco '],
            num: '06',
            services: ['local'],
            parents: ['hnoy'],
            children: ['9tlx'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
            secondaryName: false,
        },
        hnoy: {
            name: ['哥林多·伊塔奎拉', 'Corinthians·Itaquera '],
            num: '05',
            services: ['local'],
            parents: ['o2kp'],
            children: ['1en6'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[['saopaulo', 'sp3', '#EE3E34', '#fff', '3号线', 'Line 3']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
            secondaryName: false,
        },
        o2kp: {
            name: ['佩尼亚', 'Penha'],
            num: '04',
            services: ['local'],
            parents: ['2990'],
            children: ['hnoy'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [
                    [
                        ['saopaulo', 'sp2', '#008061', '#fff', '2号线', 'Line 2'],
                        ['saopaulo', 'sp3', '#EE3E34', '#fff', '3号线', 'Line 3'],
                    ],
                ],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
            secondaryName: false,
        },
        '14xl': {
            name: ['  巴西大学城', 'Estudantes'],
            secondaryName: false,
            num: '17',
            services: ['local'],
            parents: ['x63y'],
            children: ['lineend'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        x63y: {
            name: ['茂木达斯克鲁兹', 'Mogi das Cruzes '],
            secondaryName: false,
            num: '16',
            services: ['local'],
            parents: ['97yc'],
            children: ['14xl'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        '97yc': {
            name: ['布拉兹库巴斯', 'Braz Cubas '],
            secondaryName: false,
            num: '15',
            services: ['local'],
            parents: ['xd9l'],
            children: ['x63y'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        xd9l: {
            name: ['容迪亚佩巴', 'Jundiapeba '],
            secondaryName: false,
            num: '14',
            services: ['local'],
            parents: ['oi8r'],
            children: ['97yc'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        oi8r: {
            name: ['苏扎诺', 'Suzano '],
            secondaryName: false,
            num: '13',
            services: ['local'],
            parents: ['jkou'],
            children: ['xd9l'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        jkou: {
            name: ['卡尔蒙维亚纳', 'Calmon Viana '],
            secondaryName: false,
            num: '12',
            services: ['local'],
            parents: ['6dw0'],
            children: ['oi8r'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[['saopaulo', 'sp12', '#083E89', '#fff', '12号线', 'Line 12']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
    },
    line_name: ['11号线', 'Line 11'],
    psd_num: '15',
    line_num: '11',
    info_panel_type: 'gz1421',
    direction_gz_x: 41.84,
    direction_gz_y: 77.98,
    customiseMTRDest: {
        isLegacy: false,
        terminal: false,
    },
    svgWidth: {
        destination: 1000,
        runin: 1143,
        railmap: 1530,
        indoor: 1000,
    },
    notesGZMTR: [
        ['二号线佩尼亚站暂未开通', 'Penha station of Line 2 is under construction.', 82.5, 65, true],
        [
            '在圣布拉什站和卢兹站换乘十三号线，仅能乘坐十三号线的机场直达车',
            'For transferring to Line 13 at Brás Station and Luz station is currently only Linha 13 Aeroporto Expresso available.',
            61,
            80.5,
            true,
        ],
    ],
    namePosMTR: {
        isStagger: true,
        isFlip: false,
    },
};

export default params;
