const params = {
    style: 'gzmtr',
    svg_height: 370,
    padding: 8.750201061605276,
    y_pc: 50.09,
    branch_spacing: 63.18,
    theme: ['saopaulo', 'sp13', '#00AB5B', '#fff'],
    direction: 'l',
    current_stn_idx: 'iwf6',
    platform_num: '13',
    stn_list: {
        linestart: {
            parents: [],
            children: ['l1mz'],
            name: ['路綫左端', 'LEFT END'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [[]],
            },
            services: ['local'],
            facility: '',
            num: '00',
            secondaryName: false,
        },
        lineend: {
            parents: ['iwf6'],
            children: [],
            name: ['路綫右端', 'RIGHT END'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [[]],
            },
            services: ['local'],
            facility: '',
            num: '14',
            secondaryName: false,
        },
        l1mz: {
            parents: ['linestart'],
            children: ['l5s7'],
            name: ['彭美拉斯·巴拉丰达', 'Palmeiras·Barra Funda '],
            branch: {
                left: [],
                right: [],
            },
            num: '01',
            transfer: {
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [
                    [
                        ['saopaulo', 'sp3', '#EE3E34', '#fff', '3号线', 'Line 3'],
                        ['saopaulo', 'sp7', '#9E1766', '#fff', '7号线', 'Line 7'],
                        ['saopaulo', 'sp8', '#9E9E93', '#fff', '8号线', 'Line 8'],
                    ],
                    [],
                    [],
                ],
            },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        iwf6: {
            children: ['lineend'],
            parents: ['j2ts'],
            name: ['成功', 'Bonsucesso '],
            branch: {
                left: [],
                right: [],
            },
            num: '13',
            transfer: {
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [[]],
            },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        l5s7: {
            name: ['卢兹', 'Luz '],
            secondaryName: false,
            num: '02',
            services: ['local', 'express'],
            parents: ['l1mz'],
            children: ['z631'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [
                    [
                        ['saopaulo', 'sp1', '#0153A0', '#fff', '1号线', 'Line 1'],
                        ['saopaulo', 'sp4', '#FED304', '#000', '4号线', 'Line 4'],
                        ['saopaulo', 'sp7', '#9E1766', '#fff', '7号线', 'Line 7'],
                        ['saopaulo', 'sp11', '#F04D22', '#fff', '11号线', 'Line 11'],
                    ],
                ],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        z631: {
            name: ['圣布拉什', 'Brás '],
            secondaryName: false,
            num: '03',
            services: ['local', 'express'],
            parents: ['l5s7'],
            children: ['flg6'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [
                    [
                        ['saopaulo', 'sp3', '#EE3E34', '#fff', '3号线', 'Line 3'],
                        ['saopaulo', 'sp7', '#9E1766', '#fff', '7号线', 'Line 7'],
                        ['saopaulo', 'sp10', '#007C8F', '#fff', '10号线', 'Line 10'],
                        ['saopaulo', 'sp11', '#F04D22', '#fff', '11号线', 'Line 11'],
                        ['saopaulo', 'sp12', '#083E89', '#fff', '12号线', 'Line 12'],
                    ],
                ],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        flg6: {
            name: ['塔图阿普', 'Tatuapé '],
            secondaryName: false,
            num: '04',
            services: ['local'],
            parents: ['z631'],
            children: ['op34'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [
                    [
                        ['saopaulo', 'sp3', '#EE3E34', '#fff', '3号线', 'Line 3'],
                        ['saopaulo', 'sp11', '#F04D22', '#fff', '11号线', 'Line 11'],
                        ['saopaulo', 'sp12', '#083E89', '#fff', '12号线', 'Line 12'],
                    ],
                ],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        q0vm: {
            name: ['坎加尔巴', 'Cangalba '],
            secondaryName: false,
            num: '06',
            services: ['local'],
            parents: ['op34'],
            children: ['c0at'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[['saopaulo', 'sp12', '#083E89', '#fff', '12号线', 'Line 12']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        c0at: {
            name: ['技正古拉特', 'Engenheiro Goulart '],
            secondaryName: false,
            num: '07',
            services: ['local'],
            parents: ['q0vm'],
            children: ['zph2'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[['saopaulo', 'sp12', '#083E89', '#fff', '12号线', 'Line 12']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        zph2: {
            name: ['瓜鲁柳斯·切卡普', 'Guarulhos·Cecap '],
            secondaryName: false,
            num: '08',
            services: ['local', 'express'],
            parents: ['c0at'],
            children: ['0ku9'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        '0ku9': {
            name: ['瓜鲁柳斯国际机场', 'Aeroporto·Guarulhos '],
            secondaryName: false,
            num: '09',
            services: ['local', 'express'],
            parents: ['zph2'],
            children: ['jj84'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: 'airport',
        },
        jj84: {
            name: ['桉树园', 'Jardim dos Eucaliptos '],
            secondaryName: false,
            num: '10',
            services: ['local'],
            parents: ['0ku9'],
            children: ['oy89'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        oy89: {
            name: ['圣约翰', 'São João '],
            secondaryName: false,
            num: '11',
            services: ['local'],
            parents: ['jj84'],
            children: ['j2ts'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        j2ts: {
            name: ['杜特拉总统', 'Presidente Dutra '],
            secondaryName: false,
            num: '12',
            services: ['local'],
            parents: ['oy89'],
            children: ['iwf6'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        op34: {
            name: ['蒂夸提拉', 'Tiquatira '],
            secondaryName: false,
            num: '05',
            services: ['local'],
            parents: ['flg6'],
            children: ['q0vm'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [
                    [
                        ['saopaulo', 'sp2', '#008061', '#fff', '2号线', 'Line 2'],
                        ['saopaulo', 'sp12', '#083E89', '#fff', '12号线', 'Line 12'],
                    ],
                ],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
    },
    line_name: ['13号线', 'Line 13'],
    psd_num: '18',
    line_num: '13',
    info_panel_type: 'gz1421',
    direction_gz_x: 50,
    direction_gz_y: 70,
    customiseMTRDest: {
        isLegacy: false,
        terminal: false,
    },
    svgWidth: {
        destination: 1000,
        runin: 1000,
        railmap: 1510,
        indoor: 2000,
    },
    notesGZMTR: [
        [
            '西段（彭美拉斯·巴拉丰达-坎加尔巴）和东段（桉树园-成功）暂未开通',
            'West Phase (Palmeiras·Barra Funda-Cangalba) and East Phase (Jardim dos Eucaliptos-Bonsucesso) are under construction.',
            32.5,
            85,
            true,
        ],
        [
            '蒂夸提拉站暂时无法换乘2号线',
            'Transfer to Line 2 at Tiquatira station is currently unavailable.',
            74,
            84.5,
            true,
        ],
    ],
    namePosMTR: {
        isStagger: true,
        isFlip: false,
    },
};

export default params;
