const params = {
    style: 'gzmtr',
    svg_height: 310,
    padding: 3.67,
    y_pc: 46.63,
    branch_spacing: 43.65,
    theme: ['saopaulo', 'sp15', '#858D90', '#fff'],
    direction: 'l',
    current_stn_idx: 'lyqw',
    platform_num: '15',
    stn_list: {
        linestart: {
            parents: [],
            children: ['ny2q'],
            name: ['路綫左端', 'LEFT END'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [[]],
            },
            services: ['local'],
            facility: '',
            num: '00',
            secondaryName: false,
        },
        lineend: {
            parents: ['7e3x'],
            children: [],
            name: ['路綫右端', 'RIGHT END'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [[]],
            },
            services: ['local'],
            facility: '',
            num: '18',
            secondaryName: false,
        },
        l1mz: {
            parents: ['iwf6'],
            children: ['lyqw'],
            name: ['黄麻农场', 'Fazenda da Juta '],
            branch: {
                left: [],
                right: [],
            },
            num: '10',
            transfer: {
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [[]],
            },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        iwf6: {
            children: ['l1mz'],
            parents: ['0gcd'],
            name: ['萨波彭巴', 'Sapopemba '],
            branch: {
                left: [],
                right: [],
            },
            num: '09',
            transfer: {
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [[]],
            },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        ei9t: {
            parents: ['qbbb'],
            children: ['7e3x'],
            branch: {
                left: [],
                right: [],
            },
            name: ['蒂拉登特斯城', 'Cidade Tiradentes '],
            num: '17',
            services: ['local'],
            facility: '',
            transfer: {
                info: [[]],
                osi_names: [],
                paid_area: true,
                tick_direc: 'r',
            },
            secondaryName: false,
        },
        qbbb: {
            parents: ['tgp4'],
            children: ['ei9t'],
            branch: {
                left: [],
                right: [],
            },
            name: ['马西奥·贝克', 'Marcio Beck '],
            num: '16',
            services: ['local'],
            facility: '',
            transfer: {
                info: [[]],
                osi_names: [],
                paid_area: true,
                tick_direc: 'r',
            },
            secondaryName: false,
        },
        tgp4: {
            parents: ['su3g'],
            children: ['qbbb'],
            branch: {
                left: [],
                right: [],
            },
            name: ['艾瑞克·塞默', 'Erico Semmer '],
            num: '15',
            services: ['local'],
            facility: '',
            transfer: {
                info: [[]],
                osi_names: [],
                paid_area: true,
                tick_direc: 'r',
            },
            secondaryName: false,
        },
        su3g: {
            parents: ['dre1'],
            children: ['tgp4'],
            branch: {
                left: [],
                right: [],
            },
            name: ['贾库桃', 'Jacu Pêssego '],
            num: '14',
            services: ['local'],
            facility: '',
            transfer: {
                info: [[]],
                osi_names: [],
                paid_area: true,
                tick_direc: 'r',
            },
            secondaryName: false,
        },
        dre1: {
            parents: ['9v64'],
            children: ['su3g'],
            branch: {
                left: [],
                right: [],
            },
            name: ['希冀', 'Boa Esperança '],
            num: '13',
            services: ['local'],
            facility: '',
            transfer: {
                info: [[]],
                osi_names: [],
                paid_area: true,
                tick_direc: 'r',
            },
            secondaryName: false,
        },
        '9v64': {
            parents: ['lyqw'],
            children: ['dre1'],
            branch: {
                left: [],
                right: [],
            },
            name: ['克罗尼尔花园', 'Jardim Colonial '],
            num: '12',
            services: ['local'],
            facility: '',
            transfer: {
                info: [[]],
                osi_names: [],
                paid_area: true,
                tick_direc: 'r',
            },
            secondaryName: false,
        },
        lyqw: {
            parents: ['l1mz'],
            children: ['9v64'],
            branch: {
                left: [],
                right: [],
            },
            name: ['圣马修斯', 'São Mateus '],
            num: '11',
            services: ['local'],
            facility: '',
            transfer: {
                info: [[]],
                osi_names: [],
                paid_area: true,
                tick_direc: 'r',
            },
            secondaryName: false,
        },
        '0gcd': {
            name: ['高原花园', 'Jd. Planalto '],
            secondaryName: false,
            num: '08',
            services: ['local'],
            parents: ['svlx'],
            children: ['iwf6'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        svlx: {
            name: ['联合城', 'Vila União '],
            secondaryName: false,
            num: '07',
            services: ['local'],
            parents: ['s08h'],
            children: ['0gcd'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        s08h: {
            name: ['托尔斯泰镇', 'Vila Tolstói '],
            secondaryName: false,
            num: '06',
            services: ['local'],
            parents: ['ojvh'],
            children: ['svlx'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        ojvh: {
            name: ['卡米洛·哈达德', 'Camilo Haddad '],
            secondaryName: false,
            num: '05',
            services: ['local'],
            parents: ['naqs'],
            children: ['s08h'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        naqs: {
            name: ['圣卢卡斯', 'São Lucas '],
            secondaryName: false,
            num: '04',
            services: ['local'],
            parents: ['epll'],
            children: ['ojvh'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        epll: {
            name: ['欧拉托瑞尔', 'Oratório'],
            secondaryName: false,
            num: '03',
            services: ['local'],
            parents: ['9uzg'],
            children: ['naqs'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        '9uzg': {
            name: ['普鲁登特镇', 'Vila Prudente '],
            secondaryName: false,
            num: '02',
            services: ['local'],
            parents: ['ny2q'],
            children: ['epll'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[['saopaulo', 'sp2', '#008061', '#fff', '2号线', 'Line 2']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        ny2q: {
            name: ['伊皮兰加', 'Ipiranga '],
            secondaryName: false,
            num: '01',
            services: ['local'],
            parents: ['linestart'],
            children: ['9uzg'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[['saopaulo', 'sp10', '#007C8F', '#fff', '10号线', 'Line 10']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        '7e3x': {
            name: ['蒂拉登特斯市医院', 'Hospital Cidade Tiradentes '],
            secondaryName: false,
            num: '18',
            services: ['local'],
            parents: ['ei9t'],
            children: ['lineend'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
    },
    line_name: ['15号线', 'Line 15'],
    psd_num: '18',
    line_num: '15',
    info_panel_type: 'gz1421',
    direction_gz_x: 21.28,
    direction_gz_y: 79.02,
    customiseMTRDest: {
        isLegacy: false,
        terminal: false,
    },
    svgWidth: {
        destination: 1000,
        runin: 1000,
        railmap: 1500,
        indoor: 1000,
    },
    notesGZMTR: [
        [
            '伊皮兰加站和东段（克罗尼尔花园-蒂拉登特斯市医院）未开通。',
            'Ipiranga station and East Phase (Jardim Colonial-Hospital Cidade Tiradentes) are under construction.',
            63,
            75,
            true,
        ],
    ],
    namePosMTR: {
        isStagger: true,
        isFlip: false,
    },
};

export default params;
