const params = {
    style: 'gzmtr',
    svg_height: 311,
    padding: 8.750201061605276,
    y_pc: 47.22,
    branch_spacing: 45,
    theme: ['saopaulo', 'sp4', '#FED304', '#000'],
    direction: 'l',
    current_stn_idx: 'iwf6',
    platform_num: '4',
    stn_list: {
        '2990': {
            name: ['根诺波利斯·麦肯齐', 'Higienópolis· Mackenzie '],
            num: '09',
            services: ['local'],
            parents: ['o2kp'],
            children: ['l1mz'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[['saopaulo', 'sp6', '#F27C00', '#fff', '6号线', 'Line 6']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
            secondaryName: false,
        },
        '6575': {
            name: ['布坦坦', 'Butantã'],
            num: '03',
            services: ['local'],
            parents: ['iblk'],
            children: ['g0m1'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
            secondaryName: false,
        },
        linestart: {
            parents: [],
            children: ['6dw0'],
            name: ['路綫左端', 'LEFT END'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [[]],
            },
            services: ['local'],
            facility: '',
            num: '00',
            secondaryName: false,
        },
        lineend: {
            parents: ['iwf6'],
            children: [],
            name: ['路綫右端', 'RIGHT END'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [[]],
            },
            services: ['local'],
            facility: '',
            num: '00',
            secondaryName: false,
        },
        l1mz: {
            parents: ['2990'],
            children: ['iwf6'],
            name: ['共和国', 'República '],
            branch: {
                left: [],
                right: [],
            },
            num: '10',
            transfer: {
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [[['saopaulo', 'sp3', '#EE3E34', '#fff', '3号线', 'Line 3']]],
            },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        iwf6: {
            children: ['lineend'],
            parents: ['l1mz'],
            name: ['卢兹', 'Luz '],
            branch: {
                left: [],
                right: [],
            },
            num: '11',
            transfer: {
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [
                    [
                        ['saopaulo', 'sp1', '#0153A0', '#fff', '1号线', 'Line 1'],
                        ['saopaulo', 'sp7', '#9E1766', '#fff', '7号线', 'Line 7'],
                        ['saopaulo', 'sp11', '#F04D22', '#fff', '11号线', 'Line 1'],
                        ['saopaulo', 'sp13', '#00AB5B', '#fff', '13号线', 'Line 13'],
                    ],
                ],
            },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        '6dw0': {
            name: ['索尼亚城', 'Vila Sônia '],
            num: '01',
            services: ['local'],
            parents: ['linestart'],
            children: ['iblk'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
            secondaryName: false,
        },
        iblk: {
            name: ['圣保罗-莫伦比', 'São Paulo·Morumbi '],
            num: '02',
            services: ['local'],
            parents: ['6dw0'],
            children: ['6575'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
            secondaryName: false,
        },
        g0m1: {
            name: ['松树', 'Pinheiros '],
            num: '04',
            services: ['local'],
            parents: ['6575'],
            children: ['9tlx'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[['saopaulo', 'sp9', '#00A78E', '#fff', '9号线', 'Line 9']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
            secondaryName: false,
        },
        '9tlx': {
            name: ['法利亚利马', 'Faria Lima '],
            num: '05',
            services: ['local'],
            parents: ['g0m1'],
            children: ['1en6'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
            secondaryName: false,
        },
        '1en6': {
            name: ['弗拉迪克·库蒂尼奥', 'Fradique Coutinho '],
            num: '06',
            services: ['local'],
            parents: ['9tlx'],
            children: ['hnoy'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
            secondaryName: false,
        },
        hnoy: {
            name: ['奥斯卡·弗莱雷', 'Oscar Freire '],
            num: '07',
            services: ['local'],
            parents: ['1en6'],
            children: ['o2kp'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
            secondaryName: false,
        },
        o2kp: {
            name: ['保利斯塔', 'Paulista '],
            num: '08',
            services: ['local'],
            parents: ['hnoy'],
            children: ['2990'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[['saopaulo', 'sp2', '#008061', '#fff', '2号线', 'Line 2']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
            secondaryName: false,
        },
    },
    line_name: ['4号线', 'Line 4'],
    psd_num: '5',
    line_num: '4',
    info_panel_type: 'gz1421',
    direction_gz_x: 41.84,
    direction_gz_y: 77.98,
    customiseMTRDest: {
        isLegacy: false,
        terminal: false,
    },
    svgWidth: {
        destination: 1000,
        runin: 1143,
        railmap: 1143,
        indoor: 1000,
    },
    notesGZMTR: [['六号线和十三号线暂未开通', 'Line 6 and Line 13 are under construction.', 4.5, 78, true]],
    namePosMTR: {
        isStagger: true,
        isFlip: false,
    },
};

export default params;
