const params = {
    style: 'gzmtr',
    svg_height: 311,
    padding: 4.20352796096724,
    y_pc: 51.39,
    branch_spacing: 45,
    theme: ['saopaulo', 'sp5', '#784D9F', '#fff'],
    direction: 'l',
    current_stn_idx: 'l1mz',
    platform_num: '5',
    stn_list: {
        linestart: {
            parents: [],
            children: ['qvhm'],
            name: ['路綫左端', 'LEFT END'],
            branch: {
                left: [],
                right: [],
            },
            num: '00',
            transfer: {
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [[]],
            },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        lineend: {
            parents: ['l1mz'],
            children: [],
            name: ['路綫右端', 'RIGHT END'],
            branch: {
                left: [],
                right: [],
            },
            num: '18',
            transfer: {
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [[]],
            },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        l1mz: {
            parents: ['f9r3'],
            children: ['lineend'],
            name: ['查卡拉·卡拉宾', 'Chácara Klabin '],
            branch: {
                left: [],
                right: [],
            },
            num: '17',
            transfer: {
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [[['saopaulo', 'sp2', '#008061', '#fff', '2号线', 'Line  2']]],
            },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        '7ut6': {
            branch: {
                left: [],
                right: [],
            },
            parents: ['vsdm'],
            children: ['f9r3'],
            name: ['圣保罗医院', 'Hospital São Paulo '],
            num: '15',
            transfer: {
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [[]],
            },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        f9r3: {
            branch: {
                left: [],
                right: [],
            },
            parents: ['7ut6'],
            children: ['l1mz'],
            name: ['圣克鲁斯', 'Santa Cruz '],
            num: '16',
            transfer: {
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [[]],
            },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        vsdm: {
            branch: {
                left: [],
                right: [],
            },
            parents: ['i1bw'],
            children: ['7ut6'],
            name: ['AACD服务站', 'AACD·Servidor '],
            num: '14',
            transfer: {
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [[]],
            },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        i1bw: {
            branch: {
                left: [],
                right: [],
            },
            parents: ['xe64'],
            children: ['vsdm'],
            name: ['莫玛', 'Moema '],
            num: '13',
            transfer: {
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [[]],
            },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        xe64: {
            branch: {
                left: [],
                right: [],
            },
            parents: ['9yva'],
            children: ['i1bw'],
            name: ['桉树', 'Eucaliptos '],
            num: '12',
            transfer: {
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [[]],
            },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        '9yva': {
            branch: {
                left: [],
                right: [],
            },
            parents: ['pdpl'],
            children: ['xe64'],
            name: ['丽田园', 'Campo Belo'],
            num: '11',
            transfer: {
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [[]],
            },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        pdpl: {
            branch: {
                left: [],
                right: [],
            },
            parents: ['d157'],
            children: ['9yva'],
            name: ['布鲁克林', 'Brooklin '],
            num: '10',
            transfer: {
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [[]],
            },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        d157: {
            branch: {
                left: [],
                right: [],
            },
            parents: ['4oo6'],
            children: ['pdpl'],
            name: ['泊尔巴加托', 'Borba Gato'],
            num: '09',
            transfer: {
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [[]],
            },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        '4oo6': {
            branch: {
                left: [],
                right: [],
            },
            parents: ['ocmo'],
            children: ['d157'],
            name: ['阿尔图达博阿维斯塔', 'Alto da Boa Vista '],
            num: '08',
            transfer: {
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [[]],
            },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        ocmo: {
            branch: {
                left: [],
                right: [],
            },
            parents: ['ggt8'],
            children: ['4oo6'],
            name: ['阿道弗·皮涅罗', 'Adolfo Pinheiro '],
            num: '07',
            transfer: {
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [[]],
            },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        ggt8: {
            branch: {
                left: [],
                right: [],
            },
            parents: ['ttr8'],
            children: ['ocmo'],
            name: ['十三广', 'Largo Treze '],
            num: '06',
            transfer: {
                tick_direc: 'r',
                paid_area: true,
                osi_names: [['香港', 'Hong Kong']],
                info: [[], []],
            },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        ttr8: {
            branch: {
                left: [],
                right: [],
            },
            parents: ['eats'],
            children: ['ggt8'],
            name: ['圣阿马罗', 'Santo Amaro '],
            num: '05',
            transfer: {
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [[['saopaulo', 'sp9', '#00A78E', '#fff', '9号线', 'Line  9']]],
            },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        eats: {
            branch: {
                left: [],
                right: [],
            },
            parents: ['9y92'],
            children: ['ttr8'],
            name: [' 乔瓦尼·格龙奇', 'Giovanni Gronchi'],
            num: '04',
            transfer: {
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [[]],
            },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        q0jw: {
            branch: {
                left: [],
                right: [],
            },
            parents: ['qvhm'],
            children: ['9y92'],
            name: ['净地', 'Campo Limpo '],
            num: '02',
            transfer: {
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [[]],
            },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        qvhm: {
            branch: {
                left: [],
                right: [],
            },
            parents: ['linestart'],
            children: ['q0jw'],
            name: ['雷顿多角', 'Capão Redondo '],
            num: '01',
            transfer: {
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [[]],
            },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        '9y92': {
            name: [' 美丽村', 'Vila das Belezas'],
            secondaryName: false,
            num: '03',
            services: ['local'],
            parents: ['q0jw'],
            children: ['eats'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
    },
    line_name: ['5号线', 'Line  5'],
    psd_num: '14',
    line_num: '5',
    info_panel_type: 'gz1421',
    direction_gz_x: 50,
    direction_gz_y: 75.2,
    customiseMTRDest: {
        isLegacy: false,
        terminal: false,
    },
    svgWidth: {
        destination: 1000,
        runin: 1000,
        railmap: 1351,
        indoor: 1200,
    },
    notesGZMTR: [],
    namePosMTR: {
        isStagger: true,
        isFlip: false,
    },
};

export default params;
