const params = {
    style: 'gzmtr',
    svg_height: 330,
    padding: 5.353925353925354,
    y_pc: 47.82,
    branch_spacing: 47.82,
    theme: ['saopaulo', 'sp8', '#9E9E93', '#fff'],
    direction: 'l',
    current_stn_idx: 'l116',
    platform_num: '8',
    stn_list: {
        linestart: {
            parents: [],
            children: ['fuhb'],
            name: ['路綫右端', 'RIGHT END'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [[]],
            },
            services: ['local'],
            num: '00',
            facility: '',
            secondaryName: false,
        },
        lineend: {
            parents: ['l116'],
            children: [],
            name: ['路綫左端', 'LEFT END'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [[]],
            },
            services: ['local'],
            num: '23',
            facility: '',
            secondaryName: false,
        },
        l1mz: {
            parents: ['iwf6'],
            children: ['q027'],
            name: ['奎托纳', 'Quitaúna'],
            branch: {
                left: [],
                right: [],
            },
            num: '14',
            transfer: {
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [[]],
            },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        iwf6: {
            children: ['l1mz'],
            parents: ['cs6b'],
            name: ['米格尔·科斯塔将军', ' Gen. Miguel Costa '],
            branch: {
                left: [],
                right: [],
            },
            num: '13',
            transfer: {
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [[]],
            },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        q027: {
            parents: ['l1mz'],
            children: ['6r9r'],
            branch: {
                left: [],
                right: [],
            },
            name: [' 桑帕约', 'Com. Sampaio'],
            num: '15',
            transfer: {
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [[]],
            },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        '6r9r': {
            parents: ['q027'],
            children: ['u8xj'],
            branch: {
                left: [],
                right: [],
            },
            name: [' 奥萨斯库', 'Osasco'],
            num: '16',
            transfer: {
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [[['saopaulo', 'sp9', '#00A78E', '#fff', '9号线', 'Line 9']]],
            },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        u8xj: {
            parents: ['6r9r'],
            children: ['7gy7'],
            branch: {
                left: [],
                right: [],
            },
            name: [' 阿尔蒂诺总统', 'Pres. Altino'],
            num: '17',
            transfer: {
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [[['saopaulo', 'sp9', '#00A78E', '#fff', '9号线', 'Line 9']]],
            },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        '7gy7': {
            parents: ['u8xj'],
            children: ['nnvd'],
            branch: {
                left: [],
                right: [],
            },
            name: [' 利奥波丁皇后', 'Imperatriz  Leopoldina'],
            num: '18',
            transfer: {
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [[]],
            },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        rr8a: {
            parents: ['nnvd'],
            children: ['fwhz'],
            branch: {
                left: [],
                right: [],
            },
            name: [' 拉帕', 'Lapa'],
            num: '20',
            transfer: {
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [[['saopaulo', 'sp7', '#9E1766', '#fff', '7号线', 'Line 7']]],
            },
            services: ['local'],
            facility: '',
            secondaryName: ['出站换乘', 'Exit station before transfer'],
        },
        fwhz: {
            parents: ['rr8a'],
            children: ['l116'],
            branch: {
                left: [],
                right: [],
            },
            name: [' 彭美拉斯·巴拉丰达', 'Palmeiras·Barra Funda'],
            num: '21',
            transfer: {
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [
                    [
                        ['saopaulo', 'sp3', '#EE3E34', '#fff', '3号线', 'Line 3'],
                        ['saopaulo', 'sp7', '#9E1766', '#fff', '7号线', 'Line 7'],
                        ['saopaulo', 'sp13', '#00AB5B', '#fff', '13号线', 'Line 13'],
                    ],
                ],
            },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        l116: {
            parents: ['fwhz'],
            children: ['lineend'],
            branch: {
                left: [],
                right: [],
            },
            name: ['普列斯特斯', 'Júlio Prestes '],
            num: '22',
            transfer: {
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [[]],
            },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        nnvd: {
            name: ['多明戈斯·德·莫拉斯', 'Domingos  de Moraes '],
            secondaryName: false,
            num: '19',
            services: ['local'],
            parents: ['7gy7'],
            children: ['rr8a'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        okim: {
            name: ['圣特雷莎', ' Santa Terezinha '],
            secondaryName: false,
            num: '11',
            services: ['local'],
            parents: ['k7wr'],
            children: ['cs6b'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        cs6b: {
            name: ['卡拉皮库巴', 'Carapicuíba'],
            secondaryName: false,
            num: '12',
            services: ['local'],
            parents: ['okim'],
            children: ['iwf6'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        k7wr: {
            name: [' 安东尼奥·若昂', 'Antonio João'],
            secondaryName: false,
            num: '10',
            services: ['local'],
            parents: ['h60o'],
            children: ['okim'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        reyy: {
            name: ['伊塔佩维', 'Itapevi '],
            secondaryName: false,
            num: '03',
            services: ['local'],
            parents: ['kn2b'],
            children: ['qcae'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        qcae: {
            name: [' 技正卡多索', 'Engenheiro Cardoso'],
            secondaryName: false,
            num: '04',
            services: ['local'],
            parents: ['reyy'],
            children: ['r4n5'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        r4n5: {
            name: [' 圣心', 'Sagrado Coração'],
            secondaryName: false,
            num: '05',
            services: ['local'],
            parents: ['qcae'],
            children: ['f52v'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        f52v: {
            name: [' 詹迪拉', 'Jandira'],
            secondaryName: false,
            num: '06',
            services: ['local'],
            parents: ['r4n5'],
            children: ['hl50'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        hl50: {
            name: [' 西尔维拉花园', 'Jardim Silveira'],
            secondaryName: false,
            num: '07',
            services: ['local'],
            parents: ['f52v'],
            children: ['tj68'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        tj68: {
            name: ['贝尔瓦尔花园', 'Jardim Belval '],
            secondaryName: false,
            num: '08',
            services: ['local'],
            parents: ['hl50'],
            children: ['h60o'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        h60o: {
            name: [' 巴鲁埃里', 'Barueri'],
            secondaryName: false,
            num: '09',
            services: ['local'],
            parents: ['tj68'],
            children: ['k7wr'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        fuhb: {
            name: [' 阿马多尔布埃诺', 'Amador Bueno'],
            secondaryName: false,
            num: '01',
            services: ['local'],
            parents: ['linestart'],
            children: ['kn2b'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        kn2b: {
            name: [' 圣丽塔', 'Santa Rita'],
            secondaryName: false,
            num: '02',
            services: ['local'],
            parents: ['fuhb'],
            children: ['reyy'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
    },
    line_name: ['8号线', 'Line 8'],
    psd_num: '10',
    line_num: '8',
    info_panel_type: 'gz1421',
    direction_gz_x: 35.8,
    direction_gz_y: 70,
    customiseMTRDest: {
        isLegacy: false,
        terminal: false,
    },
    svgWidth: {
        destination: 1050,
        runin: 1305,
        railmap: 1313,
        indoor: 1000,
    },
    notesGZMTR: [
        [
            '十三号线彭美拉斯·巴拉丰达站暂未开通',
            'Palmeiras·Barra Funda Station of Line 13 is under construction.',
            6.5,
            79,
            true,
        ],
    ],
    namePosMTR: {
        isStagger: true,
        isFlip: true,
    },
};

export default params;
