const params = {
    style: 'gzmtr',
    svg_height: 321,
    padding: 8.750201061605276,
    y_pc: 46.63,
    branch_spacing: 45,
    theme: ['saopaulo', 'sp9', '#00A78E', '#fff'],
    direction: 'l',
    current_stn_idx: 'q6ov',
    platform_num: '9',
    stn_list: {
        linestart: {
            parents: [],
            children: ['ei9t'],
            name: ['路綫右端', 'RIGHT END'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [[]],
            },
            services: ['local'],
            facility: '',
            num: '00',
            secondaryName: false,
        },
        lineend: {
            parents: ['pzrt'],
            children: [],
            name: ['路綫左端', 'LEFT END'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [[]],
            },
            services: ['local'],
            facility: '',
            num: '22',
            secondaryName: false,
        },
        l1mz: {
            parents: ['lyqw'],
            children: ['iwf6'],
            name: [' 花园城', 'Cidade Jardim'],
            branch: {
                left: [],
                right: [],
            },
            num: '08',
            transfer: {
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [[]],
            },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        iwf6: {
            children: ['0gcd'],
            parents: ['l1mz'],
            name: ['奥林匹亚村', 'Vila Olímpia '],
            branch: {
                left: [],
                right: [],
            },
            num: '09',
            transfer: {
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [[]],
            },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        ei9t: {
            parents: ['linestart'],
            children: ['qbbb'],
            branch: {
                left: [],
                right: [],
            },
            name: ['奥萨斯库', 'Osasco '],
            num: '01',
            services: ['local'],
            facility: '',
            transfer: {
                info: [[['saopaulo', 'sp8', '#9E9E93', '#fff', '8号线', 'Line 8']]],
                osi_names: [],
                paid_area: true,
                tick_direc: 'r',
            },
            secondaryName: false,
        },
        qbbb: {
            parents: ['ei9t'],
            children: ['tgp4'],
            branch: {
                left: [],
                right: [],
            },
            name: ['阿尔蒂诺总统', 'Pres. Altino '],
            num: '02',
            services: ['local'],
            facility: '',
            transfer: {
                info: [[['saopaulo', 'sp8', '#9E9E93', '#fff', '8号线', 'Line 8']]],
                osi_names: [],
                paid_area: true,
                tick_direc: 'r',
            },
            secondaryName: false,
        },
        tgp4: {
            parents: ['qbbb'],
            children: ['su3g'],
            branch: {
                left: [],
                right: [],
            },
            name: ['凯撒', 'Ceasa '],
            num: '03',
            services: ['local'],
            facility: '',
            transfer: {
                info: [[]],
                osi_names: [],
                paid_area: true,
                tick_direc: 'r',
            },
            secondaryName: false,
        },
        su3g: {
            parents: ['tgp4'],
            children: ['dre1'],
            branch: {
                left: [],
                right: [],
            },
            name: ['罗伯斯雅达利镇', 'Vila·Lobos·Jaguaré '],
            num: '04',
            services: ['local'],
            facility: '',
            transfer: {
                info: [[]],
                osi_names: [],
                paid_area: true,
                tick_direc: 'r',
            },
            secondaryName: false,
        },
        dre1: {
            parents: ['su3g'],
            children: ['9v64'],
            branch: {
                left: [],
                right: [],
            },
            name: [' 大学城', 'Cidade Universitária'],
            num: '05',
            services: ['local'],
            facility: '',
            transfer: {
                info: [[]],
                osi_names: [],
                paid_area: true,
                tick_direc: 'r',
            },
            secondaryName: false,
        },
        '9v64': {
            parents: ['dre1'],
            children: ['lyqw'],
            branch: {
                left: [],
                right: [],
            },
            name: ['松树', 'Pinheiros '],
            num: '06',
            services: ['local'],
            facility: '',
            transfer: {
                info: [[['saopaulo', 'sp4', '#FED304', '#000', '4号线', 'Line 4']]],
                osi_names: [],
                paid_area: true,
                tick_direc: 'r',
            },
            secondaryName: false,
        },
        lyqw: {
            parents: ['9v64'],
            children: ['l1mz'],
            branch: {
                left: [],
                right: [],
            },
            name: [' 希伯来·雷布萨斯', 'Hebraica·Rebouças'],
            num: '07',
            services: ['local'],
            facility: '',
            transfer: {
                info: [[]],
                osi_names: [],
                paid_area: true,
                tick_direc: 'r',
            },
            secondaryName: false,
        },
        '0gcd': {
            name: ['贝里尼', 'Berrini '],
            secondaryName: false,
            num: '10',
            services: ['local'],
            parents: ['iwf6'],
            children: ['svlx'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        svlx: {
            name: ['莫伦比', 'Morumbi '],
            secondaryName: false,
            num: '11',
            services: ['local'],
            parents: ['0gcd'],
            children: ['s08h'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        s08h: {
            name: ['格兰奇朱丽叶', 'Granja Julieta '],
            secondaryName: false,
            num: '12',
            services: ['local'],
            parents: ['svlx'],
            children: ['ojvh'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        ojvh: {
            name: ['约翰·迪亚斯', 'João Dias '],
            secondaryName: false,
            num: '13',
            services: ['local'],
            parents: ['s08h'],
            children: ['naqs'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        naqs: {
            name: ['圣阿马罗', 'Santo Amaro '],
            secondaryName: false,
            num: '14',
            services: ['local'],
            parents: ['ojvh'],
            children: ['epll'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[['saopaulo', 'sp5', '#784D9F', '#fff', '5号线', 'Line 5']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        epll: {
            name: [' 索科洛', 'Socorro'],
            secondaryName: false,
            num: '15',
            services: ['local'],
            parents: ['naqs'],
            children: ['9uzg'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        '9uzg': {
            name: ['朱鲁巴图巴', 'Jurubatuba '],
            secondaryName: false,
            num: '16',
            services: ['local'],
            parents: ['epll'],
            children: ['ny2q'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        ny2q: {
            name: ['赛车场', 'Autódromo'],
            secondaryName: false,
            num: '17',
            services: ['local'],
            parents: ['9uzg'],
            children: ['stvr'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        pzrt: {
            name: [' 瓦尔任阿', 'Varginha'],
            secondaryName: ['建设中', 'u./c.'],
            num: '21',
            services: ['local'],
            parents: ['q6ov'],
            children: ['lineend'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        q6ov: {
            name: ['门德斯·维拉纳塔尔', 'Mendes·Vila Natal '],
            secondaryName: false,
            num: '20',
            services: ['local'],
            parents: ['4pd7'],
            children: ['pzrt'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        '4pd7': {
            name: ['格拉雅乌', 'Grajaú '],
            secondaryName: false,
            num: '19',
            services: ['local'],
            parents: ['stvr'],
            children: ['q6ov'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        stvr: {
            name: ['春日·英特拉格斯', 'Primavera·Interlagos '],
            secondaryName: false,
            num: '18',
            services: ['local'],
            parents: ['ny2q'],
            children: ['4pd7'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
    },
    line_name: ['9号线', 'Line 9'],
    psd_num: '13',
    line_num: '9',
    info_panel_type: 'gz1421',
    direction_gz_x: 21.28,
    direction_gz_y: 79.02,
    customiseMTRDest: {
        isLegacy: false,
        terminal: false,
    },
    svgWidth: {
        destination: 1000,
        runin: 1411,
        railmap: 1510,
        indoor: 1000,
    },
    notesGZMTR: [],
    namePosMTR: {
        isStagger: true,
        isFlip: false,
    },
};

export default params;
