const param = {
    style: 'shmetro',
    svg_height: 400,
    padding: 3.67,
    y_pc: 40,
    branch_spacing: 45,
    theme: ['shanghai', 'sh14', '#827A04', '#fff'],
    direction: 'l',
    current_stn_idx: 'qnbj',
    platform_num: false,
    stn_list: {
        linestart: {
            parents: [],
            children: ['9cyo'],
            name: ['路綫左端', 'LEFT END'],
            branch: { left: [], right: [] },
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            num: '00',
            facility: '',
            secondaryName: false,
        },
        lineend: {
            parents: ['n31j'],
            children: [],
            name: ['路綫右端', 'RIGHT END'],
            branch: { left: [], right: [] },
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            num: '00',
            facility: '',
            secondaryName: false,
        },
        l1mz: {
            parents: ['qzjx'],
            children: ['iwf6'],
            name: ['黄杨路', 'Huangyang Road'],
            branch: { left: [], right: [] },
            num: '02',
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        iwf6: {
            children: ['5xa7'],
            parents: ['l1mz'],
            name: ['云顺路', 'Yunshun Road'],
            branch: { left: [], right: [] },
            num: '01',
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        jsat: {
            parents: ['x9gu'],
            children: ['qzjx'],
            branch: { left: [], right: [] },
            name: ['云山路', 'Yunshan Road'],
            num: '00',
            transfer: {
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [[['shanghai', 'sh6', '#D9027D', '#fff', '6号线', 'Line 6']]],
            },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        x9gu: {
            parents: ['k9k5'],
            children: ['jsat'],
            branch: { left: [], right: [] },
            name: ['歇浦路', 'Xiepu Road'],
            num: '00',
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        k9k5: {
            parents: ['j2kn'],
            children: ['x9gu'],
            branch: { left: [], right: [] },
            name: ['昌邑路', 'Changyi Road'],
            num: '00',
            services: ['local'],
            transfer: {
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [[['shanghai', 'sh18', '#D6A461', '#000', '18号线', 'Line 18']]],
            },
            facility: '',
            secondaryName: false,
        },
        j2kn: {
            parents: ['lcgp'],
            children: ['k9k5'],
            branch: { left: [], right: [] },
            name: ['源深路', 'Yuanshen Road'],
            num: '00',
            services: ['local'],
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            facility: '',
            secondaryName: false,
        },
        kaxg: {
            parents: ['7x7k'],
            children: ['wbtv'],
            branch: { left: [], right: [] },
            name: ['大世界', 'Dashijie'],
            num: '00',
            services: ['local'],
            transfer: {
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [[['shanghai', 'sh8', '#00a3e0', '#fff', '8号线', 'Line 8']]],
            },
            facility: '',
            secondaryName: false,
        },
        sd6y: {
            parents: ['1fdr'],
            children: ['qnbj'],
            branch: { left: [], right: [] },
            name: ['武定路', 'Wuding Road'],
            num: '00',
            services: ['local'],
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [['車站名', 'Stn Name']], info: [[], []] },
            facility: '',
            secondaryName: false,
        },
        '9cyo': {
            parents: ['linestart'],
            children: ['8hte'],
            branch: { left: [], right: [] },
            name: ['封浜', 'Fengbang'],
            num: '00',
            services: ['local'],
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            facility: '',
            secondaryName: false,
        },
        hhar: {
            children: ['qgae'],
            parents: ['nhrh'],
            branch: { left: [], right: [] },
            name: ['真新新村', 'Zhenxin Xincun'],
            num: '00',
            services: ['local'],
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            facility: '',
            secondaryName: false,
        },
        jjh7: {
            children: ['h3vs'],
            parents: ['wbtv'],
            branch: { left: [], right: [] },
            name: ['陆家嘴', 'Lujiazui'],
            num: '00',
            services: ['local'],
            transfer: {
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [[['shanghai', 'sh2', '#97D700', '#000', '2号线', 'Line']]],
            },
            facility: '',
            secondaryName: false,
        },
        '7x7k': {
            children: ['kaxg'],
            parents: ['qnbj'],
            branch: { left: [], right: [] },
            name: ['一大会址·黄陂南路', 'Site of the First CPC National\\Congress · South Huangpi Road'],
            num: '00',
            services: ['local'],
            transfer: {
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [[['shanghai', 'sh1', '#E4002B', '#fff', '1号线', 'Line 1']]],
            },
            facility: '',
            secondaryName: false,
        },
        qnbj: {
            name: ['静安寺', "Jing'an Temple"],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['sd6y'],
            children: ['7x7k'],
            branch: { left: [], right: [] },
            transfer: {
                info: [
                    [
                        ['shanghai', 'sh2', '#97D700', '#000', '2号线', 'Line'],
                        ['shanghai', 'sh7', '#FF6900', '#000', '7号线', 'Line 7'],
                    ],
                ],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        '1fdr': {
            name: ['武宁路', 'Wuning Road'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['wai3'],
            children: ['sd6y'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['shanghai', 'sh13', '#EF95CF', '#000', '13号线', 'Line 13']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        lcgp: {
            name: ['浦东大道', 'Pudong Avenue'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['h3vs'],
            children: ['j2kn'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['shanghai', 'sh4', '#5F259F', '#fff', '4号线', 'Line 4']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        wbtv: {
            name: ['豫园', 'Yuyuan Garden'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['kaxg'],
            children: ['jjh7'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['shanghai', 'sh10', '#c1a7e2', '#000', '10号线', 'Line 10']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        wai3: {
            name: ['曹杨路', 'Caoyang Road'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['naz0'],
            children: ['1fdr'],
            branch: { left: [], right: [] },
            transfer: {
                info: [
                    [],
                    [
                        ['shanghai', 'sh3', '#FFD100', '#000', '3号线', 'Line 3'],
                        ['shanghai', 'sh4', '#5F259F', '#fff', '4号线', 'Line 4'],
                        ['shanghai', 'sh11', '#76232F', '#fff', '11号线', 'Line 11'],
                    ],
                ],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        naz0: {
            name: ['中宁路', 'Zhongning Road'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['y6id'],
            children: ['wai3'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        y6id: {
            name: ['真如', 'Zhenru'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['ekdv'],
            children: ['naz0'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['shanghai', 'sh11', '#76232F', '#fff', '11号线', 'Line 11']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        exax: {
            name: ['嘉怡路', 'Jiayi Road'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['yrlx'],
            children: ['nhrh'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        qzjx: {
            name: ['蓝天路', 'Lantian Road'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['jsat'],
            children: ['l1mz'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['shanghai', 'sh9', '#71c5e8', '#000', '9号线', 'Line 9']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        '8hte': {
            name: ['乐秀路', 'Lexiu Road'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['9cyo'],
            children: ['yrlx'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        yrlx: {
            name: ['临洮路', 'Lintao Road'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['8hte'],
            children: ['exax'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        nhrh: {
            name: ['定边路', 'Dingbian Road'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['exax'],
            children: ['hhar'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        qgae: {
            name: ['真光路', 'Zhenguang Road'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['hhar'],
            children: ['ekdv'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        ekdv: {
            name: ['铜川路', 'Tongchuan Road'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['qgae'],
            children: ['y6id'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['shanghai', 'sh15', '#BBA786', '#000', '15号线', 'Line 15']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        h3vs: {
            name: ['浦东南路', 'South Pudong Road'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['jjh7'],
            children: ['lcgp'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        '5xa7': {
            name: ['浦东足球场', 'Pudong Football Stadium'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['iwf6'],
            children: ['vdsk'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        vdsk: {
            name: ['金粤路', 'Jinyue Road'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['5xa7'],
            children: ['n31j'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        n31j: {
            name: ['桂桥路', 'Guiqiao Road'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['vdsk'],
            children: ['lineend'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
    },
    line_name: ['14号线', 'Line 14'],
    psd_num: '1',
    line_num: '01',
    info_panel_type: 'sh',
    direction_gz_x: 50,
    direction_gz_y: 70,
    customiseMTRDest: { isLegacy: false, terminal: false },
    svgWidth: { destination: 1500, runin: 1500, railmap: 2000, indoor: 3000 },
    notesGZMTR: [],
    namePosMTR: { isStagger: true, isFlip: false },
};

export default param;
