const param = {
    style: 'shmetro',
    svg_height: 625,
    padding: 8.750201061605276,
    y_pc: 40,
    branch_spacing: 45,
    theme: ['shanghai', 'sh4', '#5F259F', '#fff'],
    direction: 'l',
    current_stn_idx: 'y6id',
    platform_num: false,
    stn_list: {
        linestart: {
            parents: [],
            children: ['9cyo'],
            name: ['路綫左端', 'LEFT END'],
            branch: { left: [], right: [] },
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            num: '00',
            facility: '',
            secondaryName: false,
            loop_pivot: false,
        },
        lineend: {
            parents: ['qzjx'],
            children: [],
            name: ['路綫右端', 'RIGHT END'],
            branch: { left: [], right: [] },
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            num: '00',
            facility: '',
            secondaryName: false,
            loop_pivot: false,
        },
        jsat: {
            parents: ['srpy'],
            children: ['qzjx'],
            branch: { left: [], right: [] },
            name: ['延安西路', "West Yan'an Road"],
            num: '00',
            transfer: {
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [[['shanghai', 'sh3', '#ffd100', '#000', '3号线', 'Line 3']]],
            },
            services: ['local'],
            facility: '',
            secondaryName: false,
            loop_pivot: false,
        },
        srpy: {
            parents: ['x9gu'],
            children: ['jsat'],
            branch: { left: [], right: [] },
            name: ['中山公园', 'Zhongshan Park'],
            num: '00',
            transfer: {
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [
                    [
                        ['shanghai', 'sh2', '#97d700', '#000', '2号线', 'Line 2'],
                        ['shanghai', 'sh3', '#ffd100', '#000', '3号线', 'Line 3'],
                    ],
                    [],
                    [],
                ],
            },
            services: ['local'],
            facility: '',
            secondaryName: false,
            loop_pivot: true,
        },
        x9gu: {
            parents: ['k9k5'],
            children: ['srpy'],
            branch: { left: [], right: [] },
            name: ['金沙江路', 'Jinshajiang Road'],
            num: '00',
            transfer: {
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [
                    [
                        ['shanghai', 'sh3', '#ffd100', '#000', '3号线', 'Line 3'],
                        ['shanghai', 'sh13', '#EF95CF', '#000', '13号线', 'Line 13'],
                    ],
                ],
            },
            services: ['local'],
            facility: '',
            secondaryName: false,
            loop_pivot: false,
        },
        k9k5: {
            parents: ['j2kn'],
            children: ['x9gu'],
            branch: { left: [], right: [] },
            name: ['曹杨路', 'Caoyang Road'],
            num: '00',
            services: ['local'],
            transfer: {
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [
                    [
                        ['shanghai', 'sh3', '#ffd100', '#000', '3号线', 'Line 3'],
                        ['shanghai', 'sh11', '#76232F', '#fff', '11号线', 'Line 11'],
                    ],
                    [['shanghai', 'sh14', '#827A04', '#fff', '14号线', 'Line 14']],
                ],
            },
            facility: '',
            secondaryName: false,
            loop_pivot: false,
        },
        j2kn: {
            parents: ['lcgp'],
            children: ['k9k5'],
            branch: { left: [], right: [] },
            name: ['镇坪路', 'Zhenping Road'],
            num: '00',
            services: ['local'],
            transfer: {
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [
                    [
                        ['shanghai', 'sh3', '#ffd100', '#000', '3号线', 'Line 3'],
                        ['shanghai', 'sh7', '#FF6900', '#000', '7号线', 'Line 7'],
                    ],
                ],
            },
            facility: '',
            secondaryName: false,
            loop_pivot: false,
        },
        kaxg: {
            parents: ['7x7k'],
            children: ['wbtv'],
            branch: { left: [], right: [] },
            name: ['临平路', 'Linping Road'],
            num: '00',
            services: ['local'],
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            facility: '',
            secondaryName: false,
            loop_pivot: false,
        },
        sd6y: {
            parents: ['1fdr'],
            children: ['qnbj'],
            branch: { left: [], right: [] },
            name: ['浦东大道', 'Pudong Avenue'],
            num: '00',
            services: ['local'],
            transfer: {
                tick_direc: 'r',
                paid_area: true,
                osi_names: [['車站名', 'Stn Name']],
                info: [[['shanghai', 'sh14', '#827A04', '#fff', '14号线', 'Line 14']], []],
            },
            facility: '',
            secondaryName: false,
            loop_pivot: false,
        },
        '9cyo': {
            parents: ['linestart'],
            children: ['8hte'],
            branch: { left: [], right: [] },
            name: ['宜山路', 'Yishan Road'],
            num: '00',
            services: ['local'],
            transfer: {
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [
                    [
                        ['shanghai', 'sh3', '#ffd100', '#000', '3号线', 'Line 3'],
                        ['shanghai', 'sh9', '#71c5e8', '#000', '9号线', 'Line 9'],
                    ],
                ],
            },
            facility: '',
            secondaryName: false,
            loop_pivot: false,
        },
        hhar: {
            children: ['qgae'],
            parents: ['nhrh'],
            branch: { left: [], right: [] },
            name: ['鲁班路', 'Luban Road'],
            num: '00',
            services: ['local'],
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            facility: '',
            secondaryName: false,
            loop_pivot: false,
        },
        jjh7: {
            children: ['h3vs'],
            parents: ['wbtv'],
            branch: { left: [], right: [] },
            name: ['宝山路', 'Baoshan Road'],
            num: '00',
            services: ['local'],
            transfer: {
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [[['shanghai', 'sh3', '#ffd100', '#000', '3号线', 'Line 3']]],
            },
            facility: '',
            secondaryName: false,
            loop_pivot: false,
        },
        '7x7k': {
            children: ['kaxg'],
            parents: ['qnbj'],
            branch: { left: [], right: [] },
            name: ['大连路', 'Dalian Road'],
            num: '00',
            services: ['local'],
            transfer: {
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [[['shanghai', 'sh12', '#007b5f', '#fff', '12号线', 'Line 12']]],
            },
            facility: '',
            secondaryName: false,
            loop_pivot: false,
        },
        qnbj: {
            name: ['杨树浦路', 'Yangshupu Road'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['sd6y'],
            children: ['7x7k'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
            loop_pivot: false,
        },
        '1fdr': {
            name: ['世纪大道', 'Century Avenue'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['wai3'],
            children: ['sd6y'],
            branch: { left: [], right: [] },
            transfer: {
                info: [
                    [
                        ['shanghai', 'sh2', '#97d700', '#000', '2号线', 'Line 2'],
                        ['shanghai', 'sh6', '#D9027D', '#fff', '6号线', 'Line 6'],
                        ['shanghai', 'sh9', '#71c5e8', '#000', '9号线', 'Line 9'],
                    ],
                ],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
            loop_pivot: true,
        },
        lcgp: {
            name: ['中潭路', 'Zhongtan Road'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['h3vs'],
            children: ['j2kn'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['shanghai', 'sh3', '#ffd100', '#000', '3号线', 'Line 3']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
            loop_pivot: false,
        },
        wbtv: {
            name: ['海伦路站', 'Hailun Road'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['kaxg'],
            children: ['jjh7'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['shanghai', 'sh10', '#c1a7e2', '#000', '10号线', 'Line 10']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
            loop_pivot: false,
        },
        wai3: {
            name: ['浦电路', 'Pudian Road'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['naz0'],
            children: ['1fdr'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
            loop_pivot: false,
        },
        naz0: {
            name: ['蓝村路', 'Lancun Road'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['y6id'],
            children: ['wai3'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['shanghai', 'sh6', '#D9027D', '#fff', '6号线', 'Line 6']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
            loop_pivot: false,
        },
        y6id: {
            name: ['塘桥', 'Tangqiao'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['ekdv'],
            children: ['naz0'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
            loop_pivot: false,
        },
        exax: {
            name: ['东安路站', "Dong'an Road"],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['yrlx'],
            children: ['nhrh'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['shanghai', 'sh7', '#FF6900', '#000', '7号线', 'Line 7']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
            loop_pivot: false,
        },
        qzjx: {
            name: ['虹桥路', 'Hongqiao Road'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['jsat'],
            children: ['lineend'],
            branch: { left: [], right: [] },
            transfer: {
                info: [
                    [
                        ['shanghai', 'sh3', '#ffd100', '#000', '3号线', 'Line 3'],
                        ['shanghai', 'sh10', '#C1A7E2', '#000', '10号线', 'Line 10'],
                    ],
                ],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
            loop_pivot: false,
        },
        '8hte': {
            name: ['上海体育馆', 'Shanghai Indoor Stadium'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['9cyo'],
            children: ['yrlx'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['shanghai', 'sh1', '#E4002B', '#fff', '1号线', 'Line 1']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
            loop_pivot: true,
        },
        yrlx: {
            name: ['上海体育场', 'Shanghai Stadium'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['8hte'],
            children: ['exax'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
            loop_pivot: false,
        },
        nhrh: {
            name: ['大木桥路', 'Damuqiao Road'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['exax'],
            children: ['hhar'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['shanghai', 'sh12', '#007b5f', '#fff', '12号线', 'Line 12']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
            loop_pivot: false,
        },
        qgae: {
            name: ['西藏南路', 'South Xizang Road'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['hhar'],
            children: ['ekdv'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['shanghai', 'sh8', '#00a3e0', '#fff', '8号线', 'Line 8']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
            loop_pivot: true,
        },
        ekdv: {
            name: ['南浦大桥', 'Nanpu Bridge'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['qgae'],
            children: ['y6id'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
            loop_pivot: false,
        },
        h3vs: {
            name: ['上海火车站', 'Shanghai Railway Station'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['jjh7'],
            children: ['lcgp'],
            branch: { left: [], right: [] },
            transfer: {
                info: [
                    [['shanghai', 'sh3', '#ffd100', '#000', '3号线', 'Line 3']],
                    [['shanghai', 'sh1', '#E4002B', '#fff', '1号线', 'Line 1']],
                ],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
            loop_pivot: true,
        },
    },
    line_name: ['4号线', 'Line 4'],
    psd_num: '1',
    line_num: '01',
    info_panel_type: 'sh2020',
    direction_gz_x: 50,
    direction_gz_y: 70,
    customiseMTRDest: { isLegacy: false, terminal: false },
    svgWidth: { destination: 1600, runin: 1200, railmap: 2400, indoor: 2600 },
    notesGZMTR: [],
    namePosMTR: { isStagger: true, isFlip: false },
    coline: [],
    loop: true,
    loop_info: { bank: true, left_and_right_factor: 1, bottom_factor: 12 },
};

export default param;
