const params = {
    style: 'gzmtr',
    svg_height: 370,
    padding: 4.56,
    y_pc: 35.32,
    branch_spacing: 44.44444444444444,
    theme: ['foshan', 'fs2', '#DD0027', '#fff'],
    direction: 'r',
    current_stn_idx: '5o5y',
    platform_num: '3',
    stn_list: {
        linestart: {
            parents: [],
            children: ['l1mz'],
            name: ['路綫左端', 'LEFT END'],
            branch: { left: [], right: [] },
            num: '00',
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        lineend: {
            parents: ['ch3s'],
            children: [],
            name: ['路綫右端', 'RIGHT END'],
            branch: { left: [], right: [] },
            num: '00',
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        l1mz: {
            parents: ['linestart'],
            children: ['ndua'],
            name: ['南庄', 'Nanzhuang'],
            branch: { left: [], right: [] },
            num: '11',
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        iwf6: {
            children: ['ch3s'],
            parents: ['57ve'],
            name: ['林岳东', 'Linyue Dong'],
            branch: { left: [], right: [] },
            num: '26',
            transfer: {
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [[['other', 'other', '#60B4E3', '#fff', '南海有轨电车1号线', 'TNH1']]],
            },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        '57ve': {
            parents: ['d2ch'],
            children: ['iwf6'],
            name: ['林岳西', 'Linyue Xi'],
            branch: { left: [], right: [] },
            num: '25',
            transfer: {
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [[['other', 'other', '#60B4E3', '#fff', '南海有轨电车1号线', 'TNH1']]],
            },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        d2ch: {
            parents: ['rq4h'],
            children: ['57ve'],
            name: ['石洲', 'Shizhou'],
            branch: { left: [], right: [] },
            num: '24',
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        rq4h: {
            parents: ['n1ni'],
            children: ['d2ch'],
            name: ['仙涌', 'Xianchong'],
            branch: { left: [], right: [] },
            num: '23',
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        n1ni: {
            parents: ['7kvg'],
            children: ['rq4h'],
            name: ['花卉世界', 'Flower World'],
            branch: { left: [], right: [] },
            num: '22',
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        '7kvg': {
            parents: ['5o5y'],
            children: ['n1ni'],
            name: ['登洲', 'Dengzhou'],
            branch: { left: [], right: [] },
            num: '21',
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        l9io: {
            parents: ['2ifb'],
            children: ['5o5y'],
            name: ['石梁', 'Shiliang'],
            branch: { left: [], right: [] },
            num: '19',
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        '2ifb': {
            parents: ['lcjl'],
            children: ['l9io'],
            name: ['魁奇路', 'Kuiqi Lu'],
            branch: { left: [], right: [] },
            num: '18',
            transfer: {
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [[['guangzhou', 'gfl', '#C4D600', '#fff', '广佛线', 'Guangfo Line']]],
            },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        lcjl: {
            parents: ['fbpn'],
            children: ['2ifb'],
            name: ['沙岗', 'Shagang'],
            branch: { left: [], right: [] },
            num: '17',
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        fbpn: {
            parents: ['mclm'],
            children: ['lcjl'],
            name: ['石湾', 'Shiwan'],
            branch: { left: [], right: [] },
            num: '16',
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        mclm: {
            parents: ['lx10'],
            children: ['fbpn'],
            name: ['张槎', 'Zhangcha'],
            branch: { left: [], right: [] },
            num: '15',
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        lx10: {
            parents: ['yz8y'],
            children: ['mclm'],
            name: ['智慧新城', 'Zhihui Xincheng'],
            branch: { left: [], right: [] },
            num: '14',
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        yz8y: {
            parents: ['ndua'],
            children: ['lx10'],
            name: ['绿岛湖', 'Lvdao Lake'],
            branch: { left: [], right: [] },
            num: '13',
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        ndua: {
            parents: ['l1mz'],
            children: ['yz8y'],
            name: ['湖涌', 'Huchong'],
            branch: { left: [], right: [] },
            num: '12',
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        '5o5y': {
            parents: ['l9io'],
            children: ['7kvg'],
            name: ['湾华', 'Wanhua'],
            branch: { left: [], right: [] },
            num: '20',
            transfer: {
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [[['foshan', 'fs3', '#4747C5', '#fff', '3号线', 'Line 3']]],
            },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        ch3s: {
            name: ['广州南站', 'Guangzhou South\\Railway Station'],
            secondaryName: false,
            num: '27',
            services: ['local'],
            parents: ['iwf6'],
            children: ['lineend'],
            branch: { left: [], right: [] },
            transfer: {
                info: [
                    [
                        ['guangzhou', 'gz2', '#00629B', '#fff', '广州2号线', 'Guangzhou Line 2'],
                        ['guangzhou', 'gz7', '#97D700', '#000', '广州7号线', 'Guangzhou Line 7'],
                        ['guangzhou', 'gz22', '#CD5228', '#fff', '广州22号线', 'Guangzhou Line 22'],
                    ],
                ],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
    },
    line_name: ['2号线', 'Line 2'],
    psd_num: '1',
    line_num: 'F2',
    info_panel_type: 'gz28',
    direction_gz_x: 95.44,
    direction_gz_y: 72.23,
    customiseMTRDest: { isLegacy: false, terminal: false },
    svgWidth: { destination: 1150, runin: 1150, railmap: 1200, indoor: 1150 },
    notesGZMTR: [
        [
            '南海有轨电车1号线（文翰湖公园-林岳东）尚未开通。',
            'TNH1 (Wenhanhu Park-Linyue Dong) is under construction.',
            20.5,
            53,
            false,
        ],
        ['3号线尚未开通。', 'Line 3 is under construction.', 20.5, 63, false],
        ['广州地铁22号线尚未开通。', 'Guangzhou Line 22 is under construction.', 20.5, 73.5, false],
        ['出站换乘', 'Exit station before transfer', 88.5, 4.5, false],
    ],
    namePosMTR: { isStagger: true, isFlip: true },
};

export default params;
