const params = {
    style: 'gzmtr',
    svg_height: 300,
    padding: 8.750201061605276,
    y_pc: 40,
    branch_spacing: 45,
    theme: ['other', 'other', '#55AA88', '#fff'],
    direction: 'l',
    current_stn_idx: 'iwf6',
    platform_num: '2',
    stn_list: {
        linestart: {
            parents: [],
            children: ['yona'],
            name: ['路綫左端', 'LEFT END'],
            branch: { left: [], right: [] },
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            num: '00',
            secondaryName: false,
        },
        lineend: {
            parents: ['iwf6'],
            children: [],
            name: ['路綫右端', 'RIGHT END'],
            branch: { left: [], right: [] },
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            num: '00',
            secondaryName: false,
        },
        l1mz: {
            parents: ['czmj'],
            children: ['iwf6'],
            name: ['跃华路', 'Yuehua Road'],
            branch: { left: [], right: [] },
            num: '05',
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        iwf6: {
            children: ['lineend'],
            parents: ['l1mz'],
            name: ['沧江路', 'Cangjiang Road'],
            branch: { left: [], right: [] },
            num: '04',
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        czmj: {
            name: ['怡乐路', 'Yile Road'],
            secondaryName: false,
            num: '06',
            services: ['local'],
            parents: ['yrho'],
            children: ['l1mz'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        yrho: {
            name: ['荷城', 'Hecheng'],
            secondaryName: false,
            num: '07',
            services: ['local'],
            parents: ['qql7'],
            children: ['czmj'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        qql7: {
            name: ['文化中心', 'Culture Center'],
            secondaryName: false,
            num: '08',
            services: ['local'],
            parents: ['iqte'],
            children: ['yrho'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        iqte: {
            name: ['明湖公园', 'Minghu Park'],
            secondaryName: false,
            num: '09',
            services: ['local'],
            parents: ['9kln'],
            children: ['qql7'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        '9kln': {
            name: ['新江路', 'Xinjiang Road'],
            secondaryName: false,
            num: '10',
            services: ['local'],
            parents: ['0w7s'],
            children: ['iqte'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        '0w7s': {
            name: ['体育中心', 'Sport Center'],
            secondaryName: false,
            num: '11',
            services: ['local'],
            parents: ['2q0e'],
            children: ['9kln'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        '2q0e': {
            name: ['阮埇', 'Ruanyong'],
            secondaryName: false,
            num: '12',
            services: ['local'],
            parents: ['yona'],
            children: ['0w7s'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        yona: {
            name: ['智湖', 'Zhihu'],
            secondaryName: false,
            num: '13',
            services: ['local'],
            parents: ['linestart'],
            children: ['2q0e'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
    },
    line_name: ['高明有轨电车', 'TGM1'],
    psd_num: '1',
    line_num: 'TGM1',
    info_panel_type: 'gz28',
    direction_gz_x: 50,
    direction_gz_y: 70,
    customiseMTRDest: { isLegacy: false, terminal: false },
    svgWidth: { destination: 1000, runin: 1000, railmap: 1000, indoor: 800 },
    notesGZMTR: [],
    namePosMTR: { isStagger: true, isFlip: false },
};

export default params;
