const params = {
    style: 'gzmtr',
    svg_height: 300,
    padding: 8.750201061605276,
    y_pc: 40,
    branch_spacing: 45,
    theme: ['guangzhou', 'apm', '#00B5E2', '#fff'],
    direction: 'l',
    current_stn_idx: 'qbbb',
    platform_num: '3',
    stn_list: {
        linestart: {
            parents: [],
            children: ['egke'],
            name: ['路綫左端', 'LEFT END'],
            branch: { left: [], right: [] },
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            num: '10',
            secondaryName: false,
        },
        lineend: {
            parents: ['qbbb'],
            children: [],
            name: ['路綫右端', 'RIGHT END'],
            branch: { left: [], right: [] },
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            num: '00',
            secondaryName: false,
        },
        l1mz: {
            parents: ['iwf6'],
            children: ['lyqw'],
            name: ['天河南', 'Tianhenan'],
            branch: { left: [], right: [] },
            num: '07',
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        iwf6: {
            children: ['l1mz'],
            parents: ['egke'],
            name: ['体育中心南', 'Tianhe Sport Center South'],
            branch: { left: [], right: [] },
            num: '08',
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        qbbb: {
            parents: ['tgp4'],
            children: ['lineend'],
            branch: { left: [], right: [] },
            name: ['广州塔', 'Canton Tower'],
            num: '01',
            services: ['local'],
            facility: '',
            transfer: {
                info: [[['guangzhou', 'gz3', '#ECA154', '#000', '3号线', 'Line 3']]],
                osi_names: [],
                paid_area: true,
                tick_direc: 'r',
            },
            secondaryName: false,
        },
        tgp4: {
            parents: ['ecsx'],
            children: ['qbbb'],
            branch: { left: [], right: [] },
            name: ['海心沙', 'Haixinsha'],
            num: '02',
            services: ['local'],
            facility: '',
            transfer: { info: [[]], osi_names: [], paid_area: true, tick_direc: 'r' },
            secondaryName: false,
        },
        su3g: {
            parents: ['9v64'],
            children: ['ecsx'],
            branch: { left: [], right: [] },
            name: ['花城大道', 'Huacheng Dadao'],
            num: '04',
            services: ['local'],
            facility: '',
            transfer: { info: [[]], osi_names: [], paid_area: true, tick_direc: 'r' },
            secondaryName: false,
        },
        '9v64': {
            parents: ['lyqw'],
            children: ['su3g'],
            branch: { left: [], right: [] },
            name: ['妇儿中心', "Guangzhou Women and\\Children's Medical Center"],
            num: '05',
            services: ['local'],
            facility: '',
            transfer: { info: [[]], osi_names: [], paid_area: true, tick_direc: 'r' },
            secondaryName: false,
        },
        lyqw: {
            parents: ['l1mz'],
            children: ['9v64'],
            branch: { left: [], right: [] },
            name: ['黄埔大道', 'Huangpu Dadao'],
            num: '06',
            services: ['local'],
            facility: '',
            transfer: { info: [[]], osi_names: [], paid_area: true, tick_direc: 'r' },
            secondaryName: false,
        },
        ecsx: {
            name: ['大剧院', 'Guangzhou\\Opera House'],
            secondaryName: false,
            num: '03',
            services: ['local'],
            parents: ['su3g'],
            children: ['tgp4'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        egke: {
            name: ['林和西', 'Linhexi'],
            secondaryName: false,
            num: '09',
            services: ['local'],
            parents: ['linestart'],
            children: ['iwf6'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['guangzhou', 'gz3', '#ECA154', '#000', '3号线', 'Line 3']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
    },
    line_name: ['APM线', 'APM Line'],
    psd_num: '2',
    line_num: 'APM',
    info_panel_type: 'gzgf',
    direction_gz_x: 45,
    direction_gz_y: 69.27,
    customiseMTRDest: { isLegacy: false, terminal: false },
    svgWidth: { destination: 1000, runin: 1000, railmap: 1200, indoor: 1000 },
    notesGZMTR: [],
    namePosMTR: { isStagger: true, isFlip: false },
};

export default params;
