const params = {
    svg_height: 300,
    svg_width: 1400,
    svg_dest_width: 1000,
    show_outer: true,
    padding: 4.20352796096724,
    y_pc: 38.089110503458265,
    strip_pc: 90,
    branch_spacing: 45,
    theme: ['guangzhou', 'gfl', '#C4D600', '#fff'],
    direction: 'r',
    current_stn_idx: 'iwf6',
    platform_num: '4',
    txt_bg_gap: 15,
    txt_flip: true,
    stn_list: {
        linestart: {
            parents: [],
            children: ['iwf6'],
            name: ['路綫左端', 'LEFT END'],
            change_type: 'none',
            branch: { left: [], right: [] },
            interchange: [[]],
            transfer: { type: 'none', tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
        },
        lineend: {
            parents: ['zu95'],
            children: [],
            name: ['路綫右端', 'RIGHT END'],
            change_type: 'none',
            branch: { left: [], right: [] },
            interchange: [[]],
            transfer: { type: 'none', tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
        },
        l1mz: {
            parents: ['iwf6'],
            children: ['y3n5'],
            name: ['南洲', 'Nanzhou'],
            change_type: 'int2',
            branch: { left: [], right: [] },
            num: '21',
            interchange: [[['guangzhou', 'gz2', '#00629B', '#fff', '2号线', 'Line 2']]],
            transfer: {
                type: 'int2',
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [[['guangzhou', 'gz2', '#00629B', '#fff', '2号线', 'Line 2']]],
            },
        },
        iwf6: {
            children: ['l1mz'],
            parents: ['linestart'],
            name: ['沥滘', 'Lijiao'],
            change_type: 'int2',
            branch: { left: [], right: [] },
            num: '25',
            interchange: [[['guangzhou', 'gz3', '#ECA154', '#000', '3号线', 'Line 3']]],
            transfer: {
                type: 'int2',
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [[['guangzhou', 'gz3', '#ECA154', '#000', '3号线', 'Line 3']]],
            },
        },
        y3n5: {
            branch: { left: [], right: [] },
            parents: ['l1mz'],
            children: ['wo0p'],
            name: ['石溪', 'Shixi'],
            change_type: 'none',
            num: '23',
            interchange: [[]],
            transfer: { type: 'none', tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
        },
        wo0p: {
            branch: { left: [], right: [] },
            parents: ['y3n5'],
            children: ['z8yd'],
            name: ['燕岗', 'Yangang'],
            change_type: 'none',
            num: '22',
            interchange: [[]],
            transfer: { type: 'none', tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
        },
        z8yd: {
            branch: { left: [], right: [] },
            parents: ['wo0p'],
            children: ['8z6j'],
            name: ['沙园', 'Shayuan'],
            change_type: 'int2',
            num: '21',
            interchange: [[['guangzhou', 'gz8', '#008C95', '#fff', '8号线', 'Line 8']]],
            transfer: {
                type: 'int2',
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [[['guangzhou', 'gz8', '#008C95', '#fff', '8号线', 'Line 8']]],
            },
        },
        '8z6j': {
            branch: { left: [], right: [] },
            parents: ['z8yd'],
            children: ['bnx1'],
            name: ['沙涌', 'Shachong'],
            change_type: 'none',
            num: '20',
            interchange: [[]],
            transfer: { type: 'none', tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
        },
        bnx1: {
            branch: { left: [], right: [] },
            parents: ['8z6j'],
            children: ['paqy'],
            name: ['鹤洞', 'Hedong'],
            change_type: 'none',
            num: '19',
            interchange: [[]],
            transfer: { type: 'none', tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
        },
        paqy: {
            branch: { left: [], right: [] },
            parents: ['bnx1'],
            children: ['4p6r'],
            name: ['西塱', 'Xilang'],
            change_type: 'int2',
            num: '18',
            interchange: [[['guangzhou', 'gz1', '#F3D03E', '#000', '1号线', 'Line 1']]],
            transfer: {
                type: 'int2',
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [[['guangzhou', 'gz1', '#F3D03E', '#000', '1号线', 'Line 1']]],
            },
        },
        '4p6r': {
            branch: { left: [], right: [] },
            parents: ['paqy'],
            children: ['zrbn'],
            name: ['菊树', 'Jushu'],
            change_type: 'none',
            num: '17',
            interchange: [[]],
            transfer: { type: 'none', tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
        },
        zrbn: {
            branch: { left: [], right: [] },
            parents: ['4p6r'],
            children: ['2y6t'],
            name: ['龙溪', 'Longxi'],
            change_type: 'none',
            num: '16',
            interchange: [[]],
            transfer: { type: 'none', tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
        },
        '2y6t': {
            branch: { left: [], right: [] },
            parents: ['zrbn'],
            children: ['a5jc'],
            name: ['金融高新区', 'Financial Hi-Tech Zone'],
            change_type: 'none',
            num: '15',
            interchange: [[]],
            transfer: { type: 'none', tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
        },
        a5jc: {
            branch: { left: [], right: [] },
            parents: ['2y6t'],
            children: ['eu9g'],
            name: ['千灯湖', 'Qiandenghu Lake'],
            change_type: 'none',
            num: '14',
            interchange: [[]],
            transfer: { type: 'none', tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
        },
        eu9g: {
            branch: { left: [], right: [] },
            parents: ['a5jc'],
            children: ['s6zm'],
            name: ['𧒽岗', 'Leigang'],
            change_type: 'none',
            num: '13',
            interchange: [[]],
            transfer: { type: 'none', tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
        },
        s6zm: {
            branch: { left: [], right: [] },
            parents: ['eu9g'],
            children: ['28fn'],
            name: ['南桂路', 'Nangui Lu'],
            change_type: 'none',
            num: '12',
            interchange: [[]],
            transfer: { type: 'none', tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
        },
        '28fn': {
            branch: { left: [], right: [] },
            parents: ['s6zm'],
            children: ['1dy1'],
            name: ['桂城', 'Guicheng'],
            change_type: 'none',
            num: '11',
            interchange: [[]],
            transfer: { type: 'none', tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
        },
        '1dy1': {
            branch: { left: [], right: [] },
            parents: ['28fn'],
            children: ['4asf'],
            name: ['朝安', "Chao'an"],
            change_type: 'none',
            num: '10',
            interchange: [[]],
            transfer: { type: 'none', tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
        },
        '4asf': {
            branch: { left: [], right: [] },
            parents: ['1dy1'],
            children: ['eudw'],
            name: ['普君北路', 'Pujun Beilu'],
            change_type: 'none',
            num: '09',
            interchange: [[]],
            transfer: { type: 'none', tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
        },
        eudw: {
            branch: { left: [], right: [] },
            parents: ['4asf'],
            children: ['jy3n'],
            name: ['祖庙', 'Zumiao'],
            change_type: 'none',
            num: '08',
            interchange: [[]],
            transfer: { type: 'none', tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
        },
        jy3n: {
            branch: { left: [], right: [] },
            parents: ['eudw'],
            children: ['3lip'],
            name: ['同济路', 'Tongji Lu'],
            change_type: 'none',
            num: '07',
            interchange: [[]],
            transfer: { type: 'none', tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
        },
        '3lip': {
            branch: { left: [], right: [] },
            parents: ['jy3n'],
            children: ['fjqd'],
            name: ['季华园', 'Jihua Park'],
            change_type: 'none',
            num: '06',
            interchange: [[]],
            transfer: { type: 'none', tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
        },
        fjqd: {
            branch: { left: [], right: [] },
            parents: ['3lip'],
            children: ['3sqh'],
            name: ['魁奇路', 'Kuiqi Lu'],
            change_type: 'none',
            num: '05',
            interchange: [[]],
            transfer: { type: 'none', tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
        },
        '3sqh': {
            branch: { left: [], right: [] },
            parents: ['fjqd'],
            children: ['ayll'],
            name: ['澜石', 'Lanshi'],
            change_type: 'none',
            num: '04',
            interchange: [[]],
            transfer: { type: 'none', tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
        },
        ayll: {
            branch: { left: [], right: [] },
            parents: ['3sqh'],
            children: ['uwgm'],
            name: ['世纪莲', 'Shijilian'],
            change_type: 'none',
            num: '03',
            interchange: [[]],
            transfer: { type: 'none', tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
        },
        uwgm: {
            branch: { left: [], right: [] },
            parents: ['ayll'],
            children: ['zu95'],
            name: ['东平', 'Dongping'],
            change_type: 'none',
            num: '02',
            interchange: [[]],
            transfer: { type: 'none', tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
        },
        zu95: {
            branch: { left: [], right: [] },
            parents: ['uwgm'],
            children: ['lineend'],
            name: ['新城东', 'Xincheng Dong'],
            change_type: 'none',
            num: '01',
            interchange: [[]],
            transfer: { type: 'none', tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
        },
    },
    line_name: ['广佛线', 'Guangfo Line'],
    dest_legacy: false,
    char_form: 'cn',
    psd_num: '3',
    line_num: 'GF',
    info_panel_type: 'gz6',
    direction_gz_x: 50,
    direction_gz_y: 70,
};

export default params;
