const params = {
    style: 'gzmtr',
    svg_height: 300,
    padding: 8.750201061605276,
    y_pc: 40,
    branch_spacing: 45,
    theme: ['guangzhou', 'gz13', '#8E8C13', '#fff'],
    direction: 'r',
    current_stn_idx: 'iwf6',
    platform_num: '3',
    stn_list: {
        '2990': {
            name: ['双岗', 'Shuanggang'],
            num: '03',
            services: ['local'],
            parents: ['l1mz'],
            children: ['o2kp'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
            secondaryName: false,
        },
        '6575': {
            name: ['新塘', 'Xintang'],
            num: '09',
            services: ['local'],
            parents: ['g0m1'],
            children: ['iblk'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
            secondaryName: false,
        },
        linestart: {
            parents: [],
            children: ['iwf6'],
            name: ['路綫右端', 'RIGHT END'],
            branch: { left: [], right: [] },
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            num: '00',
            secondaryName: false,
        },
        lineend: {
            parents: ['6dw0'],
            children: [],
            name: ['路綫左端', 'LEFT END'],
            branch: { left: [], right: [] },
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            num: '12',
            secondaryName: false,
        },
        l1mz: {
            parents: ['iwf6'],
            children: ['2990'],
            name: ['裕丰围', 'Yufengwei'],
            branch: { left: [], right: [] },
            num: '02',
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        iwf6: {
            children: ['l1mz'],
            parents: ['linestart'],
            name: ['鱼珠', 'Yuzhu'],
            branch: { left: [], right: [] },
            num: '01',
            transfer: {
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [[['guangzhou', 'gz5', '#C5003E', '#fff', '5号线', 'Line 5']]],
            },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        '6dw0': {
            name: ['新沙', 'Xinsha'],
            num: '11',
            services: ['local'],
            parents: ['iblk'],
            children: ['lineend'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
            secondaryName: false,
        },
        iblk: {
            name: ['官湖', 'Guanhu'],
            num: '10',
            services: ['local'],
            parents: ['6575'],
            children: ['6dw0'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
            secondaryName: false,
        },
        g0m1: {
            name: ['白江', 'Baijiang'],
            num: '08',
            services: ['local'],
            parents: ['9tlx'],
            children: ['6575'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
            secondaryName: false,
        },
        '9tlx': {
            name: ['沙村', 'Shacun'],
            num: '07',
            services: ['local'],
            parents: ['1en6'],
            children: ['g0m1'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
            secondaryName: false,
        },
        '1en6': {
            name: ['南岗', 'Nangang'],
            num: '06',
            services: ['local'],
            parents: ['hnoy'],
            children: ['9tlx'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
            secondaryName: false,
        },
        hnoy: {
            name: ['夏园', 'Xiayuan'],
            num: '05',
            services: ['local'],
            parents: ['o2kp'],
            children: ['1en6'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
            secondaryName: false,
        },
        o2kp: {
            name: ['南海神殿', 'Nanhai God Temple'],
            num: '04',
            services: ['local'],
            parents: ['2990'],
            children: ['hnoy'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
            secondaryName: false,
        },
    },
    line_name: ['13号线', 'Line 13'],
    psd_num: '1',
    line_num: '13',
    info_panel_type: 'gz1421',
    direction_gz_x: 41.84,
    direction_gz_y: 77.98,
    customiseMTRDest: { isLegacy: false, terminal: false },
    svgWidth: { destination: 1000, runin: 1000, railmap: 1000, indoor: 1000 },
    notesGZMTR: [],
    namePosMTR: { isStagger: true, isFlip: false },
};

export default params;
