const param = {
    svg_height: 300,
    padding: 8.750201061605276,
    y_pc: 46.03,
    branch_spacing: 45,
    theme: ['guangzhou', 'gz22', '#CD5228', '#fff'],
    direction: 'l',
    current_stn_idx: '92zp',
    platform_num: '5',
    stn_list: {
        linestart: {
            parents: [],
            children: ['m5r0'],
            name: ['路綫右端', 'RIGHT END'],
            branch: { left: [], right: [] },
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            num: '00',
            secondaryName: false,
        },
        lineend: {
            parents: ['l1mz'],
            children: [],
            name: ['路綫左端', 'LEFT END'],
            branch: { left: [], right: [] },
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            num: '00',
            secondaryName: false,
        },
        l1mz: {
            parents: ['iwf6'],
            children: ['lineend'],
            name: ['番禺广场', 'Panyu Square'],
            branch: { left: [], right: [] },
            num: '01',
            transfer: {
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [
                    [
                        ['guangzhou', 'gz3', '#ECA154', '#000', '3号线', 'Line 3'],
                        ['guangzhou', 'gz18', '#0047BA', '#fff', '18号线', 'Line 18'],
                    ],
                ],
            },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        iwf6: {
            children: ['l1mz'],
            parents: ['92zp'],
            name: ['市广路', 'Shiguanglu'],
            branch: { left: [], right: [] },
            num: '02',
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        '92zp': {
            name: ['广州南站', 'Guangzhou South Railway Station'],
            secondaryName: false,
            num: '03',
            services: ['local'],
            parents: ['m5r0'],
            children: ['iwf6'],
            branch: { left: [], right: [] },
            transfer: {
                info: [
                    [
                        ['guangzhou', 'gz2', '#00629B', '#fff', '2号线', 'Line 2'],
                        ['guangzhou', 'gz7', '#97D700', '#000', '7号线', 'Line 7'],
                        ['other', 'other', '#f50000', '#fff', '佛山2号线', 'Foshan Line 2'],
                    ],
                ],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        m5r0: {
            name: ['陈头岗', 'Chentougang'],
            secondaryName: false,
            num: '04',
            services: ['local'],
            parents: ['linestart'],
            children: ['92zp'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
    },
    line_name: ['22号线', 'Line 22'],
    psd_num: '1',
    line_num: '22',
    info_panel_type: 'gz1421',
    direction_gz_x: 47.82,
    direction_gz_y: 79.37,
    customiseMTRDest: { isLegacy: false, terminal: false },
    svgWidth: { destination: 1000, runin: 1200, railmap: 1500, indoor: 800 },
    notesGZMTR: [],
    namePosMTR: { isStagger: true, isFlip: false },
    style: 'gzmtr',
};

export default param;
