const params = {
    svg_height: 370,
    padding: 2.45,
    y_pc: 68.02,
    branch_spacing: 64.32,
    theme: ['guangzhou', 'gz3', '#ECA154', '#000'],
    direction: 'l',
    current_stn_idx: 'lh7j',
    platform_num: '4',
    stn_list: {
        linestart: {
            parents: [],
            children: ['w6sk', 'i21j'],
            name: ['路綫左端', 'LEFT END'],
            branch: { left: [], right: ['through', 'w6sk'] },
            transfer: { type: 'none', tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            num: '00',
            secondaryName: false,
        },
        lineend: {
            parents: ['iwf6'],
            children: [],
            name: ['路綫右端', 'RIGHT END'],
            branch: { left: [], right: [] },
            transfer: { type: 'none', tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            num: '00',
            secondaryName: false,
        },
        l1mz: {
            parents: ['n4at'],
            children: ['iwf6'],
            name: ['市桥', 'Shiqiao'],
            branch: { left: [], right: [] },
            num: '02',
            transfer: { type: 'none', tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        iwf6: {
            children: ['lineend'],
            parents: ['l1mz'],
            name: ['番禺广场', 'Panyu Square'],
            branch: { left: [], right: [] },
            num: '01',
            transfer: { type: 'none', tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        n4at: {
            parents: ['8gmo'],
            children: ['l1mz'],
            name: ['汉溪长隆', 'Hanxi Changlong'],
            branch: { left: [], right: [] },
            num: '03',
            transfer: {
                type: 'int2',
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [[['guangzhou', 'gz7', '#97D700', '#fff', '7号线', 'Line 7']]],
            },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        '8gmo': {
            parents: ['uixu'],
            children: ['n4at'],
            name: ['大石', 'Dashi'],
            branch: { left: [], right: [] },
            num: '04',
            transfer: { type: 'none', tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        uixu: {
            parents: ['f6ez'],
            children: ['8gmo'],
            name: ['厦滘', 'Xiajiao'],
            branch: { left: [], right: [] },
            num: '05',
            transfer: { type: 'none', tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        f6ez: {
            parents: ['5fjd'],
            children: ['uixu'],
            name: ['沥滘', 'Lijiao'],
            branch: { left: [], right: [] },
            num: '06',
            transfer: {
                type: 'int2',
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [[['guangzhou', 'gfl', '#C4D600', '#fff', '广佛线', 'Guangfo Line']]],
            },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        '5fjd': {
            parents: ['11dr'],
            children: ['f6ez'],
            name: ['大塘', 'Datang'],
            branch: { left: [], right: [] },
            num: '07',
            transfer: { type: 'none', tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        '11dr': {
            parents: ['orew'],
            children: ['5fjd'],
            name: ['客村', 'Kecun'],
            branch: { left: [], right: [] },
            num: '08',
            transfer: {
                type: 'int2',
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [[['guangzhou', 'gz8', '#008C95', '#fff', '8号线', 'Line 8']]],
            },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        orew: {
            parents: ['1i6w'],
            children: ['11dr'],
            name: ['广州塔', 'Canton Tower'],
            branch: { left: [], right: [] },
            num: '09',
            transfer: {
                type: 'int2',
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [[['guangzhou', 'apm', '#00B5E2', '#fff', 'APM线', 'APM Line']]],
            },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        '1i6w': {
            parents: ['lh7j'],
            children: ['orew'],
            name: ['珠江新城', 'Zhujiang New Town'],
            branch: { left: [], right: [] },
            num: '10',
            transfer: {
                type: 'int2',
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [[['guangzhou', 'gz5', '#C5003E', '#fff', '5号线', 'Line 5']]],
            },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        lh7j: {
            parents: ['u42d', 'gicw'],
            children: ['1i6w'],
            name: ['体育西路', 'Tiyu Xilu'],
            branch: { left: ['through', 'u42d'], right: [] },
            num: '11',
            transfer: {
                type: 'int2',
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [[['guangzhou', 'gz1', '#F3D03E', '#000', '1号线', 'Line 1']]],
            },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        gicw: {
            parents: ['ebgb'],
            children: ['lh7j'],
            name: ['林和西', 'Linhexi'],
            branch: { left: [], right: [] },
            num: '17',
            transfer: {
                type: 'int2',
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [[['guangzhou', 'apm', '#00B5E2', '#fff', 'APM线', 'APM Line']]],
            },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        ebgb: {
            parents: ['ttuu'],
            children: ['gicw'],
            name: ['广州东站', 'Guangzhou East\\Railway Station'],
            branch: { left: [], right: [] },
            num: '18',
            transfer: {
                type: 'int2',
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [[['guangzhou', 'gz1', '#F3D03E', '#000', '1号线', 'Line 1']]],
            },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        ttuu: {
            parents: ['m5bp'],
            children: ['ebgb'],
            name: ['燕塘', 'Yantang'],
            branch: { left: [], right: [] },
            num: '19',
            transfer: {
                type: 'int2',
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [[['guangzhou', 'gz6', '#80225F', '#fff', '6号线', 'Line 6']]],
            },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        m5bp: {
            parents: ['4nai'],
            children: ['ttuu'],
            name: ['梅花园', 'Meihuayuan'],
            branch: { left: [], right: [] },
            num: '20',
            transfer: { type: 'none', tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        '4nai': {
            parents: ['dhsq'],
            children: ['m5bp'],
            name: ['京溪南方医院', 'Jingxi Nanfang Hospital'],
            branch: { left: [], right: [] },
            num: '21',
            transfer: { type: 'none', tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        dhsq: {
            parents: ['2q8m'],
            children: ['4nai'],
            name: ['同和', 'Tonghe'],
            branch: { left: [], right: [] },
            num: '22',
            transfer: { type: 'none', tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        '2q8m': {
            parents: ['uh7r'],
            children: ['dhsq'],
            name: ['永泰', 'Yongtai'],
            branch: { left: [], right: [] },
            num: '23',
            transfer: { type: 'none', tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        uh7r: {
            parents: ['cwlm'],
            children: ['2q8m'],
            name: ['白云大道北', 'Baiyundadaobei'],
            branch: { left: [], right: [] },
            num: '24',
            transfer: { type: 'none', tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        cwlm: {
            parents: ['6d8a'],
            children: ['uh7r'],
            name: ['嘉禾望岗', 'Jiahewanggang'],
            branch: { left: [], right: [] },
            num: '25',
            transfer: {
                type: 'int3',
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [
                    [
                        ['guangzhou', 'gz2', '#00629B', '#fff', '2号线', 'Line 2'],
                        ['guangzhou', 'gz14', '#81312F', '#fff', '14号线', 'Line 14'],
                    ],
                ],
            },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        '6d8a': {
            parents: ['8qia'],
            children: ['cwlm'],
            name: ['龙归', 'Longgui'],
            branch: { left: [], right: [] },
            num: '26',
            transfer: { type: 'none', tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        '8qia': {
            parents: ['ww5f'],
            children: ['6d8a'],
            name: ['人和', 'Renhe'],
            branch: { left: [], right: [] },
            num: '27',
            transfer: { type: 'none', tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        ww5f: {
            parents: ['r3cg'],
            children: ['8qia'],
            name: ['高增', 'Gaozeng'],
            branch: { left: [], right: [] },
            num: '28',
            transfer: {
                type: 'int2',
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [[['guangzhou', 'gz9', '#71CC98', '#000', '9号线', 'Line 9']]],
            },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        r3cg: {
            parents: ['i21j'],
            children: ['ww5f'],
            name: ['机场南', 'Airport S.'],
            branch: { left: [], right: [] },
            num: '29',
            transfer: { type: 'none', tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            secondaryName: ['1号航站楼', 'Terminal 1'],
        },
        i21j: {
            parents: ['linestart'],
            children: ['r3cg'],
            name: ['机场北', 'Airport N.'],
            branch: { left: [], right: [] },
            num: '30',
            transfer: { type: 'none', tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            secondaryName: ['2号航站楼', 'Terminal 2'],
        },
        u42d: {
            parents: ['rc51'],
            children: ['lh7j'],
            name: ['石牌桥', 'Shipaiqiao'],
            branch: { left: [], right: [] },
            num: '12',
            transfer: { type: 'none', tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        rc51: {
            parents: ['5wsv'],
            children: ['u42d'],
            name: ['岗顶', 'Gangding'],
            branch: { left: [], right: [] },
            num: '13',
            transfer: { type: 'none', tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        '5wsv': {
            parents: ['dq4s'],
            children: ['rc51'],
            name: ['华师', 'South China\\Normal University'],
            branch: { left: [], right: [] },
            num: '14',
            transfer: { type: 'none', tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        dq4s: {
            parents: ['w6sk'],
            children: ['5wsv'],
            name: ['五山', 'Wushan'],
            branch: { left: [], right: [] },
            num: '15',
            transfer: { type: 'none', tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        w6sk: {
            parents: ['linestart'],
            children: ['dq4s'],
            name: ['天河客运站', 'Tianhe Coach Terminal'],
            branch: { left: [], right: [] },
            num: '16',
            transfer: {
                type: 'int2',
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [[['guangzhou', 'gz6', '#80225F', '#fff', '6号线', 'Line 6']]],
            },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
    },
    line_name: ['3号线', 'Line 3'],
    psd_num: '1',
    line_num: '3',
    info_panel_type: 'gz3',
    direction_gz_x: 2.21,
    direction_gz_y: 12.724668484036409,
    customiseMTRDest: { isLegacy: false, terminal: false },
    svgWidth: { destination: 1300, runin: 1300, railmap: 1550 },
    notesGZMTR: [
        [
            '尊敬的乘客：\n　　因运营组织需要，三号线在工作日非高峰期、晚高峰期和周六日、节假日全天，加开\n番禺广场至机场北双向列车，敬请关注车站广播、告示、地铁电视等终点站信息指引或咨\n询现场工作人员。',
            'Dear passengers, due to the need of the operation organization, during off-peak hours and evening peak hours on workdays, and all day on\nweekends and holidays, Line 3 will have additional two-way trains between Panyu Square and Airport N. Please pay attention to the\ndestination information guide from station broadcast, announcements and metro television, or consult the station staff.',
            56,
            4.5,
            false,
        ],
    ],
    namePosMTR: { isStagger: true, isFlip: true },
};

export default params;
