const params = {
    style: 'gzmtr',
    svg_height: 300,
    padding: 8.750201061605276,
    y_pc: 40,
    branch_spacing: 45,
    theme: ['guangzhou', 'gz7', '#97D700', '#000'],
    direction: 'l',
    current_stn_idx: 'iwf6',
    platform_num: '4',
    stn_list: {
        linestart: {
            parents: [],
            children: ['ny2q'],
            name: ['路綫左端', 'LEFT END'],
            branch: { left: [], right: [] },
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            num: '00',
            secondaryName: false,
        },
        lineend: {
            parents: ['ei9t'],
            children: [],
            name: ['路綫右端', 'RIGHT END'],
            branch: { left: [], right: [] },
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            num: '00',
            secondaryName: false,
        },
        l1mz: {
            parents: ['iwf6'],
            children: ['lyqw'],
            name: ['石壁', 'Shibi'],
            branch: { left: [], right: [] },
            num: '02',
            transfer: {
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [[['guangzhou', 'gz2', '#00629B', '#fff', '2号线', 'Line 2']]],
            },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        iwf6: {
            children: ['l1mz'],
            parents: ['0gcd'],
            name: ['广州南站', 'Guangzhou South\\Railway Station'],
            branch: { left: [], right: [] },
            num: '01',
            transfer: {
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [
                    [
                        ['guangzhou', 'gz2', '#00629B', '#fff', '2号线', 'Line 2'],
                        ['guangzhou', 'gz22', '#CD5228', '#fff', '22号线', 'Line 22'],
                        ['foshan', 'fs2', '#DD0027', '#fff', '佛山2号线', 'Foshan Line 2'],
                    ],
                ],
            },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        ei9t: {
            parents: ['qbbb'],
            children: ['lineend'],
            branch: { left: [], right: [] },
            name: ['大学城南', 'Higher Education\\Mega Center S.'],
            num: '09',
            services: ['local'],
            facility: '',
            transfer: {
                info: [[['guangzhou', 'gz4', '#00843D', '#fff', '4号线', 'Line 4']]],
                osi_names: [],
                paid_area: true,
                tick_direc: 'r',
            },
            secondaryName: false,
        },
        qbbb: {
            parents: ['tgp4'],
            children: ['ei9t'],
            branch: { left: [], right: [] },
            name: ['板桥', 'Banqiao'],
            num: '08',
            services: ['local'],
            facility: '',
            transfer: { info: [[]], osi_names: [], paid_area: true, tick_direc: 'r' },
            secondaryName: false,
        },
        tgp4: {
            parents: ['su3g'],
            children: ['qbbb'],
            branch: { left: [], right: [] },
            name: ['员岗', 'Yuangang'],
            num: '07',
            services: ['local'],
            facility: '',
            transfer: { info: [[]], osi_names: [], paid_area: true, tick_direc: 'r' },
            secondaryName: false,
        },
        su3g: {
            parents: ['dre1'],
            children: ['tgp4'],
            branch: { left: [], right: [] },
            name: ['南村万博', 'Nancun Wanbo'],
            num: '06',
            services: ['local'],
            facility: '',
            transfer: {
                info: [[['guangzhou', 'gz18', '#0047BA', '#fff', '18号线', 'Line 18']]],
                osi_names: [],
                paid_area: true,
                tick_direc: 'r',
            },
            secondaryName: false,
        },
        dre1: {
            parents: ['9v64'],
            children: ['su3g'],
            branch: { left: [], right: [] },
            name: ['汉溪长隆', 'Hanxi Changlong'],
            num: '05',
            services: ['local'],
            facility: '',
            transfer: {
                info: [[['guangzhou', 'gz3', '#ECA154', '#000', '3号线', 'Line 3']]],
                osi_names: [],
                paid_area: true,
                tick_direc: 'r',
            },
            secondaryName: false,
        },
        '9v64': {
            parents: ['lyqw'],
            children: ['dre1'],
            branch: { left: [], right: [] },
            name: ['钟村', 'Zhongcun'],
            num: '04',
            services: ['local'],
            facility: '',
            transfer: { info: [[]], osi_names: [], paid_area: true, tick_direc: 'r' },
            secondaryName: false,
        },
        lyqw: {
            parents: ['l1mz'],
            children: ['9v64'],
            branch: { left: [], right: [] },
            name: ['谢村', 'Xiecun'],
            num: '03',
            services: ['local'],
            facility: '',
            transfer: { info: [[]], osi_names: [], paid_area: true, tick_direc: 'r' },
            secondaryName: false,
        },
        '0gcd': {
            name: ['大洲', 'Dazhou'],
            secondaryName: false,
            num: '01-1',
            services: ['local'],
            parents: ['svlx'],
            children: ['iwf6'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        svlx: {
            name: ['陈村北', 'Chencunbei'],
            secondaryName: false,
            num: '01-2',
            services: ['local'],
            parents: ['s08h'],
            children: ['0gcd'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        s08h: {
            name: ['陈村', 'Chencun'],
            secondaryName: false,
            num: '01-3',
            services: ['local'],
            parents: ['ojvh'],
            children: ['svlx'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        ojvh: {
            name: ['锦龙', 'Jinlong'],
            secondaryName: false,
            num: '01-4',
            services: ['local'],
            parents: ['naqs'],
            children: ['s08h'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        naqs: {
            name: ['南涌', 'Nanchong'],
            secondaryName: false,
            num: '01-5',
            services: ['local'],
            parents: ['epll'],
            children: ['ojvh'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        epll: {
            name: ['美的', 'Midea'],
            secondaryName: false,
            num: '01-6',
            services: ['local'],
            parents: ['9uzg'],
            children: ['naqs'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        '9uzg': {
            name: ['北滘公园', 'Beijiao Park'],
            secondaryName: false,
            num: '01-7',
            services: ['local'],
            parents: ['ny2q'],
            children: ['epll'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        ny2q: {
            name: ['美的大道', 'Meidi Dadao'],
            secondaryName: false,
            num: '01-8',
            services: ['local'],
            parents: ['linestart'],
            children: ['9uzg'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
    },
    line_name: ['7号线', 'Line 7'],
    psd_num: '10',
    line_num: '7',
    info_panel_type: 'gz1421',
    direction_gz_x: 21.28,
    direction_gz_y: 79.02,
    customiseMTRDest: { isLegacy: false, terminal: false },
    svgWidth: { destination: 1000, runin: 1000, railmap: 1500, indoor: 1000 },
    notesGZMTR: [
        [
            '二十二号线(番禺广场-陈头岗)尚未开通。',
            'Line 22 (Panyu Square-Chentougang) is under construction.',
            50,
            79.5,
            true,
        ],
    ],
    namePosMTR: { isStagger: true, isFlip: false },
};

export default params;
