const params = {
    style: 'gzmtr',
    svg_height: 300,
    padding: 5.4,
    y_pc: 50,
    branch_spacing: 45,
    theme: ['guangzhou', 'thp1', '#D42D1B', '#fff'],
    direction: 'r',
    current_stn_idx: 'iwf6',
    platform_num: '2',
    stn_list: {
        linestart: {
            parents: [],
            children: ['iwf6'],
            name: ['路綫右端', 'RIGHT END'],
            branch: { left: [], right: [] },
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            num: '00',
            secondaryName: false,
        },
        lineend: {
            parents: ['pe9p'],
            children: [],
            name: ['路綫左端', 'LEFT END'],
            branch: { left: [], right: [] },
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            num: '00',
            secondaryName: false,
        },
        l1mz: {
            parents: ['iwf6'],
            children: ['bt13'],
            name: ['区少年宫（萝岗）', "Luogang District Children's Palace"],
            branch: { left: [], right: [] },
            num: '02',
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        iwf6: {
            children: ['l1mz'],
            parents: ['linestart'],
            name: ['地铁香雪', 'Xiangxue Subway Sation'],
            branch: { left: [], right: [] },
            num: '01',
            transfer: {
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [[['guangzhou', 'gz6', '#80225F', '#fff', '6号线', 'Line 6']]],
            },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        bt13: {
            name: ['线坑', 'Xiankeng'],
            secondaryName: false,
            num: '03',
            services: ['local'],
            parents: ['l1mz'],
            children: ['vr5x'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        vr5x: {
            name: ['市民广场', 'Civic Square'],
            secondaryName: false,
            num: '04',
            services: ['local'],
            parents: ['bt13'],
            children: ['hz9h'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        hz9h: {
            name: ['会议中心', 'Convention Center'],
            secondaryName: false,
            num: '05',
            services: ['local'],
            parents: ['vr5x'],
            children: ['g9l6'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        g9l6: {
            name: ['地铁水西', 'Shuixi Subway Station'],
            secondaryName: false,
            num: '06',
            services: ['local'],
            parents: ['hz9h'],
            children: ['vhjc'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['guangzhou', 'gz21', '#201747', '#fff', '21号线', 'Line 21']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        vhjc: {
            name: ['峻泰路', 'Juntailu'],
            secondaryName: false,
            num: '07',
            services: ['local'],
            parents: ['g9l6'],
            children: ['lg14'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        vgf2: {
            name: ['北师大实验学校站', 'Guangzhou Experimental\\School Affillated to BNU '],
            secondaryName: false,
            num: '09',
            services: ['local'],
            parents: ['lg14'],
            children: ['sl58'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        lg14: {
            name: ['水西', 'Shuixi'],
            secondaryName: false,
            num: '08',
            services: ['local'],
            parents: ['vhjc'],
            children: ['vgf2'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        sl58: {
            name: ['地铁长平', 'Changping Subway Station'],
            secondaryName: false,
            num: '10',
            services: ['local'],
            parents: ['vgf2'],
            children: ['hi53'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['guangzhou', 'gz21', '#201747', '#fff', '21号线', 'Line 21']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        hi53: {
            name: ['羌洞', 'Qiangdong'],
            secondaryName: false,
            num: '11',
            services: ['local'],
            parents: ['sl58'],
            children: ['5zpg'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        '5zpg': {
            name: ['长岭居小学', 'Changlingju Primary School'],
            secondaryName: false,
            num: '12',
            services: ['local'],
            parents: ['hi53'],
            children: ['l9cr'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        l9cr: {
            name: ['岭头', 'Lingtou'],
            secondaryName: false,
            num: '13',
            services: ['local'],
            parents: ['5zpg'],
            children: ['hxd6'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        hxd6: {
            name: ['干部健康中心', 'Guangzhou Cadre Health\\Management Center'],
            secondaryName: false,
            num: '14',
            services: ['local'],
            parents: ['l9cr'],
            children: ['u4ya'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        u4ya: {
            name: ['领头东', 'Lingtou East'],
            secondaryName: false,
            num: '15',
            services: ['local'],
            parents: ['hxd6'],
            children: ['kkk7'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        kkk7: {
            name: ['贤江西', 'Xianjiang West'],
            secondaryName: false,
            num: '16',
            services: ['local'],
            parents: ['u4ya'],
            children: ['95kn'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        '95kn': {
            name: ['贤江公园', 'Xianjiang Park'],
            secondaryName: false,
            num: '17',
            services: ['local'],
            parents: ['kkk7'],
            children: ['3opm'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        pe9p: {
            name: ['新丰路', 'Xinfenglu'],
            secondaryName: false,
            num: '19',
            services: ['local'],
            parents: ['3opm'],
            children: ['lineend'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        '3opm': {
            name: ['贤江', 'Xianjiang'],
            secondaryName: false,
            num: '18',
            services: ['local'],
            parents: ['95kn'],
            children: ['pe9p'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
    },
    line_name: ['黄埔有轨1号线', 'THP1'],
    psd_num: '1',
    line_num: 'THP1',
    info_panel_type: 'gz1421',
    direction_gz_x: 50,
    direction_gz_y: 76,
    customiseMTRDest: { isLegacy: false, terminal: false },
    svgWidth: { destination: 1000, runin: 1500, railmap: 1500, indoor: 800 },
    notesGZMTR: [],
    namePosMTR: { isStagger: true, isFlip: false },
};

export default params;
