const params = {
    style: 'gzmtr',
    svg_height: 300,
    padding: 8.750201061605276,
    y_pc: 40,
    branch_spacing: 45,
    theme: ['guangzhou', 'thz1', '#44A729', '#fff'],
    direction: 'r',
    current_stn_idx: 'l1mz',
    platform_num: '2',
    stn_list: {
        linestart: {
            parents: [],
            children: ['e0a2'],
            name: ['路綫左端', 'LEFT END'],
            branch: { left: [], right: [] },
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            num: '00',
            secondaryName: false,
        },
        lineend: {
            parents: ['jw4f'],
            children: [],
            name: ['路綫右端', 'RIGHT END'],
            branch: { left: [], right: [] },
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            num: '00',
            secondaryName: false,
        },
        l1mz: {
            parents: ['e0a2'],
            children: ['jwwb'],
            name: ['广州塔东', 'Canton Tower East'],
            branch: { left: [], right: [] },
            num: '02',
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        e0a2: {
            name: ['广州塔', 'Canton Tower'],
            secondaryName: false,
            num: '01',
            services: ['local'],
            parents: ['linestart'],
            children: ['l1mz'],
            branch: { left: [], right: [] },
            transfer: {
                info: [
                    [
                        ['guangzhou', 'gz3', '#ECA154', '#000', '三号线', 'Line 3'],
                        ['guangzhou', 'apm', '#00B5E2', '#fff', 'APM线', 'APM Line'],
                    ],
                ],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        jwwb: {
            name: ['猎德大桥南', 'Liede Bridge South'],
            secondaryName: false,
            num: '03',
            services: ['local'],
            parents: ['l1mz'],
            children: ['4ol1'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        '4ol1': {
            name: ['琶醍', 'Party Pier'],
            secondaryName: false,
            num: '04',
            services: ['local'],
            parents: ['jwwb'],
            children: ['hf10'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        hf10: {
            name: ['南风', 'Nanfeng'],
            secondaryName: false,
            num: '05',
            services: ['local'],
            parents: ['4ol1'],
            children: ['8gsk'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        '8gsk': {
            name: ['会展西', 'Canton Fair Complex West'],
            secondaryName: false,
            num: '06',
            services: ['local'],
            parents: ['hf10'],
            children: ['x3dc'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        x3dc: {
            name: ['会展中', 'Canton Fair Complex Middle'],
            secondaryName: false,
            num: '07',
            services: ['local'],
            parents: ['8gsk'],
            children: ['92ad'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        '92ad': {
            name: ['会展东', 'Canton Fair Complex East'],
            secondaryName: false,
            num: '08',
            services: ['local'],
            parents: ['x3dc'],
            children: ['fcq4'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        fcq4: {
            name: ['琶洲大桥南', 'Pazhou Bridge South'],
            secondaryName: false,
            num: '09',
            services: ['local'],
            parents: ['92ad'],
            children: ['wnje'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        wnje: {
            name: ['琶洲塔', 'Pazhou Pagoda'],
            secondaryName: false,
            num: '10',
            services: ['local'],
            parents: ['fcq4'],
            children: ['jw4f'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        jw4f: {
            name: ['万胜围', 'Wanshengwei'],
            secondaryName: false,
            num: '11',
            services: ['local'],
            parents: ['wnje'],
            children: ['lineend'],
            branch: { left: [], right: [] },
            transfer: {
                info: [
                    [
                        ['guangzhou', 'gz4', '#00843D', '#fff', '4号线', 'Line 4'],
                        ['guangzhou', 'gz8', '#008C95', '#fff', '8号线', 'Line 8'],
                    ],
                ],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
    },
    line_name: ['海珠有轨1号线', 'THZ1'],
    psd_num: '1',
    line_num: 'THZ1',
    info_panel_type: 'gz1421',
    direction_gz_x: 50,
    direction_gz_y: 70,
    customiseMTRDest: { isLegacy: false, terminal: false },
    svgWidth: { destination: 1000, runin: 1300, railmap: 1300, indoor: 800 },
    notesGZMTR: [],
    namePosMTR: { isStagger: true, isFlip: false },
};

export default params;
