export default {
    svg_height: 300,
    svg_width: 1150,
    svg_dest_width: 1150,
    show_outer: true,
    padding: 5,
    y_pc: 40,
    strip_pc: 90,
    branch_spacing: 44.44444444444444,
    theme: ['guangzhou', 'gz1', '#F3D03E', '#000'],
    direction: 'r',
    current_stn_idx: 'l9io',
    platform_num: '3',
    txt_bg_gap: 15,
    txt_flip: true,
    stn_list: {
        linestart: {
            parents: [],
            children: ['l1mz'],
            name: ['路綫左端', 'LEFT END'],
            change_type: 'none',
            branch: { left: [], right: [] },
        },
        lineend: {
            parents: ['iwf6'],
            children: [],
            name: ['路綫右端', 'RIGHT END'],
            change_type: 'none',
            branch: { left: [], right: [] },
        },
        l1mz: {
            parents: ['linestart'],
            children: ['ndua'],
            name: ['西塱', 'Xilang'],
            change_type: 'int2',
            interchange: [[['guangzhou', 'gfl', '#C4D600', '#fff', '广佛线', 'Guangfo Line']]],
            branch: { left: [], right: [] },
            num: '01',
        },
        iwf6: {
            children: ['lineend'],
            parents: ['57ve'],
            name: ['广州东站', 'Guangzhou East\\Railway Station'],
            change_type: 'int2',
            interchange: [[['guangzhou', 'gz3', '#ECA154', '#000', '3号线', 'Line 3']]],
            branch: { left: [], right: [] },
            num: '16',
        },
        '57ve': {
            parents: ['d2ch'],
            children: ['iwf6'],
            name: ['体育中心', 'Tianhe Sport Center'],
            change_type: 'none',
            branch: { left: [], right: [] },
            num: '15',
        },
        d2ch: {
            parents: ['rq4h'],
            children: ['57ve'],
            name: ['体育西路', 'Tiyu Xilu'],
            change_type: 'int2',
            interchange: [[['guangzhou', 'gz3', '#ECA154', '#000', '3号线', 'Line 3']]],
            branch: { left: [], right: [] },
            num: '14',
        },
        rq4h: {
            parents: ['n1ni'],
            children: ['d2ch'],
            name: ['杨箕', 'Yangji'],
            change_type: 'int2',
            interchange: [[['guangzhou', 'gz5', '#C5003E', '#fff', '5号线', 'Line 5']]],
            branch: { left: [], right: [] },
            num: '13',
        },
        n1ni: {
            parents: ['7kvg'],
            children: ['rq4h'],
            name: ['东山口', 'Dongshankou'],
            change_type: 'int2',
            interchange: [[['guangzhou', 'gz6', '#80225F', '#fff', '6号线', 'Line 6']]],
            branch: { left: [], right: [] },
            num: '12',
        },
        '7kvg': {
            parents: ['5o5y'],
            children: ['n1ni'],
            name: ['烈士陵园', "Martyrs' Park"],
            change_type: 'none',
            branch: { left: [], right: [] },
            num: '11',
        },
        l9io: {
            parents: ['2ifb'],
            children: ['5o5y'],
            name: ['公园前', 'Gongyuanqian'],
            change_type: 'int2',
            interchange: [[['guangzhou', 'gz2', '#00629B', '#fff', '2号线', 'Line 2']]],
            branch: { left: [], right: [] },
            num: '09',
        },
        '2ifb': {
            parents: ['lcjl'],
            children: ['l9io'],
            name: ['西门口', 'Ximenkou'],
            change_type: 'none',
            branch: { left: [], right: [] },
            num: '08',
        },
        lcjl: {
            parents: ['fbpn'],
            children: ['2ifb'],
            name: ['陈家祠', 'Chen Clan Academy'],
            change_type: 'int2',
            interchange: [[['guangzhou', 'gz8', '#008C95', '#fff', '8号线', 'Line 8']]],
            branch: { left: [], right: [] },
            num: '07',
        },
        fbpn: {
            parents: ['mclm'],
            children: ['lcjl'],
            name: ['长寿路', 'Changshou Lu'],
            change_type: 'none',
            branch: { left: [], right: [] },
            num: '06',
        },
        mclm: {
            parents: ['lx10'],
            children: ['fbpn'],
            name: ['黄沙', 'Huangsha'],
            change_type: 'int2',
            interchange: [[['guangzhou', 'gz6', '#80225F', '#fff', '6号线', 'Line 6']]],
            branch: { left: [], right: [] },
            num: '05',
        },
        lx10: {
            parents: ['yz8y'],
            children: ['mclm'],
            name: ['芳村', 'Fangcun'],
            change_type: 'none',
            branch: { left: [], right: [] },
            num: '04',
        },
        yz8y: {
            parents: ['ndua'],
            children: ['lx10'],
            name: ['花地湾', 'Huadiwan'],
            change_type: 'none',
            branch: { left: [], right: [] },
            num: '03',
        },
        ndua: {
            parents: ['l1mz'],
            children: ['yz8y'],
            name: ['坑口', 'Kengkou'],
            change_type: 'none',
            branch: { left: [], right: [] },
            num: '02',
        },
        '5o5y': {
            parents: ['l9io'],
            children: ['7kvg'],
            name: ['农讲所', 'Peasant Movement\\Institute'],
            change_type: 'none',
            branch: { left: [], right: [] },
            num: '10',
        },
    },
    line_name: ['1号线', 'Line 1'],
    dest_legacy: false,
    char_form: 'cn',
    psd_num: 1,
    line_num: 1,
};
