export default {
    svg_height: 300,
    svg_width: 1400,
    svg_dest_width: 1100,
    show_outer: true,
    padding: 4.216780871148593,
    y_pc: 40,
    strip_pc: 90,
    branch_spacing: 45,
    theme: ['guangzhou', 'gz4', '#00843D', '#fff'],
    direction: 'l',
    current_stn_idx: 'iwf6',
    platform_num: '2',
    txt_bg_gap: 15,
    txt_flip: true,
    stn_list: {
        linestart: {
            parents: [],
            children: ['1qsn'],
            name: ['路綫左端', 'LEFT END'],
            change_type: 'none',
            branch: { left: [], right: [] },
        },
        lineend: {
            parents: ['iwf6'],
            children: [],
            name: ['路綫右端', 'RIGHT END'],
            change_type: 'none',
            branch: { left: [], right: [] },
        },
        l1mz: {
            parents: ['6th3'],
            children: ['iwf6'],
            name: ['车陂', 'Chebei'],
            change_type: 'none',
            branch: { left: [], right: [] },
            num: '22',
        },
        iwf6: {
            children: ['lineend'],
            parents: ['l1mz'],
            name: ['黄村', 'Huangcun'],
            change_type: 'int2',
            branch: { left: [], right: [] },
            interchange: [[['guangzhou', 'gz21', '#201747', '21号线', 'Line 21']]],
            num: '23',
        },
        '6th3': {
            branch: { left: [], right: [] },
            parents: ['o594'],
            children: ['l1mz'],
            name: ['车陂南', 'Chebeinan'],
            change_type: 'int2',
            interchange: [[['guangzhou', 'gz5', '#C5003E', '5号线', 'Line 5']]],
            num: '21',
        },
        o594: {
            branch: { left: [], right: [] },
            parents: ['vqo5'],
            children: ['6th3'],
            name: ['万胜围', 'Wanshengwei'],
            change_type: 'int2',
            interchange: [[['guangzhou', 'gz8', '#008C95', '8号线', 'Line 8']]],
            num: '20',
        },
        vqo5: {
            branch: { left: [], right: [] },
            parents: ['ocv4'],
            children: ['o594'],
            name: ['官洲', 'Guanzhou'],
            change_type: 'none',
            num: '19',
        },
        ocv4: {
            branch: { left: [], right: [] },
            parents: ['6vxs'],
            children: ['vqo5'],
            name: ['大学城北', 'Higher Education\\Mega Center N.'],
            change_type: 'none',
            num: '18',
        },
        '6vxs': {
            branch: { left: [], right: [] },
            parents: ['hewc'],
            children: ['ocv4'],
            name: ['大学城南', 'Higher Education\\Mega Center S.'],
            change_type: 'int2',
            interchange: [[['guangzhou', 'gz7', '#97D700', '7号线', 'Line 7']]],
            num: '17',
        },
        hewc: {
            branch: { left: [], right: [] },
            parents: ['pe88'],
            children: ['6vxs'],
            name: ['新造', 'Xinzao'],
            change_type: 'none',
            num: '16',
        },
        pe88: {
            branch: { left: [], right: [] },
            parents: ['4olr'],
            children: ['hewc'],
            name: ['石碁', 'Shiqi'],
            change_type: 'none',
            num: '15',
        },
        '4olr': {
            branch: { left: [], right: [] },
            parents: ['581h'],
            children: ['pe88'],
            name: ['海傍', 'Haibang'],
            change_type: 'none',
            num: '14',
        },
        '581h': {
            branch: { left: [], right: [] },
            parents: ['a2zk'],
            children: ['4olr'],
            name: ['低涌', 'Dichong'],
            change_type: 'none',
            num: '13',
        },
        a2zk: {
            branch: { left: [], right: [] },
            parents: ['bhi4'],
            children: ['581h'],
            name: ['东涌', 'Dongchong'],
            change_type: 'none',
            num: '12',
        },
        bhi4: {
            branch: { left: [], right: [] },
            parents: ['2tzt'],
            children: ['a2zk'],
            name: ['庆盛', 'Qingsheng'],
            change_type: 'osi11_ul',
            interchange: [
                [],
                [
                    ['庆盛', 'Qingsheng'],
                    ['hongkong', 'hsr', '#9D968D', '高速铁路', 'High Speed Rail'],
                ],
            ],
            num: '11',
        },
        '2tzt': {
            branch: { left: [], right: [] },
            parents: ['u2e7'],
            children: ['bhi4'],
            name: ['黄阁汽车城', 'Huangge Auto Town'],
            change_type: 'none',
            num: '10',
        },
        u2e7: {
            branch: { left: [], right: [] },
            parents: ['1r1c'],
            children: ['2tzt'],
            name: ['黄阁', 'Huangge'],
            change_type: 'none',
            num: '09',
        },
        '1r1c': {
            branch: { left: [], right: [] },
            parents: ['jz7x'],
            children: ['u2e7'],
            name: ['蕉门', 'Jiaomen'],
            change_type: 'none',
            num: '08',
        },
        jz7x: {
            branch: { left: [], right: [] },
            parents: ['pluc'],
            children: ['1r1c'],
            name: ['金洲', 'Jinzhou'],
            change_type: 'none',
            num: '07',
        },
        pluc: {
            branch: { left: [], right: [] },
            parents: ['hroa'],
            children: ['jz7x'],
            name: ['飞沙角', 'Feishajiao'],
            change_type: 'none',
            num: '06',
        },
        hroa: {
            branch: { left: [], right: [] },
            parents: ['hebc'],
            children: ['pluc'],
            name: ['广隆', 'Guanglong'],
            change_type: 'none',
            num: '05',
        },
        hebc: {
            branch: { left: [], right: [] },
            parents: ['pprg'],
            children: ['hroa'],
            name: ['大涌', 'Dachong'],
            change_type: 'none',
            num: '04',
        },
        pprg: {
            branch: { left: [], right: [] },
            parents: ['r74n'],
            children: ['hebc'],
            name: ['塘坑', 'Tangkeng'],
            change_type: 'none',
            num: '03',
        },
        r74n: {
            branch: { left: [], right: [] },
            parents: ['1qsn'],
            children: ['pprg'],
            name: ['南横', 'Nanheng'],
            change_type: 'none',
            num: '02',
        },
        '1qsn': {
            branch: { left: [], right: [] },
            parents: ['linestart'],
            children: ['r74n'],
            name: ['南沙客运港', 'Nansha Passenger Port'],
            change_type: 'none',
            num: '01',
        },
    },
    line_name: ['4号线', 'Line 4'],
    dest_legacy: false,
    char_form: 'cn',
    psd_num: 1,
    line_num: '4',
};
