const params = {
    style: 'mtr',
    svg_height: 400,
    padding: 8.750201061605276,
    y_pc: 40,
    branch_spacing: 45,
    theme: ['shenzhen', 'sz3', '#00A9E0', '#fff'],
    direction: 'r',
    current_stn_idx: 'l1mz',
    platform_num: '2',
    stn_list: {
        linestart: {
            parents: [],
            children: ['l1mz'],
            name: ['路綫左端', 'LEFT END'],
            branch: { left: [], right: [] },
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            num: '00',
            secondaryName: false,
        },
        lineend: {
            parents: ['iwf6'],
            children: [],
            name: ['路綫右端', 'RIGHT END'],
            branch: { left: [], right: [] },
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            num: '00',
            secondaryName: false,
        },
        l1mz: {
            parents: ['linestart'],
            children: ['xzqy'],
            name: ['福保', 'Futian Bonded Area'],
            branch: { left: [], right: [] },
            num: '02',
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        iwf6: {
            children: ['lineend'],
            parents: ['dll0'],
            name: ['坪地六联', 'Pingdi Liulian'],
            branch: { left: [], right: [] },
            num: '01',
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        ok23: {
            name: ['石厦', 'Shixia'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['xzqy'],
            children: ['j4x0'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['shenzhen', 'sz7', '#0033A0', '#fff', '7号线', 'Line 7']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        j4x0: {
            name: ['购物公园', 'Shopping Park'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['ok23'],
            children: ['tm6e'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['shenzhen', 'sz1', '#00B140', '#fff', '1号线', 'Line 1']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        tm6e: {
            name: ['福田', 'Futian'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['j4x0'],
            children: ['h167'],
            branch: { left: [], right: [] },
            transfer: {
                info: [
                    [
                        ['shenzhen', 'sz2', '#B94700', '#fff', '2号线', 'Line 2'],
                        ['shenzhen', 'sz11', '#672146', '#fff', '11号线', 'Line 11'],
                    ],
                ],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        h167: {
            name: ['少年宫', "Children's Palace"],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['tm6e'],
            children: ['91dm'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['shenzhen', 'sz4', '#DA291C', '#fff', '4号线', 'Line 4']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        '91dm': {
            name: ['莲花村', 'Lianhuacun'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['h167'],
            children: ['afc7'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['shenzhen', 'sz10', '#F8779E', '#fff', '10号线', 'Line 10']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        afc7: {
            name: ['华新', 'Huaxin'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['91dm'],
            children: ['sbs0'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['shenzhen', 'sz7', '#0033A0', '#fff', '7号线', 'Line 7']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        sbs0: {
            name: ['通新岭', 'Tongxinling'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['afc7'],
            children: ['kczl'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['shenzhen', 'sz6', '#00C7B1', '#fff', '6号线', 'Line 6']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        kczl: {
            name: ['红岭', 'Hongling'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['sbs0'],
            children: ['49x2'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['shenzhen', 'sz9', '#7B6469', '#fff', '9号线', 'Line 9']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        '49x2': {
            name: ['老街', 'Laojie'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['kczl'],
            children: ['tiej'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['shenzhen', 'sz1', '#00B140', '#fff', '1号线', 'Line 1']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        fpug: {
            name: ['田贝', 'Tianbei'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['t4zq'],
            children: ['dzuw'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['shenzhen', 'sz7', '#0033A0', '#fff', '7号线', 'Line 7']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        '6aqd': {
            name: ['布吉', 'Buji'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['av5l'],
            children: ['wfja'],
            branch: { left: [], right: [] },
            transfer: {
                info: [
                    [
                        ['shenzhen', 'sz5', '#A05EB5', '#fff', '5号线', 'Line 5'],
                        ['other', 'other', '#F2C75C', '#fff', '14号线', 'Line 14'],
                    ],
                ],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        '1xqp': {
            name: ['大运', 'Universiade'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['tedw'],
            children: ['s697'],
            branch: { left: [], right: [] },
            transfer: {
                info: [
                    [
                        ['other', 'other', '#F2C75C', '#fff', '14号线', 'Line 14'],
                        ['other', 'other', '#1E22AA', '#fff', '16号线', 'Line 16'],
                    ],
                ],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        w4jw: {
            name: ['双龙', 'Shuanglong'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['3swy'],
            children: ['jsjp'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['other', 'other', '#1E22AA', '#fff', '16号线', 'Line 16']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        xzqy: {
            name: ['益田', 'Yitian'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['l1mz'],
            children: ['ok23'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        tiej: {
            name: ['晒布', 'Shaibu'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['49x2'],
            children: ['t4zq'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        t4zq: {
            name: ['翠竹', 'Cuizhu'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['tiej'],
            children: ['fpug'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        dzuw: {
            name: ['水贝', 'Shuibei'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['fpug'],
            children: ['av5l'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        av5l: {
            name: ['草埔', 'Caopu'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['dzuw'],
            children: ['6aqd'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        wfja: {
            name: ['木棉湾', 'Mumianwan'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['6aqd'],
            children: ['on2d'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        on2d: {
            name: ['大芬', 'Dafeng'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['wfja'],
            children: ['pxz2'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        pxz2: {
            name: ['丹竹头', 'Danzhutou'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['on2d'],
            children: ['wo1k'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        wo1k: {
            name: ['六约', 'Liuyue'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['pxz2'],
            children: ['4v9e'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        tedw: {
            name: ['荷坳', "He'ao"],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['o1sn'],
            children: ['1xqp'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        o1sn: {
            name: ['永湖', 'Yonghu'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['u6xs'],
            children: ['tedw'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        u6xs: {
            name: ['横岗', 'Henggang'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['4v9e'],
            children: ['o1sn'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        '4v9e': {
            name: ['塘坑', 'Tangkeng'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['wo1k'],
            children: ['u6xs'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        '3swy': {
            name: ['南联', 'Nanlian'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['p1ie'],
            children: ['w4jw'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        p1ie: {
            name: ['龙城广场', 'Longcheng Square'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['8ufm'],
            children: ['3swy'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        '8ufm': {
            name: ['吉祥', 'Jixiang'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['s697'],
            children: ['p1ie'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        s697: {
            name: ['爱联', 'Ailian'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['1xqp'],
            children: ['8ufm'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        jsjp: {
            name: ['梨园', 'Liyuan'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['w4jw'],
            children: ['2cf8'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        dll0: {
            name: ['富坪', 'Fuping'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['46my'],
            children: ['iwf6'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        '46my': {
            name: ['白石塘', 'Baishitang'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['72fu'],
            children: ['dll0'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        '72fu': {
            name: ['低碳城', 'Lower Carbon City'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['e8vm'],
            children: ['46my'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        e8vm: {
            name: ['坪西', 'Pingxi'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['2cf8'],
            children: ['72fu'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        '2cf8': {
            name: ['新生', 'Xinsheng'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['jsjp'],
            children: ['e8vm'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
    },
    line_name: ['3号线', 'Line 3'],
    psd_num: '1',
    line_num: 'TW',
    info_panel_type: 'gz28',
    direction_gz_x: 50,
    direction_gz_y: 70,
    customiseMTRDest: { isLegacy: false, terminal: false },
    svgWidth: { destination: 1000, runin: 1000, railmap: 3500 },
    notesGZMTR: [],
    namePosMTR: { isStagger: true, isFlip: false },
};

export default params;
