const params = {
    style: 'mtr',
    svg_height: 300,
    padding: 8.750201061605276,
    y_pc: 40,
    branch_spacing: 45,
    theme: ['shenzhen', 'sz4', '#DA291C', '#fff'],
    direction: 'r',
    current_stn_idx: 'l1mz',
    platform_num: '2',
    stn_list: {
        linestart: {
            parents: [],
            children: ['l1mz'],
            name: ['路綫左端', 'LEFT END'],
            branch: { left: [], right: [] },
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            num: '00',
            secondaryName: false,
        },
        lineend: {
            parents: ['jhpu'],
            children: [],
            name: ['路綫右端', 'RIGHT END'],
            branch: { left: [], right: [] },
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            num: '00',
            secondaryName: false,
        },
        l1mz: {
            parents: ['linestart'],
            children: ['iwf6'],
            name: ['牛湖', 'Niuhu'],
            branch: { left: [], right: [] },
            num: '02',
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        iwf6: {
            children: ['qct5'],
            parents: ['l1mz'],
            name: ['观澜湖', 'Mission Hills'],
            branch: { left: [], right: [] },
            num: '01',
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        qct5: {
            name: ['松元厦', 'Songyuanxia'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['iwf6'],
            children: ['57tn'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        '57tn': {
            name: ['观澜', 'Guanlan'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['qct5'],
            children: ['tibd'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        tibd: {
            name: ['长湖', 'Changhu'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['57tn'],
            children: ['vsvj'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        vsvj: {
            name: ['茜坑', 'Xikeng'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['tibd'],
            children: ['lit9'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        lit9: {
            name: ['竹村', 'Zhucun'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['vsvj'],
            children: ['hm52'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        hm52: {
            name: ['清湖北', 'Qinghu North'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['lit9'],
            children: ['027g'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        '027g': {
            name: ['清湖', 'Qinghu'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['hm52'],
            children: ['2saa'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        '2saa': {
            name: ['龙华', 'Longhua'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['027g'],
            children: ['bpol'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        bpol: {
            name: ['龙胜', 'Longsheng'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['2saa'],
            children: ['mlr0'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        mlr0: {
            name: ['上塘', 'Shangtang'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['bpol'],
            children: ['qtwk'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        qtwk: {
            name: ['红山', 'Hongshan'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['mlr0'],
            children: ['q4ut'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['shenzhen', 'sz6', '#00C7B1', '#fff', '6号线', 'Line 6']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        q4ut: {
            name: ['深圳北站', 'Shenzhen North Railway Station'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['qtwk'],
            children: ['0aok'],
            branch: { left: [], right: [] },
            transfer: {
                info: [
                    [
                        ['shenzhen', 'sz5', '#A05EB5', '#fff', '5号线', 'Line 5'],
                        ['shenzhen', 'sz6', '#00C7B1', '#fff', '6号线', 'Line 6'],
                    ],
                ],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        '0aok': {
            name: ['白石龙', 'Baishilong'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['q4ut'],
            children: ['7c9b'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        '7c9b': {
            name: ['民乐', 'Minle'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['0aok'],
            children: ['jk7s'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        jk7s: {
            name: ['上梅林', 'Shangmeilin'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['7c9b'],
            children: ['o59l'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['shenzhen', 'sz9', '#7B6469', '#fff', '9号线', 'Line 9']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        o59l: {
            name: ['莲花北', 'Lianhua North'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['jk7s'],
            children: ['3w6y'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
        },
        '3w6y': {
            name: ['少年宫', "Children's Palace"],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['o59l'],
            children: ['wr5o'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['shenzhen', 'sz3', '#00A9E0', '#fff', '3号线', 'Line 3']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        wr5o: {
            name: ['市民中心', 'Civic Center'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['3w6y'],
            children: ['q3st'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['shenzhen', 'sz2', '#B94700', '#fff', '2号线', 'Line 2']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        q3st: {
            name: ['会展中心', 'Convention Exhibition Center'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['wr5o'],
            children: ['xl4a'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['shenzhen', 'sz1', '#00B140', '#fff', '1号线', 'Line 1']]],
                tick_direc: 'r',
                paid_area: false,
                osi_names: [],
            },
            facility: '',
        },
        xl4a: {
            name: ['福民', 'Fumin'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['q3st'],
            children: ['jhpu'],
            branch: { left: [], right: [] },
            transfer: {
                info: [
                    [
                        ['shenzhen', 'sz7', '#0033A0', '#fff', '7号线', 'Line 7'],
                        ['shenzhen', 'sz10', '#F8779E', '#fff', '10号线', 'Line 10'],
                    ],
                ],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        jhpu: {
            name: ['福田口岸', 'Futian Checkpoint'],
            secondaryName: false,
            num: '00',
            services: ['local'],
            parents: ['xl4a'],
            children: ['lineend'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['shenzhen', 'sz10', '#F8779E', '#fff', '10号线', 'Line 10']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
    },
    line_name: ['4号线', 'Line 4'],
    psd_num: '1',
    line_num: 'TW',
    info_panel_type: 'gz28',
    direction_gz_x: 50,
    direction_gz_y: 70,
    customiseMTRDest: { isLegacy: false, terminal: false },
    svgWidth: { destination: 1000, runin: 1000, railmap: 2000 },
    notesGZMTR: [],
    namePosMTR: { isStagger: true, isFlip: false },
};

export default params;
