const params = {
    svg_height: 400,
    padding: 3.08,
    y_pc: 46.04,
    branch_spacing: 45,
    theme: ['hongkong', 'twl', '#E2231A', '#fff'],
    direction: 'r',
    current_stn_idx: 'iwf6',
    platform_num: '2',
    stn_list: {
        linestart: {
            parents: [],
            children: ['iwf6'],
            name: ['路綫右端', 'RIGHT END'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [[]],
            },
            services: ['local'],
            facility: '',
            num: '00',
            secondaryName: false,
        },
        lineend: {
            parents: ['vc00'],
            children: [],
            name: ['路綫左端', 'LEFT END'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [[]],
            },
            services: ['local'],
            facility: '',
            num: '31',
            secondaryName: false,
        },
        l1mz: {
            parents: ['iwf6'],
            children: ['b164'],
            name: ['郑大科技园', 'Zhengzhou University Sci-tech Park'],
            branch: {
                left: [],
                right: [],
            },
            num: '02',
            transfer: {
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [[]],
            },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        iwf6: {
            children: ['l1mz'],
            parents: ['linestart'],
            name: ['河南工业大学', 'Henan University of Technology'],
            branch: {
                left: [],
                right: [],
            },
            num: '01',
            transfer: {
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [[]],
            },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        vc00: {
            name: ['河南大学新区', 'New Campus of Henan University'],
            secondaryName: false,
            num: '30',
            services: ['local'],
            parents: ['gv6z'],
            children: ['lineend'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        gv6z: {
            name: ['文苑北路', 'Wenyuan Road (N)'],
            secondaryName: false,
            num: '29',
            services: ['local'],
            parents: ['p9q7'],
            children: ['vc00'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        p9q7: {
            name: ['龙子湖', 'Long Zi Lake'],
            secondaryName: false,
            num: '28',
            services: ['local'],
            parents: ['phqt'],
            children: ['gv6z'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[['other', 'other', '#1ce4f2', '#fff', '12号线', 'Line 12']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        phqt: {
            name: ['市体育中心', 'Zhengzhou Sports Center'],
            secondaryName: false,
            num: '27',
            services: ['local'],
            parents: ['kz8k'],
            children: ['p9q7'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        kz8k: {
            name: ['博学路', 'Boxue Road'],
            secondaryName: false,
            num: '26',
            services: ['local'],
            parents: ['izkb'],
            children: ['phqt'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        izkb: {
            name: ['郑州东站', 'Zhengzhou East Railway station'],
            secondaryName: false,
            num: '25',
            services: ['local'],
            parents: ['nuxn'],
            children: ['kz8k'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [
                    [
                        ['guangzhou', 'gz4', '#00843D', '#fff', '5号线', 'Line 5'],
                        ['guangzhou', 'gfl', '#C4D600', '#fff', '8号线', 'Line 8'],
                    ],
                ],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: 'hsr',
        },
        nuxn: {
            name: ['东风南路', 'Dongfeng Road (S)'],
            secondaryName: false,
            num: '24',
            services: ['local'],
            parents: ['qdfx'],
            children: ['izkb'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[['other', 'other', '#1ce4f2', '#fff', '12号线', 'Line 12']]],
                tick_direc: 'l',
                paid_area: false,
                osi_names: [],
            },
            facility: '',
        },
        coxj: {
            name: ['黄河南路', 'Huanghe Road (S)'],
            secondaryName: false,
            num: '22',
            services: ['local'],
            parents: ['s15a'],
            children: ['qdfx'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        s15a: {
            name: ['会展中心', 'Zhengzhou International \\Convention and Exhibition Center'],
            secondaryName: false,
            num: '21',
            services: ['local'],
            parents: ['c8b7'],
            children: ['coxj'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[['guangzhou', 'gz18', '#0047BA', '#fff', '4号线', 'Line 4']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        c8b7: {
            name: ['民航路', 'Minhang Road'],
            secondaryName: false,
            num: '20',
            services: ['local'],
            parents: ['kqol'],
            children: ['s15a'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        kqol: {
            name: ['燕庄', 'Yan Zhuang'],
            secondaryName: false,
            num: '19',
            services: ['local'],
            parents: ['zprw'],
            children: ['c8b7'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[['guangzhou', 'gz6', '#80225F', '#fff', '6号线', 'Line 6']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        zprw: {
            name: ['紫荆山', 'Zi Jing Shan'],
            secondaryName: false,
            num: '18',
            services: ['local'],
            parents: ['lesa'],
            children: ['kqol'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[['other', 'other', '#F3D03E', '#fff', '2号线', 'Line 2']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        lesa: {
            name: ['人民路', 'Renmin Road'],
            secondaryName: false,
            num: '17',
            services: ['local'],
            parents: ['wown'],
            children: ['zprw'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        wown: {
            name: ['二七广场', 'Er Qi Square'],
            secondaryName: false,
            num: '16',
            services: ['local'],
            parents: ['24m5'],
            children: ['lesa'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[['other', 'other', '#ECA154', '#fff', '3号线', 'Line 3']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        '24m5': {
            name: ['郑州火车站', 'Zhengzhou Railway Station'],
            secondaryName: false,
            num: '15',
            services: ['local'],
            parents: ['2ohc'],
            children: ['wown'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[['other', 'other', '#a42e28', '#fff', '10号线', 'Line 10']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        '2ohc': {
            name: ['医学院', 'Medical College of Zhengzhou University'],
            secondaryName: false,
            num: '14',
            services: ['local'],
            parents: ['s4bt'],
            children: ['24m5'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [
                    [
                        ['other', 'other', '#a42e28', '#fff', '10号线', 'Line 10'],
                        ['other', 'other', '#f79102', '#fff', '7号线', 'Line 7'],
                    ],
                ],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        s4bt: {
            name: ['绿城广场', 'Lv Cheng Square'],
            secondaryName: false,
            num: '13',
            services: ['local'],
            parents: ['265f'],
            children: ['2ohc'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[['other', 'other', '#a42e28', '#fff', '10号线', 'Line 10']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        '265f': {
            name: ['碧沙岗', 'Bi Sha Gang'],
            secondaryName: false,
            num: '12',
            services: ['local'],
            parents: ['crby'],
            children: ['s4bt'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        crby: {
            name: ['五一公园', 'Wu Yi Park'],
            secondaryName: false,
            num: '11',
            services: ['local'],
            parents: ['io1r'],
            children: ['265f'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[['guangzhou', 'gz4', '#00843D', '#fff', '5号线', 'Line 5']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        io1r: {
            name: ['秦岭路', 'Qinling Road'],
            secondaryName: false,
            num: '10',
            services: ['local'],
            parents: ['r8wa'],
            children: ['crby'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        r8wa: {
            name: ['西三环', 'Third Ring Road (W)'],
            secondaryName: false,
            num: '09',
            services: ['local'],
            parents: ['hhgb'],
            children: ['io1r'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        hhgb: {
            name: ['西流湖', 'Xi Liu Lake'],
            secondaryName: false,
            num: '08',
            services: ['local'],
            parents: ['o3mf'],
            children: ['r8wa'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        o3mf: {
            name: ['市民中心', 'Zhengzhou Civic Center'],
            secondaryName: false,
            num: '07',
            services: ['local'],
            parents: ['xrfn'],
            children: ['hhgb'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        '6o48': {
            name: ['兰寨', 'Lan Zhai'],
            secondaryName: false,
            num: '05',
            services: ['local'],
            parents: ['mya8'],
            children: ['xrfn'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        mya8: {
            name: ['梧桐街', 'Wutong Street'],
            secondaryName: false,
            num: '04',
            services: ['local'],
            parents: ['b164'],
            children: ['6o48'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        b164: {
            name: ['郑州大学', 'Zhengzhou University'],
            secondaryName: false,
            num: '03',
            services: ['local'],
            parents: ['l1mz'],
            children: ['mya8'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[['guangzhou', 'gfl', '#C4D600', '#fff', '8号线', 'Line 8']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        qdfx: {
            name: ['农业南路', 'Nongye Road (S)'],
            secondaryName: false,
            num: '23',
            services: ['local'],
            parents: ['coxj'],
            children: ['nuxn'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        xrfn: {
            name: ['铁炉', 'Tie Lu'],
            secondaryName: false,
            num: '06',
            services: ['local'],
            parents: ['6o48'],
            children: ['o3mf'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[['chengdu', 'cd12', '#772583', '#fff', '14号线', 'Line 14']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
    },
    line_name: ['1号线', 'Line 1'],
    psd_num: '1',
    line_num: '1',
    info_panel_type: 'gz28',
    direction_gz_x: 50,
    direction_gz_y: 76.4,
    customiseMTRDest: {
        isLegacy: false,
        terminal: false,
    },
    svgWidth: {
        destination: 1500,
        runin: 1700,
        railmap: 3000,
        indoor: 2500,
    },
    notesGZMTR: [
        [
            '6号线、7号线、8号线、10号线、12号线暂缓开通',
            'Line 6, Line 7, Line 8, Line 10 and Line 12 have been suspended',
            0,
            5.5,
            false,
        ],
    ],
    namePosMTR: {
        isStagger: true,
        isFlip: false,
    },
    style: 'gzmtr',
};

export default params;
