const params = {
    svg_height: 350,
    padding: 8.750201061605276,
    y_pc: 40,
    branch_spacing: 45,
    theme: ['chengdu', 'cd12', '#772583', '#fff'],
    direction: 'r',
    current_stn_idx: '4oej',
    platform_num: '2',
    stn_list: {
        linestart: {
            parents: [],
            children: ['iwf6'],
            name: ['路綫右端', 'RIGHT END'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [[]],
            },
            services: ['local'],
            facility: '',
            num: '00',
            secondaryName: false,
        },
        lineend: {
            parents: ['l1mz'],
            children: [],
            name: ['路綫左端', 'LEFT END'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [[]],
            },
            services: ['local'],
            facility: '',
            num: '07',
            secondaryName: false,
        },
        l1mz: {
            parents: ['1t8g'],
            children: ['lineend'],
            name: ['莲湖', 'Lian Lake'],
            branch: {
                left: [],
                right: [],
            },
            num: '06',
            transfer: {
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [[]],
            },
            services: ['local'],
            facility: '',
            secondaryName: ['暂缓开通', 'Stay Open'],
        },
        iwf6: {
            children: ['tl1k'],
            parents: ['linestart'],
            name: ['须水', 'Xu Shui River'],
            branch: {
                left: [],
                right: [],
            },
            num: '01',
            transfer: {
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [[]],
            },
            services: ['local'],
            facility: '',
            secondaryName: ['暂缓开通', 'Stay Open'],
        },
        tl1k: {
            name: ['铁炉', 'Tie Lu'],
            secondaryName: false,
            num: '02',
            services: ['local'],
            parents: ['iwf6'],
            children: ['vdxz'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[['hongkong', 'twl', '#E2231A', '#fff', '1号线', 'Line 1']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        vdxz: {
            name: ['市民大道', 'Shimin Road'],
            secondaryName: ['暂缓开通', 'Stay Open'],
            num: '03',
            services: ['local'],
            parents: ['tl1k'],
            children: ['4oej'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        '4oej': {
            name: ['市委党校', 'Zhengzhou \\Municipal Party School'],
            secondaryName: false,
            num: '04',
            services: ['local'],
            parents: ['vdxz'],
            children: ['1t8g'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        '1t8g': {
            name: ['奥体中心', 'Zhengzhou \\Olympic Sports Center'],
            secondaryName: false,
            num: '05',
            services: ['local'],
            parents: ['4oej'],
            children: ['l1mz'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[['guangzhou', 'gz6', '#80225F', '#fff', '6号线', 'Line 6']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
    },
    line_name: ['14号线', 'Line 14'],
    psd_num: '1',
    line_num: '14',
    info_panel_type: 'gz28',
    direction_gz_x: 50,
    direction_gz_y: 70,
    customiseMTRDest: {
        isLegacy: false,
        terminal: false,
    },
    svgWidth: {
        destination: 1000,
        runin: 1500,
        railmap: 2000,
        indoor: 800,
    },
    notesGZMTR: [['6号线暂缓开通', 'Line 6 has been suspended', 0, 7, false]],
    namePosMTR: {
        isStagger: true,
        isFlip: false,
    },
    style: 'gzmtr',
};

export default params;
