const params = {
    svg_height: 350,
    padding: 3.79,
    y_pc: 40,
    branch_spacing: 45,
    theme: ['other', 'other', '#844F7C', '#fff'],
    direction: 'r',
    current_stn_idx: '4oej',
    platform_num: '2',
    stn_list: {
        linestart: {
            parents: [],
            children: ['iwf6'],
            name: ['路綫右端', 'RIGHT END'],
            branch: { left: [], right: [] },
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            num: '00',
            secondaryName: false,
            loop_pivot: false,
        },
        lineend: {
            parents: ['l1mz'],
            children: [],
            name: ['路綫左端', 'LEFT END'],
            branch: { left: [], right: [] },
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            num: '07',
            secondaryName: false,
            loop_pivot: false,
        },
        l1mz: {
            parents: ['1t8g'],
            children: ['lineend'],
            name: ['莲湖', 'Lian Lake'],
            branch: { left: [], right: [] },
            num: '06',
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            secondaryName: ['暂缓开通', 'Stay Open'],
            loop_pivot: false,
        },
        iwf6: {
            children: ['tl1k'],
            parents: ['linestart'],
            name: ['须水', 'Xushui River'],
            branch: { left: [], right: [] },
            num: '01',
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            secondaryName: ['暂缓开通', 'Stay Open'],
            loop_pivot: false,
        },
        tl1k: {
            name: ['铁炉', 'Tie Lu'],
            secondaryName: false,
            num: '02',
            services: ['local'],
            parents: ['iwf6'],
            children: ['vdxz'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['other', 'other', '#D20200', '#fff', '1号线', 'Line 1']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
            loop_pivot: false,
        },
        vdxz: {
            name: ['市民大道', 'Shimin Ave'],
            secondaryName: ['暂缓开通', 'Stay Open'],
            num: '03',
            services: ['local'],
            parents: ['tl1k'],
            children: ['4oej'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
            loop_pivot: false,
        },
        '4oej': {
            name: ['市委党校', 'Zhengzhou Party \\School of CPC'],
            secondaryName: false,
            num: '04',
            services: ['local'],
            parents: ['vdxz'],
            children: ['1t8g'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['other', 'other', '#B15F56', '#fff', '10号线', 'Line 10']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
            loop_pivot: false,
        },
        '1t8g': {
            name: ['奥体中心', 'Zhengzhou \\Olympic Sports Center'],
            secondaryName: false,
            num: '05',
            services: ['local'],
            parents: ['4oej'],
            children: ['l1mz'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['other', 'other', '#852081', '#fff', '6号线', 'Line 6']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
            loop_pivot: false,
        },
    },
    line_name: ['14号线', 'Line 14'],
    psd_num: '1',
    line_num: '14',
    info_panel_type: 'gz28',
    direction_gz_x: 50,
    direction_gz_y: 70,
    customiseMTRDest: { isLegacy: false, terminal: false },
    svgWidth: { destination: 1000, runin: 1500, railmap: 1900, indoor: 800 },
    notesGZMTR: [['6号线、10号线暂缓开通', 'Line 6，Line 10 has been suspended', 0, 4.5, false]],
    namePosMTR: { isStagger: true, isFlip: false },
    style: 'gzmtr',
    coline: [],
    loop: false,
    loop_info: { bank: true, left_and_right_factor: 1, bottom_factor: 1 },
};

export default params;
