const params = {
    svg_height: 350,
    padding: 3.97,
    y_pc: 50.2,
    branch_spacing: 45,
    theme: ['other', 'other', '#CB5100', '#fff'],
    direction: 'r',
    current_stn_idx: 'r9mx',
    platform_num: '2',
    stn_list: {
        linestart: {
            parents: [],
            children: ['r9mx'],
            name: ['路綫左端', 'LEFT END'],
            branch: { left: [], right: [] },
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            num: '00',
            secondaryName: false,
            loop_pivot: false,
        },
        lineend: {
            parents: ['isy4'],
            children: [],
            name: ['路綫右端', 'RIGHT END'],
            branch: { left: [], right: [] },
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            num: '26',
            secondaryName: false,
            loop_pivot: false,
        },
        l1mz: {
            parents: ['pl80'],
            children: ['evpi'],
            name: ['兴隆铺', 'Xing Long Pu'],
            branch: { left: [], right: [] },
            num: '03',
            transfer: { tick_direc: 'r', paid_area: true, osi_names: [], info: [[]] },
            services: ['local'],
            facility: '',
            secondaryName: false,
            loop_pivot: false,
        },
        '5hx2': {
            name: ['营岗', 'Ying Gang'],
            secondaryName: false,
            num: '21',
            services: ['local'],
            parents: ['qbqn'],
            children: ['gks3'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
            loop_pivot: false,
        },
        qbqn: {
            name: ['圃田西', 'Pu Tian (W)'],
            secondaryName: false,
            num: '20',
            services: ['local'],
            parents: ['lu8q'],
            children: ['5hx2'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['other', 'other', '#E6E394', '#fff', '8号线', 'Line 8']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
            loop_pivot: false,
        },
        lu8q: {
            name: ['省骨科医院', 'Henan Orthopaedic Hospital'],
            secondaryName: false,
            num: '19',
            services: ['local'],
            parents: ['plxy'],
            children: ['qbqn'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['other', 'other', '#25AC74', '#fff', '5号线', 'Line 5']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
            loop_pivot: false,
        },
        plxy: {
            name: ['东周', 'Dong Zhou'],
            secondaryName: false,
            num: '18',
            services: ['local'],
            parents: ['y1gf'],
            children: ['lu8q'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
            loop_pivot: false,
        },
        y1gf: {
            name: ['西周', 'Xi Zhou'],
            secondaryName: false,
            num: '17',
            services: ['local'],
            parents: ['fiag'],
            children: ['plxy'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['other', 'other', '#225e9e', '#fff', '12号线', 'Line 12']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
            loop_pivot: false,
        },
        fiag: {
            name: ['通泰路', 'Tongtai Road'],
            secondaryName: false,
            num: '16',
            services: ['local'],
            parents: ['13yo'],
            children: ['y1gf'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
            loop_pivot: false,
        },
        '13yo': {
            name: ['东十里铺', 'Dong Shi Li Pu'],
            secondaryName: false,
            num: '15',
            services: ['local'],
            parents: ['45bu'],
            children: ['fiag'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['other', 'other', '#3792D6', '#fff', '4号线', 'Line 4']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
            loop_pivot: false,
        },
        '45bu': {
            name: ['凤凰台', 'Feng Huang Tai'],
            secondaryName: false,
            num: '14',
            services: ['local'],
            parents: ['1rt3'],
            children: ['13yo'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
            loop_pivot: false,
        },
        '1rt3': {
            name: ['博览中心', 'Zhongyuan International Expo Center'],
            secondaryName: false,
            num: '13',
            services: ['local'],
            parents: ['2zpf'],
            children: ['45bu'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['other', 'other', '#852081', '#fff', '6号线', 'Line 6']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
            loop_pivot: false,
        },
        '2zpf': {
            name: ['郑州文庙', 'Zhengzhou Wen Miao'],
            secondaryName: false,
            num: '12',
            services: ['local'],
            parents: ['776d'],
            children: ['1rt3'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
            loop_pivot: false,
        },
        '776d': {
            name: ['东大街', 'Dongdajie Street'],
            secondaryName: false,
            num: '11',
            services: ['local'],
            parents: ['euag'],
            children: ['2zpf'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['other', 'other', '#D28F00', '#fff', '2号线', 'Line 2']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
            loop_pivot: false,
        },
        euag: {
            name: ['西大街', 'Xidajie Street'],
            secondaryName: false,
            num: '10',
            services: ['local'],
            parents: ['l988'],
            children: ['776d'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
            loop_pivot: false,
        },
        l988: {
            name: ['二七广场', 'Erqi Square'],
            secondaryName: false,
            num: '09',
            services: ['local'],
            parents: ['olls'],
            children: ['euag'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['other', 'other', '#D20200', '#fff', '1号线', 'Line 1']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
            loop_pivot: false,
        },
        gc0z: {
            name: ['大石桥', 'Da Shi Qiao'],
            secondaryName: false,
            num: '07',
            services: ['local'],
            parents: ['c96g'],
            children: ['olls'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['other', 'other', '#C0955A', '#fff', '7号线', 'Line 7']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
            loop_pivot: false,
        },
        c96g: {
            name: ['海滩寺', 'Hai Tan Si'],
            secondaryName: false,
            num: '06',
            services: ['local'],
            parents: ['76hr'],
            children: ['gc0z'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['other', 'other', '#25AC74', '#fff', '5号线', 'Line 5']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
            loop_pivot: false,
        },
        '76hr': {
            name: ['南阳新村', 'Nan Yang Xin Cun'],
            secondaryName: false,
            num: '05',
            services: ['local'],
            parents: ['evpi'],
            children: ['c96g'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
            loop_pivot: false,
        },
        evpi: {
            name: ['同乐', 'Tong Le'],
            secondaryName: false,
            num: '04',
            services: ['local'],
            parents: ['l1mz'],
            children: ['76hr'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['other', 'other', '#E6E394', '#fff', '8号线', 'Line 8']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
            loop_pivot: false,
        },
        r9mx: {
            name: ['省体育中心', 'Henan Sports Center'],
            secondaryName: false,
            num: '01',
            services: ['local'],
            parents: ['linestart'],
            children: ['pl80'],
            branch: { left: [], right: [] },
            transfer: {
                info: [[['other', 'other', '#3792D6', '#fff', '4号线', 'Line 4']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
            loop_pivot: false,
        },
        pl80: {
            name: ['王砦', 'Wang Zhai'],
            secondaryName: false,
            num: '02',
            services: ['local'],
            parents: ['r9mx'],
            children: ['l1mz'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
            loop_pivot: false,
        },
        olls: {
            name: ['人民公园', 'Renmin Park'],
            secondaryName: false,
            num: '08',
            services: ['local'],
            parents: ['gc0z'],
            children: ['l988'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
            loop_pivot: false,
        },
        isy4: {
            name: ['滨河新城南', 'International Eco-Aquapolis \\Zhengzhou China (S)'],
            secondaryName: ['暂缓开通', 'Stay Open'],
            num: '25',
            services: ['local'],
            parents: ['6e35'],
            children: ['lineend'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
            loop_pivot: false,
        },
        '6e35': {
            name: ['司赵', 'Si Zhao'],
            secondaryName: ['暂缓开通', 'Stay Open'],
            num: '24',
            services: ['local'],
            parents: ['v61f'],
            children: ['isy4'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
            loop_pivot: false,
        },
        v61f: {
            name: ['滨河新城', 'International Eco-Aquapolis \\Zhengzhou China'],
            secondaryName: ['暂缓开通', 'Stay Open'],
            num: '23',
            services: ['local'],
            parents: ['gks3'],
            children: ['6e35'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
            loop_pivot: false,
        },
        gks3: {
            name: ['潮河', 'Chao River'],
            secondaryName: ['暂缓开通', 'Stay Open'],
            num: '22',
            services: ['local'],
            parents: ['5hx2'],
            children: ['v61f'],
            branch: { left: [], right: [] },
            transfer: { info: [[]], tick_direc: 'r', paid_area: true, osi_names: [] },
            facility: '',
            loop_pivot: false,
        },
    },
    line_name: ['3号线', 'Line 3'],
    psd_num: '1',
    line_num: '3',
    info_panel_type: 'gz28',
    direction_gz_x: 50,
    direction_gz_y: 75.45,
    customiseMTRDest: { isLegacy: false, terminal: ['营岗', 'YINGGANG'] },
    svgWidth: { destination: 1500, runin: 1500, railmap: 3000, indoor: 1800 },
    notesGZMTR: [['6号线、7号线、8号线暂缓开通', 'Line 6, Line 7, Line 8 have been suspended', 0, 6.5, false]],
    namePosMTR: { isStagger: true, isFlip: false },
    style: 'gzmtr',
    coline: [],
    loop: false,
    loop_info: { bank: true, left_and_right_factor: 1, bottom_factor: 1 },
};

export default params;
