const params = {
    svg_height: 400,
    padding: 3.08,
    y_pc: 40,
    branch_spacing: 44.44444444444444,
    theme: ['guangzhou', 'gz18', '#0047BA', '#fff'],
    direction: 'r',
    current_stn_idx: 'a5',
    platform_num: '2',
    stn_list: {
        linestart: {
            parents: [],
            children: ['a5'],
            name: ['路綫左端', 'LEFT END'],
            branch: {
                left: [],
                right: [],
            },
            num: '00',
            transfer: {
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [[]],
            },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        a5: {
            parents: ['linestart'],
            children: ['a10'],
            name: ['老鸦陈', 'Lao Ya Chen'],
            branch: {
                left: [],
                right: [],
            },
            num: '01',
            transfer: {
                tick_direc: 'l',
                paid_area: true,
                osi_names: [['天河路', 'Tianhe Lu']],
                info: [[], [['guangzhou', 'gz10', '#7D9BC1', '#fff', '10号线', 'Line 10']]],
            },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        a10: {
            parents: ['a5'],
            children: ['j0wm'],
            name: ['省体育中心', 'Henan Sports Center'],
            branch: {
                left: [],
                right: [],
            },
            num: '02',
            transfer: {
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [[['other', 'other', '#ECA154', '#fff', '3号线', 'Line 3']]],
            },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        lineend: {
            parents: ['hf3z'],
            children: [],
            name: ['路綫右端', 'RIGHT END'],
            branch: {
                left: [],
                right: [],
            },
            num: '28',
            transfer: {
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [[]],
            },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        j0wm: {
            name: ['北二十里铺', 'Bei Er Shi Li Pu'],
            secondaryName: false,
            num: '03',
            services: ['local'],
            parents: ['a10'],
            children: ['eal0'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        hf3z: {
            name: ['郎庄', 'Lang Zhuang'],
            secondaryName: false,
            num: '27',
            services: ['local'],
            parents: ['q9yj'],
            children: ['lineend'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        c06y: {
            name: ['货站街', 'Huozhan Street'],
            secondaryName: false,
            num: '22',
            services: ['local'],
            parents: ['x24d'],
            children: ['uiml'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        x24d: {
            name: ['东十里铺', 'Dong Shi Li Pu'],
            secondaryName: false,
            num: '21',
            services: ['local'],
            parents: ['lmfv'],
            children: ['c06y'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[['other', 'other', '#ECA154', '#fff', '3号线', 'Line 3']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        lmfv: {
            name: ['商鼎路', 'Shangding Road'],
            secondaryName: false,
            num: '20',
            services: ['local'],
            parents: ['p1x7'],
            children: ['x24d'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        p1x7: {
            name: ['会展中心', 'Zhengzhou International \\Convention and Exhibition Center'],
            secondaryName: false,
            num: '19',
            services: ['local'],
            parents: ['kly4'],
            children: ['lmfv'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[['hongkong', 'twl', '#E2231A', '#fff', '1号线', 'Line 1']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        kly4: {
            name: ['中央商务区', 'Central Business District'],
            secondaryName: false,
            num: '18',
            services: ['local'],
            parents: ['z5ba'],
            children: ['p1x7'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[['guangzhou', 'gz4', '#00843D', '#fff', '5号线', 'Line 5']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        z5ba: {
            name: ['农业东路', 'Nongye Road (E)'],
            secondaryName: false,
            num: '17',
            services: ['local'],
            parents: ['36qp'],
            children: ['kly4'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        '36qp': {
            name: ['龙湖中环南', 'Longhu Middle Ring Road (S)'],
            secondaryName: false,
            num: '16',
            services: ['local'],
            parents: ['vxlj'],
            children: ['z5ba'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[['guangzhou', 'gfl', '#C4D600', '#fff', '8号线', 'Line 8']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        vxlj: {
            name: ['龙湖南', 'Long Lake (S)'],
            secondaryName: false,
            num: '15',
            services: ['local'],
            parents: ['9x8a'],
            children: ['36qp'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        '9x8a': {
            name: ['金融岛南', 'Zhengzhou \\Finance Island (S)'],
            secondaryName: ['暂缓开通', 'Stay Open'],
            num: '14',
            services: ['local'],
            parents: ['64kj'],
            children: ['vxlj'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        '64kj': {
            name: ['金融岛北', 'Zhengzhou \\Finance Island (N)'],
            secondaryName: ['暂缓开通', 'Stay Open'],
            num: '13',
            services: ['local'],
            parents: ['5h9o'],
            children: ['9x8a'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        '5h9o': {
            name: ['龙湖北', 'Long Lake (N)'],
            secondaryName: false,
            num: '12',
            services: ['local'],
            parents: ['brqw'],
            children: ['64kj'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        brqw: {
            name: ['龙湖中环北', 'Longhu Middle Ring Road (N)'],
            secondaryName: false,
            num: '11',
            services: ['local'],
            parents: ['e42t'],
            children: ['5h9o'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        e42t: {
            name: ['清华附中', 'High School affiliated to \\Tsinghua University'],
            secondaryName: false,
            num: '10',
            services: ['local'],
            parents: ['4z1h'],
            children: ['brqw'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[['guangzhou', 'gz6', '#80225F', '#fff', '6号线', 'Line 6']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        '4z1h': {
            name: ['森林公园北', 'Long Lake Wetland Park (N)'],
            secondaryName: false,
            num: '09',
            services: ['local'],
            parents: ['ulie'],
            children: ['e42t'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        ulie: {
            name: ['杨君刘', 'Yang Jun Liu'],
            secondaryName: false,
            num: '08',
            services: ['local'],
            parents: ['bhsb'],
            children: ['4z1h'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        bhsb: {
            name: ['沙门', 'Sha Men'],
            secondaryName: false,
            num: '07',
            services: ['local'],
            parents: ['zces'],
            children: ['ulie'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[['other', 'other', '#F3D03E', '#fff', '2号线', 'Line 2']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        zces: {
            name: ['陈寨东', 'Chen Zhai (E)'],
            secondaryName: false,
            num: '06',
            services: ['local'],
            parents: ['8hu4'],
            children: ['bhsb'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        '8hu4': {
            name: ['张家村', 'Zhang Jia Chun'],
            secondaryName: false,
            num: '05',
            services: ['local'],
            parents: ['eal0'],
            children: ['zces'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[['other', 'other', '#F79102', '#fff', '7号线', 'Line 7']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        eal0: {
            name: ['丰庆路', 'Fengqing Road'],
            secondaryName: false,
            num: '04',
            services: ['local'],
            parents: ['j0wm'],
            children: ['8hu4'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        uiml: {
            name: ['七里河', 'Qili River'],
            secondaryName: false,
            num: '23',
            services: ['local'],
            parents: ['c06y'],
            children: ['8jm8'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[['guangzhou', 'gz4', '#00843D', '#fff', '5号线', 'Line 5']]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        '8jm8': {
            name: ['果树所', 'Guo Shu Suo'],
            secondaryName: false,
            num: '24',
            services: ['local'],
            parents: ['uiml'],
            children: ['2yuh'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        '2yuh': {
            name: ['金岱', 'Jin Dai'],
            secondaryName: false,
            num: '25',
            services: ['local'],
            parents: ['8jm8'],
            children: ['q9yj'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        q9yj: {
            name: ['姚庄', 'Yao Zhuang'],
            secondaryName: false,
            num: '26',
            services: ['local'],
            parents: ['2yuh'],
            children: ['hf3z'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
    },
    line_name: ['4号线', 'Line 4'],
    psd_num: '1',
    line_num: '4',
    info_panel_type: 'gz28',
    direction_gz_x: 50,
    direction_gz_y: 70,
    customiseMTRDest: {
        isLegacy: false,
        terminal: false,
    },
    svgWidth: {
        destination: 1050,
        runin: 1800,
        railmap: 3000,
        indoor: 1050,
    },
    notesGZMTR: [['6号线、7号线、8号线暂缓开通', 'Line 6, Line 7 and Line 8 have been suspended', 0, 7.5, false]],
    namePosMTR: {
        isStagger: true,
        isFlip: false,
    },
    style: 'gzmtr',
};

export default params;
