const params = {
    style: 'gzmtr',
    svg_height: 400,
    padding: 8.750201061605276,
    y_pc: 40,
    branch_spacing: 45,
    theme: ['guangzhou', 'gz6', '#80225F', '#fff'],
    direction: 'r',
    current_stn_idx: 'iwf6',
    platform_num: '2',
    stn_list: {
        linestart: {
            parents: [],
            children: ['iwf6'],
            name: ['路綫右端', 'RIGHT END'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [[]],
            },
            services: ['local'],
            facility: '',
            num: '11',
            secondaryName: false,
        },
        lineend: {
            parents: ['q9b3'],
            children: [],
            name: ['路綫左端', 'LEFT END'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [[]],
            },
            services: ['local'],
            facility: '',
            num: '00',
            secondaryName: false,
        },
        l1mz: {
            parents: ['iwf6'],
            children: ['vcfk'],
            name: ['奥体中心', 'Zhengzhou \\Olympic Sports Center'],
            branch: {
                left: [],
                right: [],
            },
            num: '09',
            transfer: {
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [[['chengdu', 'cd12', '#772583', '#fff', '14号线', 'Line 14']]],
            },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        iwf6: {
            children: ['l1mz'],
            parents: ['linestart'],
            name: ['常庄', 'Chang Zhuang'],
            branch: {
                left: [],
                right: [],
            },
            num: '10',
            transfer: {
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
                info: [[]],
            },
            services: ['local'],
            facility: '',
            secondaryName: false,
        },
        q9b3: {
            name: ['贾峪', 'Jia Yu'],
            secondaryName: false,
            num: '01',
            services: ['local'],
            parents: ['w6w7'],
            children: ['lineend'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        w6w7: {
            name: ['洞林湖', 'Donglin Lake'],
            secondaryName: false,
            num: '02',
            services: ['local'],
            parents: ['0c7a'],
            children: ['q9b3'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        '0c7a': {
            name: ['洞林寺', 'Dong Lin Si'],
            secondaryName: false,
            num: '03',
            services: ['local'],
            parents: ['77vp'],
            children: ['w6w7'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        '77vp': {
            name: ['安宁路', 'Anning Road'],
            secondaryName: false,
            num: '04',
            services: ['local'],
            parents: ['tko1'],
            children: ['0c7a'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        tko1: {
            name: ['马寨', 'Ma Zhai'],
            secondaryName: false,
            num: '05',
            services: ['local'],
            parents: ['63sm'],
            children: ['77vp'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        '63sm': {
            name: ['河南建院', 'Henan Technical College \\Of Construction'],
            secondaryName: false,
            num: '06',
            services: ['local'],
            parents: ['briz'],
            children: ['tko1'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        briz: {
            name: ['金桢路', 'Jinzhen Road'],
            secondaryName: false,
            num: '07',
            services: ['local'],
            parents: ['vcfk'],
            children: ['63sm'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
        vcfk: {
            name: ['玉轩路', 'Yuxuan Road'],
            secondaryName: false,
            num: '08',
            services: ['local'],
            parents: ['l1mz'],
            children: ['briz'],
            branch: {
                left: [],
                right: [],
            },
            transfer: {
                info: [[]],
                tick_direc: 'r',
                paid_area: true,
                osi_names: [],
            },
            facility: '',
        },
    },
    line_name: ['6号线', 'Line 6'],
    psd_num: '1',
    line_num: '6',
    info_panel_type: 'gz28',
    direction_gz_x: 50,
    direction_gz_y: 70,
    customiseMTRDest: {
        isLegacy: false,
        terminal: false,
    },
    svgWidth: {
        destination: 1500,
        runin: 1500,
        railmap: 2000,
        indoor: 800,
    },
    notesGZMTR: [
        [
            '冯湾站至清华附中站暂缓开通',
            'Fengwan station to High School affiliated to Tsinghua University suspended the opening',
            0,
            11,
            false,
        ],
    ],
    namePosMTR: {
        isStagger: true,
        isFlip: false,
    },
};

export default params;
